### PR TITLE
doc: Fixes typo in the documentation

### PR DESCRIPTION
**Pull request by digiserg**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@digiserg
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @digiserg 
Could you sign the CLA?

**Comment by digiserg** [comment]
> Thanks for the PR @digiserg Could you sign the CLA?

Done

**Review by apeabody — APPROVED** [review]
LGTM - Thanks for the contribution @digiserg!

**Pull request merged**
