### PR TITLE
chore: Delete Stale CODEOWNERS

### PR DESCRIPTION
**Pull request by apeabody**
Standardizing to /CODEOWNERS

### CODE REVIEW

**Review by bharathkkb — APPROVED** [review]

**Comment by apeabody** [comment]
Wait for https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1291

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
