### PR TITLE
fix: change asm module depends_on method

### PR DESCRIPTION
**Pull request by apeabody**
* Workaround for https://github.com/terraform-google-modules/terraform-google-gcloud/issues/123

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Comment by aablsk** [comment]
Really appreciate the quick fix on this issue as this is blocking my current project. Can you give any indication on when this might be merged? 
Thank you for your time and consideration! 🙏

**Comment by apeabody** [comment]
Enhanced docs per [terraform-google-gcloud/issues/123](https://github.com/terraform-google-modules/terraform-google-gcloud/issues/123)

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by apeabody** [comment]
> Really appreciate the quick fix on this issue as this is blocking my current project. Can you give any indication on when this might be merged? Thank you for your time and consideration! 🙏

Hi @aablsk - It should be included in this release: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1355

**Pull request merged**
