### PR TITLE
add config_connector to safer variant

### PR DESCRIPTION
**Pull request by jmymy**

### CODE REVIEW

**Comment by zolech** [comment]
Hi. Is there any possibility to merge this into private_cluster submodule?

**Comment by morgante** [comment]
@zolech It's already available on the beta_private_cluster: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/beta-private-cluster

**Comment by zolech** [comment]
I know, but I am avoiding anything that has "beta" in it's name. Is there any reason that this feature is not in a "private_cluster" submodule?

**Comment by morgante** [comment]
`config_connector_config` is only supported in beta: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#config_connector_config

**Comment by zolech** [comment]
Ah ok. I didn't realized that there is a second beta provider. Thanks for the clarification. I will try to switch to beta submodule then.

**Pull request merged**
