### PR TITLE
fix(beta-private-cluster-update-variant): version constraint deprecation

### PR DESCRIPTION
**Pull request by jai**
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/763

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by morgante — CHANGES_REQUESTED** [review]
Changes need to be made in `autogen/` then propagated via `make build`.

**Comment by ivanblack19** [comment]
Wuld appeciate uf sone one handle

**Comment by jai** [comment]
Hi - fixed (I think) but CI is still failing. Let me know if I'm doing something wrong, thanks!

**Comment by jai** [comment]
@morgante how do you guys handle `terraform fmt`? After `make build` I did a `terraform fmt` which did some reformatting in my files as well as unrelated files - I didn't check the unrelated files in, not sure if that's what's causing the lint check to fail?

**Review by bharathkkb — CHANGES_REQUESTED** [review]
@jai you should be able to run `terraform fmt -recursive` to fix the lint issue. You can also run the lint test locally `make docker_test_lint`.

**Comment by jai** [comment]
@bharathkkb @morgante I've fmt'ed all the files and pushed them, however still getting this from `terraform fmt` - do I just delete the `{{ autogeneration_note }}` tags?

```bash
Error: Argument or block definition required

  on autogen/main/networks.tf line 17:
  17: {{ autogeneration_note }}

An argument or block definition is required here.


Error: Argument or block definition required

  on autogen/main/variables_defaults.tf line 17:
  17: {{ autogeneration_note }}

An argument or block definition is required here.
```

**Comment by jai** [comment]
Looks like the `{{ autogen }}` tags exist on `master` as well so I'll just leave them until someone says otherwise

**Comment by bharathkkb** [comment]
@jai that should be okay but I noticed some fmt issues were introduced in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/764/commits/25a506058076ab7d8d18721c5919e3237d39f828. I will try to fix at https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/764/commits/f019ea48c0c4b7b8b62ff8429577f1801da16c8e after which has the necessary changes.

**Comment by bharathkkb** [comment]
Looks like fmt produces slightly different results in 0.14 (https://github.com/hashicorp/terraform/pull/26390) as opposed to 0.12.29 (which is the current lint CI image) and hence the complaining. I am going to make it complaint with the CI image fmt for the time being.

**Comment by bharathkkb** [comment]
@morgante we may have an edge case in `check_generate_modules`; looks like it does not take fmt into account as it just generates and does a diff. This can lead to slightly different whitespace depending on length of LHS of `=` like in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/764/commits/ac03f08b5f0d172c30fc5c84a131c16b8ce81037

**Comment by jai** [comment]
@bharathkkb IIUC you mean leave the lint/formatting introduced by Terraform 0.14.2 as-is?

So lmk if I need to make other changes?

**Comment by bharathkkb** [comment]
superseded by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/774

**Pull request closed without merging**
