### PR TITLE
Enable vertical pod autoscaling

### PR DESCRIPTION
**Pull request by kolesnikovIV**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/terraform-google-kubernetes-engine/README.md /tmp/tmp.RRygzQBJ8U/generate_docs/workspace/terraform-google-kubernetes-engine/README.md
154a155
> | vertical\_pod\_autoscaling | Enable vertical pod autoscaling | bool | `"false"` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./variables.tf:86:   
./variables.tf:92:  
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
variables.tf
--- old/variables.tf
+++ new/variables.tf
@@ -83,13 +83,13 @@
   description = "Enable horizontal pod autoscaling addon"
   default     = true
 }
-   
+
 variable "vertical_pod_autoscaling" {
   type        = bool
   description = "Enable vertical pod autoscaling"
   default     = false
- }
-  
+}
+
 variable "http_load_balancing" {
   type        = bool
   description = "Enable httpload balancer addon"
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by bharathkkb** [comment]
@kolesnikovIV I see that `vertical_pod_autoscaling` is supported in our beta module, so it would be just a matter of graduating it by moving [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/7fc3b488ed6db60fdc081258146270da4dda7ab9/autogen/main/cluster.tf.tmpl#L97) and [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/f93eac01500f3fe04a9fe43dcbdf5c60953258af/autogen/main/variables.tf.tmpl#L492) out of the `{% if beta_cluster %}...{% endif %}` block and running `make build`.

**Comment by kolesnikovIV** [comment]
> @kolesnikovIV I see that `vertical_pod_autoscaling` is supported in our beta module, so it would be just a matter of graduating it by moving [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/7fc3b488ed6db60fdc081258146270da4dda7ab9/autogen/main/cluster.tf.tmpl#L97) and [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/f93eac01500f3fe04a9fe43dcbdf5c60953258af/autogen/main/variables.tf.tmpl#L492) out of the `{% if beta_cluster %}...{% endif %}` block and running `make build`.

ahh, sorry, missed it. Just updated PR.

**Comment by bharathkkb** [comment]
@kolesnikovIV `vertical_pod_autoscaling` is already defined [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/7fc3b488ed6db60fdc081258146270da4dda7ab9/autogen/main/cluster.tf.tmpl#L97). IIUC we want to make `vertical_pod_autoscaling` available in the GA module and for that we would need to remove it from within the `{% if beta_cluster %}...{% endif %}` blocks.

**Comment by kolesnikovIV** [comment]
> @kolesnikovIV `vertical_pod_autoscaling` is already defined [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/7fc3b488ed6db60fdc081258146270da4dda7ab9/autogen/main/cluster.tf.tmpl#L97). IIUC we want to make `vertical_pod_autoscaling` available in the GA module and for that we would need to remove it from within the `{% if beta_cluster %}...{% endif %}` blocks.

yep, PR updated

**Comment by bharathkkb** [comment]
Hi @kolesnikovIV 
Anything I can do to help with this? 
I think whats remaining is to move the `enable_vertical_pod_autoscaling` variable block from the `{% if beta_cluster %}...{% endif %}` block [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/dffb04774f81cd0a9e2459c411eb75cde8b705d2/autogen/main/variables.tf.tmpl#L492).

**Comment by kolesnikovIV** [comment]
> Hi @kolesnikovIV
> Anything I can do to help with this?
> I think whats remaining is to move the `enable_vertical_pod_autoscaling` variable block from the `{% if beta_cluster %}...{% endif %}` block [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/dffb04774f81cd0a9e2459c411eb75cde8b705d2/autogen/main/variables.tf.tmpl#L492).

ahh, thank you for your advice, just committed.

**Comment by descampsk** [comment]
Hello,
Need help on this ? 
I would like to have this feature too !

**Comment by morgante** [comment]
@descampsk This still needs to be rebased on `master`, so maybe you could help @kolesnikovIV with that?

**Comment by bharathkkb** [comment]
superseded by #758

**Pull request closed without merging**
