### PR TITLE
Add support for https_proxy parameter for the config_sync.git block

### PR DESCRIPTION
**Pull request by muresan**
Add support for https_proxy parameter for the config_sync.git block

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@muresan
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/acm/README.md /tmp/tmp.XlhjAdC7yE/workspace/modules/acm/README.md
76a77
> | https\_proxy | URL for the HTTPS proxy to be used when communicating with the Git repo. | `string` | `null` | no |
82d82
< | https\_proxy | URL for the HTTPS proxy to be used when communicating with the Git repo. | `string` | `null` | no |
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/acm/README.md /tmp/tmp.HIUyZhXT6k/generate_docs/workspace/modules/acm/README.md
76a77
> | https\_proxy | URL for the HTTPS proxy to be used when communicating with the Git repo. | `string` | `null` | no |
82d82
< | https\_proxy | URL for the HTTPS proxy to be used when communicating with the Git repo. | `string` | `null` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@muresan
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/acm/README.md /tmp/tmp.9VR29zhGQH/workspace/modules/acm/README.md
76a77
> | https\_proxy | URL for the HTTPS proxy to be used when communicating with the Git repo. | `string` | `null` | no |
82d82
< | https\_proxy | URL for the HTTPS proxy to be used when communicating with the Git repo. | `string` | `null` | no |
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/acm/README.md /tmp/tmp.BK8nBRqFwH/generate_docs/workspace/modules/acm/README.md
76a77
> | https\_proxy | URL for the HTTPS proxy to be used when communicating with the Git repo. | `string` | `null` | no |
82d82
< | https\_proxy | URL for the HTTPS proxy to be used when communicating with the Git repo. | `string` | `null` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@muresan
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by Jberlinsky** [comment]
@bharathkkb I haven't contributed here for a while (although I'm excited to get back into it :) ) so I'm not comfortable approving myself, but @muresan and I are working on a customer engagement together where this is necessary -- it would be great to get a rapid review of this one.

**Review by bharathkkb — APPROVED** [review]
@muresan Thanks for the PR!  The build failure looks unrelated.
@Jberlinsky np :)

**Pull request merged**
