### PR TITLE
fix: remove quotes from references

### PR DESCRIPTION
**Pull request by naseemkullah**
To address 
> Warning: Quoted references are deprecated

### CODE REVIEW

**Comment by naseemkullah** [comment]
As a generality for the entire terraform-google-modules project, it would be nice to make the build logs public a la circle CI

**Comment by morgante** [comment]
Thanks for the fix. The CI error is unrelated (GCE stockout).

**Comment by naseemkullah** [comment]
My pleasure, good to know!

**Comment by morgante** [comment]
Also, unfortunately it's currently mot possible to make Cloud Build logs public. We'd love to if we could.

**Comment by naseemkullah** [comment]
Ah I see. Do you know if there is a public issue I can track/star regarding this?

**Comment by morgante** [comment]
https://b.corp.google.com/issues/122321153 is probably the closest I could find publicly

**Comment by naseemkullah** [comment]
Seems to be internal to the big G, requiring "moma" SSO ? 
Good to know there is an internal issue for this though! Thanks.

**Comment by naseemkullah** [comment]
Vintage style 😄 
image

**Comment by morgante** [comment]
Oops, http://issuetracker.google.com/issues/122321153 is the public link.

**Pull request merged**
