### PR TITLE
feat: add security posture

### PR DESCRIPTION
**Pull request by mmorejon**
Adds support for security posture configuration - https://cloud.google.com/kubernetes-engine/docs/concepts/about-security-posture-dashboard

Duplicated: #1719 #1694

### CODE REVIEW

**Comment by chandra-scentre** [comment]
please someone review this and fix it.

**Comment by cmreddyv** [comment]
please someone review and fix it.

**Comment by mmorejon** [comment]
@apeabody , could you run the tests?

**Comment by cmreddyv** [comment]
please let us know, when this will be merged to master ?

**Comment by ebeltramo96** [comment]
any news?

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @mmorejon!

**Comment by cmreddyv** [comment]
Thank you @apeabody for merging and @mmorejon for the PR.

Please let me know, by when this will be available for Terraform Tag release. current 28 version does not have the security posture config

**Comment by apeabody** [comment]
> Thank you @apeabody for merging and @mmorejon for the PR.
> 
> Please let me know, by when this will be available for Terraform Tag release. current 28 version does not have the security posture config

Hi @cmreddyv - I should be included when v29.0.0 is released (https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1746), if needed you can also source the repo head directly in the meantime.

**Pull request merged**
