### PR TITLE
feat: add network tags to auto-provisioned node pools

### PR DESCRIPTION
**Pull request by MyMirelHub**

### CODE REVIEW

**Comment by g-awmalik** [comment]
@MyMirelHub - are you still working on this PR? If not, can you flip its status?

**Comment by g-awmalik** [comment]
@MyMirelHub - can you please rebase this with master since I'm unable to do it for you.

**Comment by g-awmalik** [comment]
Please rebase again.

**Comment by MyMirelHub** [comment]
fixed by #1920

**Pull request closed without merging**
