### PR TITLE
fix: add network tag

### PR DESCRIPTION
**Pull request by rochana-atapattu**
Adding the network tag used by the firewall rule to the nodes

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@rochana-atapattu
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-autopilot-private-cluster/cluster.tf /tmp/tmp.NbLzVfoa5P/workspace/modules/beta-autopilot-private-cluster/cluster.tf
212,216d211
<   node_pool_auto_config {
<     network_tags {
<       tags = [local.cluster_network_tag]
<     }
<   }
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
@rochana-atapattu
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@rochana-atapattu
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by rochana-atapattu** [comment]
creating new pr with branch  beta-network-tags

**Pull request closed without merging**
