### PR TITLE
Allow datapath_provider in GA main module

### PR DESCRIPTION
**Pull request by somethingnew2-0**
First time contributor implementing https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1074

Had to bump the main module GA google provider to 3.55.0 to enable `datapath_provider` being GA https://github.com/hashicorp/terraform-provider-google/blob/e2e533f83c388fecbf51ae8ca541326b152cede0/CHANGELOG.md#3550-february-1-2021

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate . 
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part1/terraform 
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part2/terraform 
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part3/terraform 
Success!
 The configuration is valid.
terraform_validate ./examples/deploy_service 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/disable_client_cert 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/node_pool 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 22, in provider "google-beta":
│
 
  22:   version = 
"~> 3.90.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/node_pool_update_variant 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/node_pool_update_variant_beta 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 22, in provider "google-beta":
│
 
  22:   version     = 
"~> 3.79.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/node_pool_update_variant_public_beta 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 22, in provider "google-beta":
│
 
  22:   version     = 
"~> 3.79.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/private_zonal_with_networking 
Success!
 The configuration is valid.
terraform_validate ./examples/regional_private_node_pool_oauth_scopes 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints >=
│
 
2.12.0, ~> 3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/safer_cluster 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 34, in provider "google":
│
 
  34:   version = 
"~> 3.42.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and one more similar warning elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/safer_cluster_iap_bastion 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on provider.tf line 18, in provider "google":
│
 
  18:   version = 
"~> 3.52.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and one more similar warning elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/shared_vpc 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/simple_regional 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/simple_regional_beta 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 22, in provider "google-beta":
│
 
  22:   version = 
"~> 3.79.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/simple_regional_private 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/simple_regional_private_beta 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 22, in provider "google":
│
 
  22:   version = 
"~> 3.42.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and one more similar warning elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/simple_regional_with_kubeconfig 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/simple_regional_with_networking 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints >=
│
 
2.12.0, ~> 3.45.0, ~> 3.45, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/simple_zonal_private 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/simple_zonal_with_acm 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/simple_zonal_with_asm 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 22, in provider "google-beta":
│
 
  22:   version = 
"~> 3.79.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and one more similar warning elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/simple_zonal_with_hub 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/simple_zonal_with_hub_kubeconfig 
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/stub_domains_private 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/stub_domains_upstream_nameservers 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/upstream_nameservers 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/workload_identity 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints >=
│
 
3.39.0, ~> 3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./examples/workload_metadata_config 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 22, in provider "google-beta":
│
 
  22:   version = 
"~> 3.79.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./modules/acm 
Success!
 The configuration is valid.
terraform_validate ./modules/asm 
Success!
 The configuration is valid.
terraform_validate ./modules/auth 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/binary-authorization 
Success!
 The configuration is valid.
terraform_validate ./modules/config-sync 
Success!
 The configuration is valid.
terraform_validate ./modules/hub 
Success!
 The configuration is valid.
terraform_validate ./modules/k8s-operator-crd-support 
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/services 
Success!
 The configuration is valid.
terraform_validate ./modules/workload-identity 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/beta_cluster 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on ../../../examples/simple_regional_beta/main.tf line 22, in provider "google-beta":
│
 
  22:   version = 
"~> 3.79.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/deploy_service 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/disable_client_cert 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/node_pool 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on ../../../examples/node_pool/main.tf line 22, in provider "google-beta":
│
 
  22:   version = 
"~> 3.90.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/node_pool_update_variant 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/private_zonal_with_networking 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on ../../../examples/safer_cluster/main.tf line 34, in provider "google":
│
 
  34:   version = 
"~> 3.42.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and one more similar warning elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/safer_cluster_iap_bastion 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on ../../../examples/safer_cluster_iap_bastion/provider.tf line 18, in provider "google":
│
 
  18:   version = 
"~> 3.52.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and one more similar warning elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/sandbox_enabled 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on ../../../examples/simple_regional_beta/main.tf line 22, in provider "google-beta":
│
 
  22:   version = 
"~> 3.79.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/simple_regional 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/simple_regional_private 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/simple_regional_with_kubeconfig 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/simple_regional_with_networking 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints >=
│
 
2.12.0, ~> 3.45.0, ~> 3.45, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/simple_zonal 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/simple_zonal_private 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/simple_zonal_with_asm 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 24, in provider "google":
│
 
  24:   version = 
"~> 3.63.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and 2 more similar warnings elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/stub_domains 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/stub_domains_private 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/stub_domains_upstream_nameservers 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/upstream_nameservers 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~>
│
 
3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/workload_identity 
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints >=
│
 
3.39.0, ~> 3.42.0, >= 3.55.0, < 4.0.0
╵
terraform_validate ./test/fixtures/workload_metadata_config 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on ../../../examples/workload_metadata_config/main.tf line 22, in provider "google-beta":
│
 
  22:   version = 
"~> 3.79.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/setup 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on versions.tf line 22, in provider "google":
│
 
  22:   version = 
"3.50.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and one more similar warning elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
 ```

**Review by bharathkkb — CHANGES_REQUESTED** [review]
Thanks for the PR @somethingnew2-0 
Looks like we will also need to bump https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/a0303606209234179ee0a480f8a91c6073301555/examples/simple_regional_with_networking/main.tf#L18

**Comment by alexandruivan** [comment]
Hello. Is anyone looking to finish this work or I can pick it up and finish it?

**Comment by somethingnew2-0** [comment]
@bharathkkb @alexandruivan rebased and fixed the version issue

**Review by morgante — APPROVED** [review]

**Pull request merged**
