### PR TITLE
Add spot vm support to beta clusters

### LINKED ISSUE #1127: Support for Spot instances in node pools?
### TL;DR

Any support for spot instances?

### Terraform Resources

_No response_

### Detailed design

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by adrianchifor**
Fixes #1127

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster/README.md /tmp/tmp.XOkLSiBHAW/workspace/modules/beta-private-cluster/README.md
74d73
<       spot                      = false
311d309
< | spot | A boolean that represents whether the underlying node VMs are spot | false | Optional |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster/cluster.tf /tmp/tmp.XOkLSiBHAW/workspace/modules/beta-private-cluster/cluster.tf
469d468
<     spot = lookup(each.value, "spot", false)
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster-update-variant/README.md /tmp/tmp.XOkLSiBHAW/workspace/modules/beta-private-cluster-update-variant/README.md
96d95
<       spot                      = false
333d331
< | spot | A boolean that represents whether the underlying node VMs are spot | false | Optional |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster-update-variant/cluster.tf /tmp/tmp.XOkLSiBHAW/workspace/modules/beta-private-cluster-update-variant/cluster.tf
373d372
<     "spot",
555d553
<     spot = lookup(each.value, "spot", false)
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster/README.md /tmp/tmp.XOkLSiBHAW/workspace/modules/beta-public-cluster/README.md
68d67
<       spot                      = false
298d296
< | spot | A boolean that represents whether the underlying node VMs are spot | false | Optional |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster/cluster.tf /tmp/tmp.XOkLSiBHAW/workspace/modules/beta-public-cluster/cluster.tf
450d449
<     spot = lookup(each.value, "spot", false)
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster-update-variant/README.md /tmp/tmp.XOkLSiBHAW/workspace/modules/beta-public-cluster-update-variant/README.md
90d89
<       spot                      = false
320d318
< | spot | A boolean that represents whether the underlying node VMs are spot | false | Optional |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster-update-variant/cluster.tf /tmp/tmp.XOkLSiBHAW/workspace/modules/beta-public-cluster-update-variant/cluster.tf
354d353
<     "spot",
536d534
<     spot = lookup(each.value, "spot", false)
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/beta-public-cluster/cluster.tf
--- old/modules/beta-public-cluster/cluster.tf
+++ new/modules/beta-public-cluster/cluster.tf
@@ -447,7 +447,7 @@
       local.service_account,
     )
     preemptible = lookup(each.value, "preemptible", false)
-    spot = lookup(each.value, "spot", false)
+    spot        = lookup(each.value, "spot", false)
 
     oauth_scopes = concat(
       local.node_pools_oauth_scopes["all"],
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/beta-public-cluster-update-variant/cluster.tf
--- old/modules/beta-public-cluster-update-variant/cluster.tf
+++ new/modules/beta-public-cluster-update-variant/cluster.tf
@@ -533,7 +533,7 @@
       local.service_account,
     )
     preemptible = lookup(each.value, "preemptible", false)
-    spot = lookup(each.value, "spot", false)
+    spot        = lookup(each.value, "spot", false)
 
     oauth_scopes = concat(
       local.node_pools_oauth_scopes["all"],
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/beta-private-cluster-update-variant/cluster.tf
--- old/modules/beta-private-cluster-update-variant/cluster.tf
+++ new/modules/beta-private-cluster-update-variant/cluster.tf
@@ -552,7 +552,7 @@
       local.service_account,
     )
     preemptible = lookup(each.value, "preemptible", false)
-    spot = lookup(each.value, "spot", false)
+    spot        = lookup(each.value, "spot", false)
 
     oauth_scopes = concat(
       local.node_pools_oauth_scopes["all"],
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/beta-private-cluster/cluster.tf
--- old/modules/beta-private-cluster/cluster.tf
+++ new/modules/beta-private-cluster/cluster.tf
@@ -466,7 +466,7 @@
       local.service_account,
     )
     preemptible = lookup(each.value, "preemptible", false)
-    spot = lookup(each.value, "spot", false)
+    spot        = lookup(each.value, "spot", false)
 
     oauth_scopes = concat(
       local.node_pools_oauth_scopes["all"],
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by adrianchifor** [comment]
Needs a bit more work on the versioning conflicts

**Review by bharathkkb — CHANGES_REQUESTED** [review]
@adrianchifor Could you rebase on main? It would be great to get this for our breaking release.

**Comment by domino7** [comment]
Hi @bharathkkb, @adrianchifor, I was working on the same, waiting with PR for recent providers updates. I opened https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1133 rebased on main just in case @adrianchifor will be not able to move forward with this before next release cycle

**Comment by adrianchifor** [comment]
Thanks @domino7 but I've just rebased and updated.

cc @bharathkkb

**Comment by adrianchifor** [comment]
@bharathkkb Any chance we can merge this? Would like to try out the new release tomorrow on a few node pools.

**Review by bharathkkb — APPROVED** [review]
Could you also mention the min beta provider required in this upgrade guide: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/upgrading_to_v18.0.md?

**Comment by adrianchifor** [comment]
Noted 4.3+ on google-beta.

**Pull request merged**
