### PR TITLE
feat!: K8s provider upgrade

### PR DESCRIPTION
**Pull request by pib**
Updates kubernetes provider to ~> 2.0.

See https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/816

I'm not set up to run the integration tests right now, but I did make sure that `make docker_test_lint` was happy.

### CODE REVIEW

**Comment by morgante** [comment]
Integration test failure is unrelated.

**Comment by pib** [comment]
It doesn't seem to have done another build?

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
