### PR TITLE
feat: Default image type for gke sandbox

### PR DESCRIPTION
**Pull request by diegolnasc**

### CODE REVIEW

**Review by morgante — CHANGES_REQUESTED** [review]
Please make sure that modules are generated from autogen templates:

```
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/cluster.tf /tmp/tmp.I6Ocwbpd7l/workspace/cluster.tf
236c236
<     image_type   = lookup(each.value, "image_type", "COS")
---
>     image_type   = lookup(each.value, "image_type", var.sandbox_enabled ? "COS_CONTAINERD" : "COS")
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster/cluster.tf /tmp/tmp.I6Ocwbpd7l/workspace/modules/private-cluster/cluster.tf
249c249
<     image_type   = lookup(each.value, "image_type", "COS")
---
>     image_type   = lookup(each.value, "image_type", var.sandbox_enabled ? "COS_CONTAINERD" : "COS")
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster-update-variant/cluster.tf /tmp/tmp.I6Ocwbpd7l/workspace/modules/private-cluster-update-variant/cluster.tf
333c333
<     image_type   = lookup(each.value, "image_type", "COS")
---
>     image_type   = lookup(each.value, "image_type", var.sandbox_enabled ? "COS_CONTAINERD" : "COS")
Error: submodule's files generation has not been run, please run the
```

**Comment by diegolnasc** [comment]
> Please make sure that modules are generated from autogen templates:
> 
> ```
> diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/cluster.tf /tmp/tmp.I6Ocwbpd7l/workspace/cluster.tf
> 236c236
> <     image_type   = lookup(each.value, "image_type", "COS")
> ---
> >     image_type   = lookup(each.value, "image_type", var.sandbox_enabled ? "COS_CONTAINERD" : "COS")
> diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster/cluster.tf /tmp/tmp.I6Ocwbpd7l/workspace/modules/private-cluster/cluster.tf
> 249c249
> <     image_type   = lookup(each.value, "image_type", "COS")
> ---
> >     image_type   = lookup(each.value, "image_type", var.sandbox_enabled ? "COS_CONTAINERD" : "COS")
> diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster-update-variant/cluster.tf /tmp/tmp.I6Ocwbpd7l/workspace/modules/private-cluster-update-variant/cluster.tf
> 333c333
> <     image_type   = lookup(each.value, "image_type", "COS")
> ---
> >     image_type   = lookup(each.value, "image_type", var.sandbox_enabled ? "COS_CONTAINERD" : "COS")
> Error: submodule's files generation has not been run, please run the
> ```

Oh, that's right.
Can you check again?

**Review by morgante — APPROVED** [review]

**Comment by morgante** [comment]
@diegolnasc Thanks for the PR! 🚀

**Pull request merged**
