### PR TITLE
feat!: Update least privilege default service account

### PR DESCRIPTION
**Pull request by gorge511**
This update follows changes from #1757 and reverts #1827.

The role `roles/container.nodeServiceAccount` is deprecated now and it is replaced with new `roles/container.defaultNodeServiceAccount` role. Unfortunately this is not yet documented in Google docs.

As the scope of the new role is smaller than the old one, this should be considered breaking change.

### CODE REVIEW

**Comment by apeabody** [comment]
marked as breaking change per PR comment

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @gorge511!

**Comment by gorge511** [comment]
> Thanks for the contribution @gorge511!

Thanks for accepting my ideas and changes.

**Comment by davem-git** [comment]
how do we update to this from an older version? will it just delete and recreate this without any downtime?

**Comment by hSATAC** [comment]
Can anyone confirm is there any downtime of this SA recreation for old clusters upgraded to v30?

**Comment by mmorejon** [comment]
@gorge511 , could you share a reference about `oles/container.defaultNodeServiceAccount`? You mentioned there aren't docs in GCP but I was looking into the roles directly through the `gcloud` cli and I couldn't find anything about it.

**Comment by gorge511** [comment]
> Can anyone confirm is there any downtime of this SA recreation for old clusters upgraded to v30?

Hi @hSATAC this change is without any downtime.

**Comment by gorge511** [comment]
> @gorge511 , could you share a reference about `oles/container.defaultNodeServiceAccount`? You mentioned there aren't docs in GCP but I was looking into the roles directly through the `gcloud` cli and I couldn't find anything about it.

Hi @mmorejon, please see #1757 for a bigger discussion of why I did this PR. This is quite a new thing, but you can find the role easily with `gcloud iam roles describe roles/container.defaultNodeServiceAccount` and read all its permissions.

Unfortunately, this is so new that the public docs are not updated yet, but I got a thumbs up for using it from our Google TAM who consulted this with GKE developer team.

**Pull request merged**
