### PR TITLE
[WIP] Adding new integration test

### PR DESCRIPTION
**Pull request by chrislovecnm**
This commit adds a new integration test, which tests the beta
public module.

This fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/180

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@morgante / @aaron-lane I missed something in this CR since the new integration test is not running in concourse.  Any ideas?

**Comment by morgante** [comment]
@chrislovecnm New tests have to be added to the [pipeline config](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/concourse/pipelines/terraform-google-kubernetes-engine.yml#L158) before they get executed.

**Comment by chrislovecnm** [comment]
Well then I need to test more locally.  I am guessing with the file being external to this project that it has the capability to mess up testing across multiple PRs and not just this PR.

**Comment by morgante** [comment]
@chrislovecnm Nothing should "messed up" here, what's not working or still WIP? The expected workflow is:
- Get new tests working locally and merge into repo
- Submit the PR to the CI repo to start running them there.

It's not perfect, but it's not terrible and there are some risks with having the pipeline definition editable in PRs.

**Comment by bohdanyurov-gl** [comment]
@morgante You can probably close this one

**Comment by morgante** [comment]
Replaced by #199.

**Pull request closed without merging**
