### PR TITLE
feat!: Change the default value of "monitoring_enable_managed_prometheus" var to null

### PR DESCRIPTION
**Pull request by legal90**
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1706

~This PR is a continuation of https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1715 by removing the condition for `monitoring_config` and turning it into a "static" block.~

This PR is a continuation of https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/2155. 
Here we change the default value of the variable `monitoring_enable_managed_prometheus` to `null`.

That is supposed to fix the calculation of `local.logmon_config_is_set`. Now it will return `true` no only when `monitoring_enable_managed_prometheus` is set to `true`, but also when it is set to `false`.

### CODE REVIEW

**Comment by legal90** [comment]
@apeabody Thank you! I will take a look at it soon.

**Comment by legal90** [comment]
@apeabody I rolled back my previous changes and implemented the fix using a different approach - by changing the default value of `"monitoring_enable_managed_prometheus"` var to `null`.

Could you please re-trigger the integration test?

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @legal90!

**Pull request merged**
