### PR TITLE
Convert GKE cluster ID lookup to variable to avoid flappy GKE Hub membership

### PR DESCRIPTION
**Pull request by Jberlinsky**
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1434

### CODE REVIEW

**Review by bharathkkb — COMMENTED** [review]
Looking at https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1434, this is likely due to the deferred data source read. Any reason why you need explicit depends-on? The name output from GKE module is already computed which means passing in `cluster_name    = module.gke.name` on hub should implicitly resolve the dependency on the GKE module.

[1]: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/a82c9d1618edc78a83aa9e2d39eaad27d972a03e/outputs.tf#L26

**Comment by comment-bot-dev** [comment]
@Jberlinsky
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part1/terraform
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part2/terraform
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part3/terraform
Success!
 The configuration is valid.
terraform_validate ./examples/deploy_service
Success!
 The configuration is valid.
terraform_validate ./examples/disable_client_cert
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_beta
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_public_beta
Success!
 The configuration is valid.
terraform_validate ./examples/private_zonal_with_networking
Success!
 The configuration is valid.
terraform_validate ./examples/regional_private_node_pool_oauth_scopes
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster_iap_bastion
Success!
 The configuration is valid.
terraform_validate ./examples/shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/simple_autopilot_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_autopilot_public
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_beta
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private_beta
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_networking
Success!
 The configuration is valid.
terraform_validate ./examples/simple_windows_node_pool
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_acm
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on ../../modules/acm/main.tf line 22, in module "registration":
│
 
  22: module "registration" 
{
│
 
│
 
The argument "cluster_id" is required, but no definition was found.
╵
terraform_validate ./examples/simple_zonal_with_asm
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_hub
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on hub.tf line 17, in module "hub":
│
 
  17: module "hub" 
{
│
 
│
 
The argument "cluster_id" is required, but no definition was found.
╵
terraform_validate ./examples/simple_zonal_with_hub_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_private
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./examples/upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./examples/workload_identity
Success!
 The configuration is valid.
terraform_validate ./examples/workload_metadata_config
Success!
 The configuration is valid.
terraform_validate ./modules/acm
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 22, in module "registration":
│
 
  22: module "registration" 
{
│
 
│
 
The argument "cluster_id" is required, but no definition was found.
╵
terraform_validate ./modules/asm
Success!
 The configuration is valid.
terraform_validate ./modules/auth
Success!
 The configuration is valid.
terraform_validate ./modules/beta-autopilot-private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-autopilot-public-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/binary-authorization
Success!
 The configuration is valid.
terraform_validate ./modules/fleet-membership
Success!
 The configuration is valid.
terraform_validate ./modules/hub-legacy
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/services
Success!
 The configuration is valid.
terraform_validate ./modules/workload-identity
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/beta_cluster
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/deploy_service
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/disable_client_cert
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool_update_variant
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/private_zonal_with_networking
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster_iap_bastion
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/sandbox_enabled
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_autopilot_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_autopilot_public
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_networking
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_windows_node_pool
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on ../../../modules/acm/main.tf line 22, in module "registration":
│
 
  22: module "registration" 
{
│
 
│
 
The argument "cluster_id" is required, but no definition was found.
╵
terraform_validate ./test/fixtures/simple_zonal_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_with_asm
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_identity
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_metadata_config
Success!
 The configuration is valid.
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by Jberlinsky** [comment]
@bharathkkb It was indeed the presence of `module.gke` in `depends_on` causing this, thank you! I'm happy to close this PR if you'd rather stick with `data` lookups for this information.

**Comment by bharathkkb** [comment]
@Jberlinsky I am leaning towards closing it as it would add another required var but feel free to reopen issue if any further problems.

**Pull request closed without merging**
