### PR TITLE
feat!: Adding support for variable `networking_mode` in `google_container_cluster`

### PR DESCRIPTION
**Pull request by jcortejoso**
This PR adds the possibility of setting `networking_mode` in `google_container_cluster` resource.
Currently `networking_mode` is only set in beta clusters and is hardcoded to `VPC_NATIVE` value. `VPC_NATIVE` is the [recommended value for GKE networking best practices](https://cloud.google.com/kubernetes-engine/docs/best-practices/networking#vpc-native-clusters), and is kept as default configuration option. 
Autopilot and private cluster can be only be configured using `networking_mode=VPC_NATIVE`, so for those cluster types `networking_mode` cannot be configured.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @jcortejoso 
Is your usecase to create a routes based cluster? Since recommended approach is VPC native and most GKE modes do not support route based, I am wondering if this would be a broadly useful override.

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by jcortejoso** [comment]
> Thanks for the PR @jcortejoso Is your usecase to create a routes based cluster? Since recommended approach is VPC native and most GKE modes do not support route based, I am wondering if this would be a broadly useful override.

Hi @bharathkkb, thank you for taking a look. Our case we are importing gke cluster created time ago when `ROUTES` was the [default networking mode](https://cloud.google.com/kubernetes-engine/docs/how-to/routes-based-cluster) (back in 2021). I guess main use case for supporting this is legacy support. Maybe making this explicit in the variable comment would be helpful?

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by bharathkkb** [comment]
@jcortejoso thanks for explaining. We generally try not to expose legacy options so would it be possible for you to stand up a new cluster a migrate workloads instead?

**Comment by jcortejoso** [comment]
Thanks for the answer @bharathkkb. We have considered redeploying the GKE clusters using `VPC_NATIVE` networking mode, and it is something we have not discarded. Unfortunately some of the affected clusters are serving production workloads, so any change have to been considered with care and time, so we have prioritized other tasks with greater value (like having better migration plan and tooling), and postponed this bc for us having `ROUTES` as networking mode has not any negative impact.

Thanks anyway for considering!

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jcortejoso
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by ericyz** [comment]
Let's close this one for now. 

(Not fixed)

**Pull request closed without merging**
