### PR TITLE
fix!: enable private nodes with specified pod ip range

### LINKED ISSUE #1493: Unable to enable private nodes when creating nodes with specified pod ip range
### TL;DR

We are trying to create private nodes with our specified pod ip range
So we set the variable enable_private_nodes to true.
After the change, the terraform plan is broken. It seems the provider kubernetes couldn't make a request with error
Error: error creating NodePool: googleapi: Error 400: EnablePrivateNodes must be enabled for private clusters with valid masterIpv4Cidr., badRequest

I find there's no variables for changing this in resource "google_container_node_pool" "pools"

### Expected behavior

a new node should be created as described below:
module.gke.google_container_node_pool.pools["default-node-pool"] will be created with such network config
resource "google_container_node_pool" "pools"

  network_config {
      enable_private_nodes = (known after apply)
      pod_ipv4_cidr_block  = (known after apply)
      pod_range            = "blablabla"
    }

### Observed behavior

Error: error creating NodePool: googleapi: Error 400: EnablePrivateNodes must be enabled for private clusters with valid masterIpv4Cidr., badRequest with module.gke.google_container_node_pool.pools["default-node-pool"], on .terraform/modules/gke/modules/beta-private-cluster/cluster.tf line 416, in resource "google_container_node_pool" "pools": 416: resource "google_container_node_pool" "pools" {

### Terraform Configuration

```hcl
We use the module beta-private-cluster just like the example in README.md.

# google_client_config and kubernetes provider must be explicitly specified like the following.
data "google_client_config" "default" {}

provider "kubernetes" {
  host                   = "https://${module.gke.endpoint}"    # Here we reference the endpoint of the cluster using the output of module gke
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(module.gke.ca_certificate)
}

module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster"
  project_id                 = "<PROJECT ID>"
  name                       = "gke-test-1"
  region                     = "us-central1"
  zones                      = ["us-central1-a", "us-central1-b", "us-central1-f"]
  network                    = "vpc-01"
  subnetwork                 = "us-central1-01"
  ip_range_pods              = "us-central1-01-gke-01-pods"
  ip_range_services          = "us-central1-01-gke-01-services"
  http_load_balancing        = false
  network_policy             = false
  horizontal_pod_autoscaling = true
  filestore_csi_driver       = false
  enable_private_endpoint    = var.enable_private_endpoint      # var.enable_private_endpoint set to true to enable the private endpoint
  enable_private_nodes       = true
  master_ipv4_cidr_block     = "10.0.0.0/28"
  istio                      = true
  cloudrun                   = true
  dns_cache                  = false
  master_authorized_networks = var.enable_private_endpoint ? [] : concat(var.master_authorized_networks, var.additional_master_authorized_networks)      # remove master_authorized_networks once we enable the private endpoint
  node_pools = [
    {
      name               = "blabla"
      machine_type       = "e2-standard-2"
      min_count          = 0
      max_count          = 100
      disk_size_gb       = 100
      disk_type          = "pd-ssd"
      image_type         = "COS_CONTAINERD"
      auto_repair        = true
      auto_upgrade       = true
      preemptible        = false
      spot               = false
      initial_node_count = 1
      max_pods_per_node  = 110
      node_locations     = "asia-southeast1-a,asia-southeast1-b"
      pod_range          = "SPECIFIED POD RANGE"
    }
]
```

### Terraform Version

```sh
$ terraform --version
Terraform v1.0.9
on linux_amd64
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by splichy**
Fixes #1493 
enable_private_nodes attribute was introduced in google provider 4.45.0 and Google API now requires `enable_private_nodes` to be set on both cluster and node_pool when pod_ip_range is specified on the node_pool level.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@splichy
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@splichy
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster/cluster.tf /tmp/tmp.r4ozMkasza/workspace/modules/beta-private-cluster/cluster.tf
477c477,478
<       pod_range = lookup(network_config.value, "pod_range", null)
---
>       pod_range            = lookup(network_config.value, "pod_range", null)
>       enable_private_nodes = var.enable_private_nodes
687c688,689
<       pod_range = lookup(network_config.value, "pod_range", null)
---
>       pod_range            = lookup(network_config.value, "pod_range", null)
>       enable_private_nodes = var.enable_private_nodes
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster-update-variant/cluster.tf /tmp/tmp.r4ozMkasza/workspace/modules/beta-private-cluster-update-variant/cluster.tf
571c571,572
<       pod_range = lookup(network_config.value, "pod_range", null)
---
>       pod_range            = lookup(network_config.value, "pod_range", null)
>       enable_private_nodes = var.enable_private_nodes
782c783,784
<       pod_range = lookup(network_config.value, "pod_range", null)
---
>       pod_range            = lookup(network_config.value, "pod_range", null)
>       enable_private_nodes = var.enable_private_nodes
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster/cluster.tf /tmp/tmp.r4ozMkasza/workspace/modules/beta-public-cluster/cluster.tf
458c458,459
<       pod_range = lookup(network_config.value, "pod_range", null)
---
>       pod_range            = lookup(network_config.value, "pod_range", null)
>       enable_private_nodes = var.enable_private_nodes
668c669,670
<       pod_range = lookup(network_config.value, "pod_range", null)
---
>       pod_range            = lookup(network_config.value, "pod_range", null)
>       enable_private_nodes = var.enable_private_nodes
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster-update-variant/cluster.tf /tmp/tmp.r4ozMkasza/workspace/modules/beta-public-cluster-update-variant/cluster.tf
552c552,553
<       pod_range = lookup(network_config.value, "pod_range", null)
---
>       pod_range            = lookup(network_config.value, "pod_range", null)
>       enable_private_nodes = var.enable_private_nodes
763c764,765
<       pod_range = lookup(network_config.value, "pod_range", null)
---
>       pod_range            = lookup(network_config.value, "pod_range", null)
>       enable_private_nodes = var.enable_private_nodes
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
@splichy
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@splichy
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@splichy
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@splichy
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@splichy
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@splichy
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@splichy
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@splichy
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by splichy** [comment]
@bharathkkb I have finally found what was wrong with the tests, so it's ready to be merged.
And maybe as an issue is caused by the change in Google API, it should be considered to backport it also into module v23 as an upgrade to v24 requires a manual step due to breaking change.

BTW is it correct that integration tests are not sending emails what part failed? I had to create a test project under my personal GCP account, hopefully, it will not cost me hundreds of $

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @splichy

**Comment by bharathkkb** [comment]
> And maybe as an issue is caused by the change in Google API, it should be considered to backport it also into module v23 as an upgrade to v24 requires a manual step due to breaking change.

We usually don't do backports unless it is a critical issue. However reading the API docs, it seems like even if this not set it should now default to the cluster config. Are you still able to reproduce the error?

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters.nodePools#nodenetworkconfig
`Whether nodes have internal IP addresses only. If enablePrivateNodes is not specified, then the value is derived from [cluster.privateClusterConfig.enablePrivateNodes]`

**Comment by splichy** [comment]
I'm still able to reproduce the error
```{
  "error": {
    "code": 400,
    "message": "EnablePrivateNodes must be enabled for private clusters with valid masterIpv4Cidr.",
    "errors": [
      {
        "message": "EnablePrivateNodes must be enabled for private clusters with valid masterIpv4Cidr.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```
It's probably a bug in Google API which is not deriving from [cluster.privateClusterConfig.enablePrivateNodes] when NodePool.NodeNetworkConfig.podRange is defined/different from cluster default.

There are also other bugs with https://cloud.google.com/kubernetes-engine/docs/how-to/multi-pod-cidr - which for example states that you can use subnet smaller than /24 for node pool override, and you can actually use e.g. /25 as cluster default, but when you try to use anything smaller than /24 for node pool override then you will get an error.

**Comment by sivadeepN** [comment]
> I'm still able to reproduce the error
> 
> ```
>   "error": {
>     "code": 400,
>     "message": "EnablePrivateNodes must be enabled for private clusters with valid masterIpv4Cidr.",
>     "errors": [
>       {
>         "message": "EnablePrivateNodes must be enabled for private clusters with valid masterIpv4Cidr.",
>         "domain": "global",
>         "reason": "badRequest"
>       }
>     ],
>     "status": "INVALID_ARGUMENT"
>   }
> }
> ```
> 
> It's probably a bug in Google API which is not deriving from [cluster.privateClusterConfig.enablePrivateNodes] when NodePool.NodeNetworkConfig.podRange is defined/different from cluster default.
> 
> There are also other bugs with https://cloud.google.com/kubernetes-engine/docs/how-to/multi-pod-cidr - which for example states that you can use subnet smaller than /24 for node pool override, and you can actually use e.g. /25 as cluster default, but when you try to use anything smaller than /24 for node pool override then you will get an error.


@splichy Im facing the exact same issue that you mentioned above. How do I fix it?

**Comment by splichy** [comment]
@sivadeepN you have to set enable_private_nodes on both: cluster & node_pool, or if you are talking about an inability to use a subnet smaller than /24 for node pool override, then this doesn't have a solution yet - I have tried to solve it with GCP support, spent a few days mailing with them, then I gave up. Anyway you can use a smaller subnet cluster-wide and then add /24 as node pool overrides.

**Comment by henryhcheung2** [comment]
@splichy thank you for your work. 

When I set `private_cluster_config.enable_private_nodes` = `true` in `google_container_cluster` & `network_config.enable_private_nodes` = `false`, I get a similar error:

```bash
Error: error creating NodePool: googleapi: Error 400: EnablePrivateNodes must be enabled for private clusters with valid masterIpv4Cidr., badRequest
```

What I am trying to achieve is a private cluster with mixed node pools (public and private node pools), but it seems it does not work. Although according to the documentation, it should: https://cloud.google.com/blog/products/containers-kubernetes/understanding-gkes-new-control-plane-connectivity#:~:text=Allow%20toggling%20and%20mixed%2Dmode%20clusters%20with%20public%20and%20private%20node%20pools

**Comment by agates4** [comment]
I'm able to get around this, and create public node pools with a different pod IP range, when I pin the google-beta version:
```terraform
terraform {
  required_version = ">=0.13"

  provider_meta "google-beta" {
    module_name = "blueprints/terraform/terraform-google-kubernetes-engine:safer-cluster-update-variant/v16.0.1"
  }

  required_providers {
    google-beta = "~> 4.44.1"
  }

}
```

**Pull request merged**
