### PR TITLE
feat: remove provider config from module to be TF 0.13 compatible

### LINKED ISSUE #673: Unable to use for_each to create multiple clusters at once: nested provider configuration for "kubernetes"
I am sorry if this issue has been discussed before but I couldn't find anything about it.

We are currently trying to create multiple clusters at once using terraform's for_each. The idea behind this was to use terraform-google-modules/project-factory to create projects for different environments (dev, stg, prd, ...) and afterwards create the same resources for each project. Unfortunately when we try call the GKE module with for_each like:

```
module "gke" {
  for_each = module.project_hierarchy.projects
  source = "terraform-google-modules/kubernetes-engine/google//modules/beta-public-cluster"
  project_id = each.value
  name = "cluster-${each.key}"
  create_service_account = true
  regional = false
  region = var.region
  zones = [var.zone]
  [...]
}
```
where `each.key` is the name of the environment and `each.value` the newly created project id. We get the error:

> Error: Module does not support for_each
> 
>   on main.tf line 36, in module "gke":
>   36:   for_each = module.project_hierarchy.projects
> 
> Module "gke" cannot be used with for_each because it contains a nested
> provider configuration for "kubernetes", at
> .terraform/modules/gke/modules/beta-public-cluster/auth.tf:29,10-22.
> 
> This module can be made compatible with for_each by changing it to receive all
> of its provider configurations from the calling module, by using the
> "providers" argument in the calling module block.

Are we doing something wrong or is for_each simply not supported (yet)?

### LINKED ISSUE #677: Migrate module to terraform 0.13
0.13 is here, with `for_each`, `depends_on` for whole modules and custom variables validation.

While `for_each` is more about code cleanup, the vars constraints should really speed-up re-using of the module as we can make API design reflected on vars constraints as well (combinations of variables, possible values etc). 
F.e. [new precise variables validation](https://www.hashicorp.com/blog/custom-variable-validation-in-terraform-0-13) would help with avoiding [such situations](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/675#issuecomment-693737731)

### PR DESCRIPTION
**Pull request by xingao267**
Fixes #677
Fixes #673

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by xingao267** [comment]
@morgante @bharathkkb could you help take a look at this PR?

**Comment by morgante** [comment]
@xingao267 Have you tested/confirmed this approach works with the Kubernetes functionality like creating [a DNS map](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/dns.tf#L45)?

Note this would have to be marked as a breaking change, so please also include/start an upgrade guide.

**Comment by xingao267** [comment]
> @xingao267 Have you tested/confirmed this approach works with the Kubernetes functionality like creating [a DNS map](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/dns.tf#L45)?
`stub_domains_*` tests and `upstream_nameservers` test cover creating the `kubernetes_config_map` resources and they seem fine. https://console.cloud.google.com/cloud-build/builds/0efe0e77-8334-4a7d-ad2f-af0c7dcc46c5;step=39?project=cloud-foundation-cicd

> 
> Note this would have to be marked as a breaking change, so please also include/start an upgrade guide.
I'll add it.

**Review by morgante — APPROVED** [review]

**Comment by bharathkkb** [comment]
also fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/673

**Comment by xingao267** [comment]
@morgante ready to be merged

**Pull request merged**
