### PR TITLE
feat: add gpu_sharing_config to node_pools 2

### LINKED ISSUE #1506: gpu nodepool with gpu_sharing_strategy & max_shared_clients_per_gpu not possible
### TL;DR

gpu nodepool with gpu_sharing_config including gpu_sharing_strategy & max_shared_clients_per_gpu currently cannot be created as these parameters cannot be passed/configured like the one from resource "google_container_node_pool"

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool

...
guest_accelerator {
      type  = "nvidia-tesla-a100"
      gpu_partition_size = "1g.5gb"
      count = 1
      gpu_sharing_config {
        gpu_sharing_strategy = "TIME_SHARING"
        max_shared_clients_per_gpu = 2
      }
}	
...
```

### Detailed design

_No response_

### Additional information

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/NodeConfig

### PR DESCRIPTION
**Pull request by luisferreira32**
Opinionated expose of gpu_sharing_config. Fixes #1506, alternative to #1599.

### CODE REVIEW

**Comment by luisferreira32** [comment]
To extend a bit on this opinionated alternative to an existing PR: the object validation should be handled by the `hashicorp/google` provider, so just extending the module arguments should suffice.

**Comment by FuyuanChu** [comment]
awesome, pretty helpful feature.

**Comment by luisferreira32** [comment]
Hi, is it possible to follow-up on what the ci is indicating to be wrong?

**Pull request closed without merging**
