### PR TITLE
feat: support gVNIC

### PR DESCRIPTION
**Pull request by anoxape**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@anoxape
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by anoxape** [comment]
@bharathkkb this is a simple autogen-based change that enables [gVNIC](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#gvnic) support on a per-nodepool pool basis.
google & google-beta provider version requirements bumped to [4.14.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.14.0) which [had it implemented](https://github.com/hashicorp/terraform-provider-google/pull/11240)

**Review by bharathkkb — CHANGES_REQUESTED** [review]
Thanks for the PR @anoxape, looks like we also need a rebase.
We should also allow this per nodepool here
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/cluster.tf#L300

**Comment by anoxape** [comment]
@bharathkkb thanks, fixed and rebased
I also added `enable_gvnic` to `force_node_pool_recreation_resources` because [it forces a replacement](https://github.com/hashicorp/terraform-provider-google/blob/v4.27.0/google/node_config.go#L136)

**Comment by comment-bot-dev** [comment]
@anoxape
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@anoxape
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
