### PR TITLE
feat!: align keepers with ForceNew: true fields 

### PR DESCRIPTION
**Pull request by lauraseidler**
Will cause node pools to be re-created on update, unless remote state
of the `random_id` resources is manually modified to reflect the new keepers.

Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1695

### CODE REVIEW

**Comment by lauraseidler** [comment]
Not stale, still an open issue

**Review by apeabody — COMMENTED** [review]
Thanks for the contribution @lauraseidler!

Could you add the referenced tf state migration to (new) `docs/upgrading_to_v29.0.md`

**Comment by lauraseidler** [comment]
> Could you add the referenced tf state migration to (new) `docs/upgrading_to_v29.0.md`

@apeabody sorry, it took me a while to find time for this again - done now :)

**Review by apeabody — COMMENTED** [review]
Thanks for the contribution @lauraseidler!

**Review by apeabody — APPROVED** [review]

**Pull request merged**
