### PR TITLE
fix: empty addons_config handling

### LINKED ISSUE #1716: Import of existing cluster fails due to addons response empty
### TL;DR

Importing an existing cluster fails due to the addons JSON response empty from gcloud CLI.

```json
{
  "addonsConfig": {
    "gcePersistentDiskCsiDriverConfig": {
      "enabled": true
    },
    "kubernetesDashboard": {
      "disabled": true
    },
    "networkPolicyConfig": {
      "disabled": true
    }
  },
...
```

### Expected behavior

I would like to see the cluster imported correctly.

### Observed behavior

```sh
╷
│ Error: Invalid index
│
│   on .terraform/modules/gke/main.tf line 114, in locals:
│  114:   cluster_output_http_load_balancing_enabled        = google_container_cluster.primary.addons_config[0].http_load_balancing[0].disabled
│     ├────────────────
│     │ google_container_cluster.primary.addons_config[0].http_load_balancing is empty list of object
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵

╷
│ Error: Invalid index
│
│   on .terraform/modules/gke/main.tf line 115, in locals:
│  115:   cluster_output_horizontal_pod_autoscaling_enabled = google_container_cluster.primary.addons_config[0].horizontal_pod_autoscaling[0].disabled
│     ├────────────────
│     │ google_container_cluster.primary.addons_config[0].horizontal_pod_autoscaling is empty list of object
│
│ The given key does not identify an element in this collection value: the collection has no elements.
```

### Terraform Configuration

```hcl
module "gke" {
  source  = "terraform-google-modules/kubernetes-engine/google"
  version = "~> 27.0"

  project_id = var.project_id
  name       = "myone"

  region     = "us-central1"
  zones      = ["us-central1-f"]
  network    = "default"
  subnetwork = "default"

  ip_range_pods     = "gke-myone-pods-09c87874"
  ip_range_services = "gke-myone-services-09c87874"

  http_load_balancing        = true
  network_policy             = false
  horizontal_pod_autoscaling = true
  filestore_csi_driver       = false

  create_service_account = false

  node_pools = [
    {
      name            = "default-pool"
      machine_type    = "e2-medium"
      node_locations  = "us-central1-f"
      autoscaling     = false
      node_count      = 3
      local_ssd_count = 0
      spot            = false
      disk_size_gb    = 100
      disk_type       = "pd-balanced"
      image_type      = "COS_CONTAINERD"
      service_account = "default"
      enable_gcfs     = false
      enable_gvnic    = false
      auto_repair     = true
      auto_upgrade    = true
      service_account = "default"
      preemptible     = false
    },
  ]

  node_pools_oauth_scopes = {
    all = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
  }

  kubernetes_version = "1.26.6-gke.1700"
}
```

### Terraform Version

```sh
Terraform v1.5.5
on linux_amd64
```

### Additional information

A similar issue (https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/494) was reported but in that occasion the user could at least import. I'm not even able to import.

### PR DESCRIPTION
**Pull request by 0Delta**
resolve #1716

Older clusters may have missing or missing values in `google_container_cluster.primary.addons_config`.
The current code assumes that the value is sufficient and cannot resolve this.

This patch will reduce dirty hacks such as pulling and modifying this repo and importing.

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @0Delta!

Please see the linter output for change.

**Comment by 0Delta** [comment]
I have fixed the points you pointed out, apologize for my bad format.

**Comment by apeabody** [comment]
From the linter:

```
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/main.tf /tmp/tmp.xMCHtY7AKG/workspace/main.tf
121,123c121,123
<   cluster_output_network_policy_enabled             = coalescelist(lookup(coalescelist(google_container_cluster.primary.addons_config, [{}])[0], "network_policy_config", [{}]), [{ disabled = false }])[0].disabled
<   cluster_output_http_load_balancing_enabled        = coalescelist(lookup(coalescelist(google_container_cluster.primary.addons_config, [{}])[0], "http_load_balancing", [{}]), [{ disabled = false }])[0].disabled
<   cluster_output_horizontal_pod_autoscaling_enabled = coalescelist(lookup(coalescelist(google_container_cluster.primary.addons_config, [{}])[0], "horizontal_pod_autoscaling", [{}]), [{ disabled = false }])[0].disabled
---
>   cluster_output_network_policy_enabled             = google_container_cluster.primary.addons_config[0].network_policy_config[0].disabled
>   cluster_output_http_load_balancing_enabled        = google_container_cluster.primary.addons_config[0].http_load_balancing[0].disabled
>   cluster_output_horizontal_pod_autoscaling_enabled = google_container_cluster.primary.addons_config[0].horizontal_pod_autoscaling[0].disabled
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
```

**Comment by 0Delta** [comment]
Linter indicates the previous code, indicating that existing problems are not solved.
Which is better to ask Linter ignoring only this section or design a code that makes Linter in a good mood?

**Comment by apeabody** [comment]
> Linter indicates the previous code, indicating that existing problems are not solved. Which is better to ask Linter ignoring only this section or design a code that makes Linter in a good mood?

Hi @0Delta - It appears the templates haven't been updated.  Please see here for details: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/CONTRIBUTING.md#templating. Thanks!

**Comment by 0Delta** [comment]
I finally found out what this repository was made up of. 
Thank you @apeabody for the detailed guide.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @0Delta!

**Pull request merged**
