### PR TITLE
Add documentation regarding requirements

### LINKED ISSUE #34: Enable easier shared VPC usage
Ran into this issue with creating a GKE cluster.

`1 error(s) occurred:
* module.prod-gke-cluster.google_container_cluster.primary: 1 error(s) occurred:
* google_container_cluster.primary: googleapi: Error 404: Not found: GAIA email lookup., notFound`

TF Debug output in attached file
[debug.log](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/files/2601389/debug.log)

```
module "dev-gke-cluster" {
  source = "github.com/terraform-google-modules/terraform-google-kubernetes-engine"
  name = "gke-dev"
  kubernetes_version = "latest"
  project_id = "${google_project.dev-project.project_id}"
  region = "${var.region}"
  network = "${google_compute_network.dev-network.name}"
  subnetwork = "${google_compute_subnetwork.dev-app-subnet.name}"
  network_project_id = "${google_compute_shared_vpc_host_project.shared_vpc.project}"
  ip_range_pods = "${google_compute_subnetwork.dev-app-subnet.secondary_ip_range.0.range_name}"
  ip_range_services = "${google_compute_subnetwork.dev-app-subnet.secondary_ip_range.1.range_name}"
  regional = true
  horizontal_pod_autoscaling = true
  network_policy = true 
  master_authorized_networks_config = [{
    cidr_blocks = [{ cidr_block = "0.0.0.0/0" display_name = "all" }]  
  }]
  node_pools = [
    {
      name = "default-node-pool"
      machine_type    = "n1-standard-2"
      min_count = 1
      max_count = 3
      disk_size_gb = 100
      disk_type = "pd-standard"
      image_type = "COS"
      auto_repair = true
      auto_upgrade = true
    },
  ]
}

### PR DESCRIPTION
**Pull request by morgante**
This should make #34 easier to avoid.

Fixes #34.

### CODE REVIEW

**Comment by davidrymkiewicz** [comment]
@morgante I added a comment to #34 that actually fixes the original issue. It would add the `google_project_service` resources and the `google_project_iam_member` resources needed.

**Comment by morgante** [comment]
@davidrymkiewicz Our philosophy is generally that IAM and API enablement should be handled outside the module, but I'm willing to reconsider.

**Comment by davidrymkiewicz** [comment]
@morgante I've always worked with modules in terraform as exclusively self-contained code. Meaning modules should be completely stand-alone components, and especially with the complexity of coding something like GKE in terraform, it would be beneficial to the lifecycle of the module and its components if all dependancies are handled internally. Speaking from using this module myself for the first time, it wasn't immediately obvious that the module wouldn't handle enabling the API or granting the service accounts the necessary permissions to the shared VPC project. Even if you don't add the functionality to the module, I'd at least recommend adding the code I put in #34 to the `/examples/shared_vpc` so others don't need to go off and search to find the particular [article](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-shared-vpc) that I did so that they can figure out which permissions to add and where.

**Comment by davidrymkiewicz** [comment]
@morgante you also need JP as a prerequisite.

**Comment by morgante** [comment]
That is documented: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine#requirements-1

**Comment by davidrymkiewicz** [comment]
@morgante Ah, I didn’t see it on commit 68dcd99

**Pull request merged**
