### PR TITLE
Exposing use_existing_context variable

### PR DESCRIPTION
**Pull request by jeffreylean**
exposing use_existing_context variable to allow kubectl wrapper to run kubectl using local kube config context

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jeffreylean
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jeffreylean
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @jeffreylean

**Pull request merged**
