### PR TITLE
feat: add advanced datapath observability config option

### LINKED ISSUE #1755: Support `advanced_datapath_observability_config`
### TL;DR

Add inputs for the block:

```HCL
advanced_datapath_observability_config {
  enable_metrics # true | false
  relay_mode # DISABLED | INTERNAL_VPC_LB | EXTERNAL_LB
}
```

### Terraform Resources

- [google_container_cluster#advanced_datapath_observability_config](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#advanced_datapath_observability_config)
- [Class AdvancedDatapathObservabilityConfig](https://cloud.google.com/python/docs/reference/container/latest/google.cloud.container_v1.types.AdvancedDatapathObservabilityConfig)

### Detailed design

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TheKangaroo**
fixes #1755 

I'm not sure about the variable names though. Any ideas for shorter names?

### CODE REVIEW

**Comment by TheKangaroo** [comment]
Hi @ericyz , WDYT about the variable names? I shortened them to
```
monitoring_enable_observability_metrics = false
monitoring_observability_metrics_relay_mode = null
```
The default for the mode variable is `INTERNAL_VPC_LB` in my private cluster, but I suspect this is different for different cluster types. I cannot verify this though. Anyway I think a default of `null` makes sense?

**Comment by TheKangaroo** [comment]
@apeabody I have rebeased again. Last time the pipeline status was red. Did the PR break something?

**Comment by apeabody** [comment]
> @apeabody I have ~rebeased~ merged master again. Last time the pipeline status was red. Did the PR break something?

Hi @TheKangaroo - For `terraform-google-kubernetes-engine-int-trigger` a maintainer needs to comment gcbrun after the latest commits, otherwise the check won't actually run in CloudBuild and will (confusingly) be marked as failed in GitHub.

I just triggered it now.

**Comment by TheKangaroo** [comment]
Thanks for the explanation @apeabody. 
Looks good now, doesn't it?

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @TheKangaroo!

**Comment by Markieta** [comment]
Trying to disable these does not seem to take effect:

```HCL
  monitoring_enable_observability_metrics = false
  monitoring_observability_metrics_relay_mode = "DISABLED"
```

Not sure if the problems lies in this module or the underlying `google_container_cluster` resource.

**Comment by TheKangaroo** [comment]
@Markieta 
Hmm, thats strange, I run all my clusters with:
```
  monitoring_enable_observability_metrics     = true
  monitoring_observability_metrics_relay_mode = "INTERNAL_VPC_LB"
```
but changed one to test this to 
```
  monitoring_enable_observability_metrics     = false
  monitoring_observability_metrics_relay_mode = "INTERNAL_VPC_LB"
```
and I think everyting works as expected.

Terraform needed like half an hour to complete, but after that, everything seems to be fine.

The only thing that was a bit suprising to me ist that the cluster state show true if enalbed and nothing if disabled:
Enabled (before terraform change):
```
> gcloud container clusters describe <name> | grep monitoringConfig -A 3
monitoringConfig:
  advancedDatapathObservabilityConfig:
    enableMetrics: true
    relayMode: INTERNAL_VPC_LB
```
Disabled (after terraform change):
```
> gcloud container clusters describe <name> | grep monitoringConfig -A 3
monitoringConfig:
  advancedDatapathObservabilityConfig:
    relayMode: INTERNAL_VPC_LB
  componentConfig: {}
```

I think it would be better if you opened a new issue describing exactly what is happening.

**Comment by Markieta** [comment]
Thanks, perhaps it's only an issue for existing cluster (modules) that were created before adding these inputs? I've created an [issue](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1892).

**Pull request merged**
