### PR TITLE
[ready] [breaking] Added monitoring_config and logging_config variables to beta clusters

### PR DESCRIPTION
**Pull request by rosmo**
- Updated the provider version too
- Also made it docker binary configurable (given all the changes with Docker Desktop etc)

Related changes: https://github.com/hashicorp/terraform-provider-google/pull/10125

### CODE REVIEW

**Comment by NeckBeardPrince** [comment]
@rosmo Can you review the conflicts?

**Comment by bharathkkb** [comment]
@rosmo we have an upcoming breaking release (https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1086), can you resolve the conflicts?

**Review by morgante — APPROVED** [review]
Test failure is unrelated.

**Comment by Nicarim** [comment]
Did anyone get this change to work? I'm getting issue of not being able to use it at all, getting errors as in this issue: https://github.com/hashicorp/terraform-provider-google/issues/10361

**Comment by rwong2888** [comment]
@rosmo , @morgante 
Can we get `monitoring_enabled_components` for the other submodules? Particularly `private-cluster`.

**Pull request merged**
