### PR TITLE
feat: Add support for Logging Variant to enable max throughput option

### PR DESCRIPTION
**Pull request by billyfoss**
added logging_variant variable for node pools configuration to the autogen files

### CODE REVIEW

**Comment by vadlvadl** [comment]
@Jberlinsky @ericyz could you review this MR?

**Comment by ericyz** [comment]
Note for myself: 
- logging_variant added in [v4.44.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.44.0)

**Comment by ericyz** [comment]
LGTM and will approve once passing the integration test

**Review by ericyz — APPROVED** [review]

**Review by ericyz — APPROVED** [review]

**Pull request merged**
