### PR TITLE
Add initial_node_count variable for scaling the default node pool

### PR DESCRIPTION
**Pull request by ctrox**
Adds a variable to be able to configure the number of nodes in the default node pool. It defaults to 0 so it should not change existing behaviour.

### CODE REVIEW

**Comment by morgante** [comment]
@ctrox Is your intention to use the default node pool? We encourage explicitly passing the node pools you wish to use (via the node_pools argument on this module) and instead deleting the default node pool.

**Comment by ctrox** [comment]
@morgante I actually want to set the initial node count to implement [this workaround](https://github.com/terraform-providers/terraform-provider-google/issues/3385#issuecomment-488149996). But if someone really wants to use the default node pool we would need to have a lot more configuration options available, so I think this one parameter does not make it likely for someone to actually use it.

**Comment by morgante** [comment]
@ctrox Got it, that use case makes sense. Could we potentially *compute* a realistic initial_node_count based on the node_pool configs provided? Maybe you could share your expected configuration?

**Comment by ctrox** [comment]
@morgante It might be a bit hard to compute it with Terraform 0.11 but essentially it would be just adding the `min_node_count` of all node pools together. With that it will launch as many nodes in the default node pool as the other pools will have afterwards. But it would also change the default behaviour of the module if for example someone did not set `delete_node_pool = true` it would suddenly launch a number of nodes.

**Comment by aaron-lane** [comment]
Hi @ctrox.

Can you please move your implementation to the equivalent files in the `autogen` directory, then run `make generate` and `make generate_docs`?

**Comment by ctrox** [comment]
@aaron-lane Totally missed that, sorry! Updated my branch accordingly.

**Pull request merged**
