### PR TITLE
feat(TPG>=6.5.0)!: support gcp_filestore_csi_driver_config for autopilot

### PR DESCRIPTION
**Pull request by DrFaust92**
https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.5.0

### CODE REVIEW

**Comment by DrFaust92** [comment]
[apeabody](https://github.com/apeabody) can you share the error?

**Comment by apeabody** [comment]
> [apeabody](https://github.com/apeabody) can you share the error?

I'm pretty sure this was a flake, re-running the tests.

**Comment by DrFaust92** [comment]
[apeabody](https://github.com/apeabody) still seems to fail 😢

**Comment by apeabody** [comment]
> [apeabody](https://github.com/apeabody) still seems to fail 😢

Doesn't appear related to your change, working on it here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/2130

**Comment by apeabody** [comment]
This will be a breaking change, updated the subject and marked as `do not merge` for now.

**Comment by apeabody** [comment]
Given the removal of TPGv5 support, going to hold this for the v35 breaking release.

**Review by apeabody — APPROVED** [review]

**Comment by apeabody** [comment]
Thanks for the contribution @DrFaust92!

**Pull request merged**
