### PR TITLE
feat: Set boot_disk_kms_key cluster wide and for cluster_autoscaling

### PR DESCRIPTION
**Pull request by CPL-markus**
Currently it seems impossible to set KMS keys (`boot_disk_kms_key`) for the cluster autoscaler, which leads to node-pools being created using _Google Managed Keys_ for all boot disks. As this is supported by the resource `google_container_cluster`, it should also be supported in the module.

Additionally similar to `service_account` the KMS key should be possible to be set cluster-wide as well.

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @CPL-markus!

Please see the lint findings:
```
Working in ./modules/beta-autopilot-private-cluster ...
1 issue(s) found:

Warning: [Fixable] variable "boot_disk_kms_key" is declared but not used (terraform_unused_declarations)

  on variables.tf line 248:
 248: variable "boot_disk_kms_key" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.7.0/docs/rules/terraform_unused_declarations.md

tflint failed ./modules/beta-autopilot-private-cluster 
Working in ./modules/beta-autopilot-public-cluster ...
1 issue(s) found:

Warning: [Fixable] variable "boot_disk_kms_key" is declared but not used (terraform_unused_declarations)

  on variables.tf line 248:
 248: variable "boot_disk_kms_key" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.7.0/docs/rules/terraform_unused_declarations.md

tflint failed ./modules/beta-autopilot-public-cluster 
```

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @CPL-markus!

Confirmed `boot_disk_kms_key` GA in TPG 5.25.0

**Comment by CPL-markus** [comment]
Thank you @apeabody for your support here!

**Pull request merged**
