### PR TITLE
feat!: add service_external_ips option

### PR DESCRIPTION
**Pull request by jpetrucciani**
This PR was created to replace #1440 

This PR adds the ability to set `service_external_ips_config` on the underlying cluster upon creation, which otherwise can (in my experience) take up to 20-30 minutes to enable independently after the cluster settles after initial creation.

I added the changes to the templates in `./autogen/` and ran `make build` in order to generate the changes across the repo

I've been testing cluster creation with these new settings already via my fork (and it appears to be working well! shaves a good amount of time off of our new cluster creation process), but would love to see it included in the official module if possible! Please let me know if there are any changes you'd like, or things I should take into account!

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@jpetrucciani
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/beta-autopilot-public-cluster/cluster.tf
--- old/modules/beta-autopilot-public-cluster/cluster.tf
+++ new/modules/beta-autopilot-public-cluster/cluster.tf
@@ -91,7 +91,7 @@
   dynamic "service_external_ips_config" {
     for_each = var.service_external_ips ? [1] : []
     content {
-        enabled = var.service_external_ips
+      enabled = var.service_external_ips
     }
   }
 
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/beta-autopilot-private-cluster/cluster.tf
--- old/modules/beta-autopilot-private-cluster/cluster.tf
+++ new/modules/beta-autopilot-private-cluster/cluster.tf
@@ -91,7 +91,7 @@
   dynamic "service_external_ips_config" {
     for_each = var.service_external_ips ? [1] : []
     content {
-        enabled = var.service_external_ips
+      enabled = var.service_external_ips
     }
   }
 
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@jpetrucciani
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jpetrucciani
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @jpetrucciani

**Pull request merged**
