### PR TITLE
fix: Add project ID to the fleet feature membership for ASM

### PR DESCRIPTION
**Pull request by legal90**
That resource was added recently in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1702

Bit I get this error when I try to apply it with my config:
```hcl
# module "gke" { ... }

module "asm" {
  source = "git@github.com:terraform-google-modules/terraform-google-kubernetes-engine.git//modules/asm?ref=3c9a634ceef3fe8fc073de161f17f0064f424c04"

  project_id                = var.project_id
  cluster_name              = module.gke.name
  cluster_location          = module.gke.location
  mesh_management           = "MANAGEMENT_AUTOMATIC"
  multicluster_mode         = "connected"
  enable_cni                = true
  enable_fleet_registration = true
  enable_mesh_feature       = true
}
```

```
$ terraform plan
 <...>
╷
│ Error: 1 error occurred:
│ 	* Failed to retrieve project, pid: , err: project: required field is not set
│
│
│
│   with module.asm.google_gke_hub_feature_membership.mesh_feature_membership[0],
│   on .terraform/modules/asm/modules/asm/hub.tf line 37, in resource "google_gke_hub_feature_membership" "mesh_feature_membership":
│   37: resource "google_gke_hub_feature_membership" "mesh_feature_membership" {
│
╵
```

I fix it in this PR just by adding `project` argument explicitly. 
After that fix it works as expected.

cc @ferrarimarco

### CODE REVIEW

**Comment by apeabody** [comment]
Thanks @legal90!  @ferrarimarco would you be able to review?

/gcbrun

**Comment by ferrarimarco** [comment]
Hi! I'll have a look!

**Review by ferrarimarco — APPROVED** [review]
@apeabody LGTM.

/cc @jbrook

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @legal90!

Thanks for the review @ferrarimarco!

**Pull request merged**
