### PR TITLE
refactor!:remove hub from asm module

### PR DESCRIPTION
**Pull request by cloud-pharaoh**
address #661

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — CHANGES_REQUESTED** [review]
Thanks for the PR @cloud-pharaoh 
We have this [example](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/examples/simple_zonal_with_asm/) which is actually an [integration test](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/182dded476ddd8eb6f95a800f7a5bb6541c9fcbe/test/integration/simple_zonal_with_asm/controls/gcloud.rb#L43). To keep those passing, I propose we invoke the hub module within that same example. 

Another alternative is to use a new test just for hub but I dont think thats necessary as we should be consolidating wherever possible.

**Review by bharathkkb — APPROVED** [review]
LGTM

**Comment by cloud-pharaoh** [comment]
w00t!

**Comment by bharathkkb** [comment]
@cloud-pharaoh one minor nit. The documentation for `asm` module still has some references to hub like `Optionally registering your cluster with GKE Hub.` We should clean those up too.

**Comment by cloud-pharaoh** [comment]
Good catch. I totally forgot there were words in there apart from the variables and outputs :) 
Done.

**Pull request merged**
