### PR TITLE
Add a service activation module

### PR DESCRIPTION
**Pull request by morgante**
This is a simple submodule which can be used to activate all required services.

### CODE REVIEW

**Comment by aaron-lane** [comment]
@morgante is this ready for review?

**Comment by morgante** [comment]
@aaron-lane Not yet.

**Comment by Jberlinsky** [comment]
@morgante Could you kindly mark this PR as `Draft`?

**Comment by morgante** [comment]
@Jberlinsky The "WIP" in the title should be sufficient? There's no way to mark PRs as drafts AFAIK.

**Comment by Jberlinsky** [comment]
Ah, yes, my mistake -- a PR can only be marked as `Draft` when creating it. Carry on :)

**Pull request merged**
