### PR TITLE
feat: Add threads_per_core setting for node config in node pools

### PR DESCRIPTION
**Pull request by alvicsam**
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1474

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @alvicsam!

From the linter: `Error: The following tests have failed: check_generate_modules` Can you run `make generate_modules`?

**Comment by alvicsam** [comment]
@apeabody thanks for the answer! I applied `make`, could you please run the CI again?

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @alvicsam!

**Pull request merged**
