### PR TITLE
feat: output ID of the Binary Authorization note, key & attestor

### PR DESCRIPTION
**Pull request by mmalecki**
With hashicorp/terraform-provider-google#7745 soon to be added, users will now be able to complete the full Binary Authorization multi-project flow via Terraform.

Let me know if you need the naming to change or anything.

### CODE REVIEW

**Comment by mmalecki** [comment]
Missed the `make build` there. Fixed now, lint should be going through now.

**Comment by mmalecki** [comment]
Added the attestor ID, which I believe is also required for a full multi-project setup.

**Comment by apeabody** [comment]
The CI INT error isn't related to this change, but will need to be resolved first:

```
Step #55 - "verify beta-cluster":         	Error:      	Not equal: 
Step #55 - "verify beta-cluster":         	            	expected: "{\n    \"advancedDatapathObservabilityConfig\": {\n      \"relayMode\": \"DISABLED\"\n    },\n    \"componentConfig\": {\n      \"enableComponents\": [\n        \"SYSTEM_COMPONENTS\"\n      ]\n    }\n  }"
Step #55 - "verify beta-cluster":         	            	actual  : "{\n    \"advancedDatapathObservabilityConfig\": {\n      \"relayMode\": \"DISABLED\"\n    },\n    \"componentConfig\": {\n      \"enableComponents\": [\n        \"SYSTEM_COMPONENTS\"\n      ]\n    },\n    \"managedPrometheusConfig\": {\n      \"enabled\": true\n    }\n  }"
Step #55 - "verify beta-cluster":         	            	
Step #55 - "verify beta-cluster":         	            	Diff:
Step #55 - "verify beta-cluster":         	            	--- Expected
Step #55 - "verify beta-cluster":         	            	+++ Actual
Step #55 - "verify beta-cluster":         	            	@@ -8,2 +8,5 @@
Step #55 - "verify beta-cluster":         	            	       ]
Step #55 - "verify beta-cluster":         	            	+    },
Step #55 - "verify beta-cluster":         	            	+    "managedPrometheusConfig": {
Step #55 - "verify beta-cluster":         	            	+      "enabled": true
Step #55 - "verify beta-cluster":         	            	     }
Step #55 - "verify beta-cluster":         	Test:       	TestBetaCluster
Step #55 - "verify beta-cluster":         	Messages:   	expected monitoringConfig to match fixture {
Step #55 - "verify beta-cluster":         	            	    "advancedDatapathObservabilityConfig": {
Step #55 - "verify beta-cluster":         	            	      "relayMode": "DISABLED"
Step #55 - "verify beta-cluster":         	            	    },
Step #55 - "verify beta-cluster":         	            	    "componentConfig": {
Step #55 - "verify beta-cluster":         	            	      "enableComponents": [
Step #55 - "verify beta-cluster":         	            	        "SYSTEM_COMPONENTS"
Step #55 - "verify beta-cluster":         	            	      ]
Step #55 - "verify beta-cluster":         	            	    }
Step #55 - "verify beta-cluster":         	            	  }
```

**Pull request closed without merging**
