### PR TITLE
chore: switch region for gpu quota

### PR DESCRIPTION
**Pull request by bharathkkb**
tests seem to be failing due to a quota issue for GPUs

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by g-awmalik** [comment]
Can this be done in a vars files specific to this fixture instead of hardcoding in the fixture itself?

**Comment by bharathkkb** [comment]
@g-awmalik We generally prefer to hardcode as much as possible rather than having var files

**Review by g-awmalik — APPROVED** [review]
LGTM

**Pull request merged**
