### PR TITLE
feat: promote `max_pods_per_node`, `max_surge`, and `max_unavailable` fields to ga

### LINKED ISSUE #1258: Support max_surge in non-beta GKE cluster variants
### TL;DR

Surge upgrades for GKE are supported [in the beta cluster variants](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/394). Would it be possible to add support for the max_surge upgrades in the non-beta cluster variants as well? 

### Terraform Resources

We just need to expose the [upgrade_settings section](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#upgrade_settings) to the private cluster variants.

### Detailed design

We just need to take [this section](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/81686e7ffb98da59c756691351db1e8ae158c218/modules/beta-private-cluster-update-variant/cluster.tf#L502-L505) and add it [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/81686e7ffb98da59c756691351db1e8ae158c218/modules/private-cluster/cluster.tf#L242).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DrFaust92**
Closes #1258

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@DrFaust92
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/acm-terraform-blog-part1/terraform
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part2/terraform
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part3/terraform
Success!
 The configuration is valid.
terraform_validate ./examples/deploy_service
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/disable_client_cert
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/node_pool
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../modules/private-cluster-update-variant/cluster.tf line 402, in resource "google_container_node_pool" "pools":
│
 
 402:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/node_pool_update_variant_beta
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_public_beta
Success!
 The configuration is valid.
terraform_validate ./examples/private_zonal_with_networking
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../modules/private-cluster/cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/regional_private_node_pool_oauth_scopes
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../modules/private-cluster/cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/safer_cluster
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster_iap_bastion
Success!
 The configuration is valid.
terraform_validate ./examples/shared_vpc
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/simple_autopilot_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_autopilot_public
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/simple_regional_beta
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../modules/private-cluster/cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/simple_regional_private_beta
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_kubeconfig
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/simple_regional_with_networking
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/simple_zonal_private
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../modules/private-cluster/cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/simple_zonal_with_acm
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/simple_zonal_with_asm
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/simple_zonal_with_hub
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/simple_zonal_with_hub_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/stub_domains_private
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../modules/private-cluster/cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/stub_domains_upstream_nameservers
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/upstream_nameservers
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/workload_identity
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./examples/workload_metadata_config
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../modules/private-cluster/cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./modules/acm
Success!
 The configuration is valid.
terraform_validate ./modules/asm
Success!
 The configuration is valid.
terraform_validate ./modules/auth
Success!
 The configuration is valid.
terraform_validate ./modules/beta-autopilot-private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-autopilot-public-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/binary-authorization
Success!
 The configuration is valid.
terraform_validate ./modules/fleet-membership
Success!
 The configuration is valid.
terraform_validate ./modules/hub-legacy
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./modules/private-cluster-update-variant
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on cluster.tf line 402, in resource "google_container_node_pool" "pools":
│
 
 402:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./modules/safer-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/services
Success!
 The configuration is valid.
terraform_validate ./modules/workload-identity
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/beta_cluster
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/deploy_service
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/disable_client_cert
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/node_pool
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool_update_variant
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../modules/private-cluster-update-variant/cluster.tf line 402, in resource "google_container_node_pool" "pools":
│
 
 402:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/private_zonal_with_networking
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../modules/private-cluster/cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/safer_cluster
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster_iap_bastion
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/sandbox_enabled
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_autopilot_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_autopilot_public
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/simple_regional_private
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../modules/private-cluster/cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/simple_regional_with_kubeconfig
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/simple_regional_with_networking
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/simple_zonal
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/simple_zonal_private
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../modules/private-cluster/cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/simple_zonal_with_asm
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/stub_domains
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/stub_domains_private
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../modules/private-cluster/cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/stub_domains_upstream_nameservers
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/upstream_nameservers
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/workload_identity
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../cluster.tf line 300, in resource "google_container_node_pool" "pools":
│
 
 300:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/fixtures/workload_metadata_config
╷
│
 
Error: 
Unsupported block type
│
 
│
 
  on ../../../modules/private-cluster/cluster.tf line 313, in resource "google_container_node_pool" "pools":
│
 
 313:   dynamic 
"network_config"
 {
│
 
│
 
Blocks of type "network_config" are not expected here.
╵
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@DrFaust92
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@DrFaust92
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@DrFaust92
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @DrFaust92

**Pull request merged**
