### PR TITLE
feat!: dynamic operator yaml

### PR DESCRIPTION
**Pull request by bharathkkb**
Creating a local file `operator_cr.yaml` in an ephemeral pipeline during create results in an error during subsequent destroy if that file is not present.

This PR aims to pass the rendered yaml via stdin.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Error: 
Argument or block definition required
  on modules/k8s-operator-crd-support/main.tf line 126:
  (source code not available)
An argument or block definition is required here.
Error: terraform fmt failed with exit code 2
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by bharathkkb** [comment]
@cloud-pharaoh Could you test with this branch?

**Comment by bharathkkb** [comment]
Breaking change as this will delete and recreate operator

**Review by morgante — APPROVED** [review]

**Comment by morgante** [comment]
@bharathkkb Please make sure to update the upgrade guide with a note about the new change.

**Pull request merged**
