### PR TITLE
Issue 501: Expose node pool "shielded_instance_config"

### PR DESCRIPTION
**Pull request by c0ffeec0der**
Expose node pool "shielded_instance_config" for module:
- beta-private-cluster
- beta-private-cluster-update-variant
- beta-public-cluster
- private-cluster
- private-cluster-update-variant

Tested for beta-private-cluster-update-variant
test-result

### CODE REVIEW

**Comment by bharathkkb** [comment]
Thanks for the PR!
The changes need to made in `autogen/main/cluster.tf.tmpl` which is then propagated to all the other modules by running `make build`. [More details here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/CONTRIBUTING.md#templating).

**Comment by c0ffeec0der** [comment]
You're welcome

I have updated the autogen/main/cluster.tf.tmpl

However, running make build run to error:

docker run --rm -it \
                -v "C:/main/repos/terraform-google-kubernetes-engine":/workspace \
                gcr.io/cloud-foundation-cicd/cft/developer-tools:0 \
                /bin/bash -c 'source /usr/local/bin/task_helper_functions.sh && generate_modules'
/workspace/test/task_helper_functions.sh: line 2: $'\r': command not found
/workspace/test/task_helper_functions.sh: line 16: $'\r': command not found
/workspace/test/task_helper_functions.sh: line 18: syntax error near unexpected token `$'{\r''
'workspace/test/task_helper_functions.sh: line 18: `function download_acm() {

I tried executing:

1. docker run --rm -it \
                -v "C:/main/repos/terraform-google-kubernetes-engine":/workspace \
                gcr.io/cloud-foundation-cicd/cft/developer-tools:0 \
                /bin/bash
2. gsutil cp gs://config-management-release/released/latest/config-management-operator.yaml /workspace/acm.yaml

results in another error:

 401 Anonymous caller does not have storage.objects.get access to config-management-release/released/latest/config-management-operator.yaml

Any advice on this?

**Comment by bharathkkb** [comment]
@c0ffeec0der that seems odd, I was able to run it fine from your branch.
I think it has something to with newlines (\n vs \r\n) in Windows (which is what I am assuming you are using)?
The script it references is here: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/build/developer-tools/build/scripts/task_helper_functions.sh

**Comment by c0ffeec0der** [comment]
Hey, you're right!

Previously i thought to solve it by executing inside the container and came that 401 error. But then, after reading your review, maybe it was just the line /r code. So I browsed around and found this thread:

https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile

dos2unix command solved the issue and the tool worked!

I commited all the changes except for file task_helper_functions.sh, because it was modified by dos2unix tool and might cause problem to other coder using linux/mac if I commited it. But there were some changes on readme.md caused by the tool which I think are not relevant to the changes I made. Please review and let me know your thoughts. Thanks

**Pull request merged**
