### PR TITLE
addresses import issues with gke module

### LINKED ISSUE #14: Importing existing kube clusters seems to be forbidden
importing clusters seems to fail with this error:
```
terraform import module.prod_cluster.google_container_cluster.primary $PROJECT/$REGION/$CLUSTER

Error: Provider "kubernetes" depends on non-var "local.cluster_endpoint". Providers for import can currently
only depend on variables or must be hardcoded. You can stop import
from loading configurations by specifying `-config=""`.
```

This is a huge problem because it breaks the `terraform import` functionality

### PR DESCRIPTION
**Pull request by anantasty**
This pull request addresses:

Fixes #14 

tested by importing a cluster from theroot of the project using 

`terraform import google_container_cluster.primary <project_id>/<region>/<cluster>`

the caller modules must configure the provider as:
```
provider "kubernetes" {
  load_config_file       = false
  host                   = "https://${module.gke.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(module.gke.ca_certificate)
}
```
Example can be found in `examples/deploy_service/main.tf `

### CODE REVIEW

**Comment by cray0000** [comment]
We've tested this PR and it seems to be fixing the existing kube cluster import. Should be safe to merge

**Comment by morgante** [comment]
@cray0000 Does it work with the kubernetes provider though?

**Comment by aaron-lane** [comment]
@cray0000 can you please respond and see this through to completion?

**Comment by cray0000** [comment]
@aaron-lane yep, thanks for reminding, I missed this somehow. @morgante I'll pick up this issue and will test with the kube provider.

**Comment by bharathkkb** [comment]
provider configs removed by #777

**Pull request closed without merging**
