### PR TITLE
feat: Add enable_l4_ilb_subsetting for autopilot clusters

### PR DESCRIPTION
**Pull request by kliu47**
setting already exists for other submodules. Adding functionality to autopilot submodule

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @kliu47!

Can we confirm this is supported in Autopilot? `GKE subsetting is disabled in Autopilot clusters.`
https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#subsetting

At the very least we should enable in at least one autopilot example so it's exercised by the CI tests: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/examples/simple_autopilot_public/main.tf#L35

**Comment by kliu47** [comment]
@apeabody , Yes, this feature is supported in autopilot clusters, however the default behavior is to have it disabled
image


I've also gone ahead and added the setting to true in the public autopilot example:
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1969/files#diff-229618ff3e7246fb9ddf90bc00eea2b8f399b4412e8d42d7783d2ecf04bece48R51

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @kliu47!

**Pull request merged**
