### PR TITLE
Fixes #180: Add tests for beta submodules/examples

### LINKED ISSUE #180: Add tests for beta submodules/examples

### LINKED ISSUE #185: Add database_encryption tests for terraform 0.12
Once the module is updated to support terraform 0.12 a test and example for `database_encryption` should be added.

### PR DESCRIPTION
**Pull request by bohdanyurov-gl**
Fixes #180
Fixes #185

Tests for beta GKE features.

### CODE REVIEW

**Comment by morgante** [comment]
@bohdanyurov-gl Looks like tests are failing. Can you check locally?

**Comment by nick4fake** [comment]
@morgante we've discussed this with @aaron-lane today. Looks like there is another permission missing from ci fixtures

**Comment by morgante** [comment]
Looks like there are still issues unrelated to permissions: https://concourse.infra.cft.tips/builds/6158

```
       Error: Invalid index
       
         on ../../../modules/beta-public-cluster/main.tf line 262, in locals:
        262:   cluster_master_auth_list_layer2 = local.cluster_master_auth_list_layer1[0]
```

**Comment by nick4fake** [comment]
@morgante @aaron-lane has told me there was an issue with permission, here is pr: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/280

Regarding the failure you've noted - it should not be related to my work. Tests pass smoothly locally

**Comment by nick4fake** [comment]
image

**Comment by kopachevsky** [comment]
@bohdanyurov-gl some strange commit in PR, probably result of incorrect rebase/merge

**Comment by nick4fake** [comment]
@kopachevsky I haven't added it. Waiting for @morgante's response

**Comment by nick4fake** [comment]
> @bohdanyurov-gl
> How do you feel about fixing [linters](https://concourse.infra.cft.tips/builds/6514) and [integration tests](https://concourse.infra.cft.tips/builds/6515)
> So it could pass the checks and be merged?
> This PR blocks integration tests for #228

Linters and integration tests are not related to my work. Please wait for other PRs to be merged:
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/238

**Comment by nick4fake** [comment]
@morgante Integration tests are failing due to outdated google-beta provider. It is going to be fixed in this PR:
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/295

**Pull request merged**
