### PR TITLE
Update version to fix the exception of node pool to terraform

### PR DESCRIPTION
**Pull request by abhisek00**
Updated version to 21.2 from 16.0 which has fixed the issue.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@abhisek00
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@abhisek00
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part1/terraform
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part2/terraform
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part3/terraform
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google-beta: no available releases match the given constraints >=
│
 
3.43.0, 3.73.0, >= 4.10.0, < 5.0.0
╵
terraform_validate ./examples/deploy_service
Success!
 The configuration is valid.
terraform_validate ./examples/disable_client_cert
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_beta
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_public_beta
Success!
 The configuration is valid.
terraform_validate ./examples/private_zonal_with_networking
Success!
 The configuration is valid.
terraform_validate ./examples/regional_private_node_pool_oauth_scopes
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster_iap_bastion
Success!
 The configuration is valid.
terraform_validate ./examples/shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/simple_autopilot_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_autopilot_public
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_beta
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private_beta
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_networking
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_acm
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_asm
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_hub
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_hub_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_private
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./examples/upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./examples/workload_identity
Success!
 The configuration is valid.
terraform_validate ./examples/workload_metadata_config
Success!
 The configuration is valid.
terraform_validate ./modules/acm
Success!
 The configuration is valid.
terraform_validate ./modules/asm
Success!
 The configuration is valid.
terraform_validate ./modules/auth
Success!
 The configuration is valid.
terraform_validate ./modules/beta-autopilot-private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-autopilot-public-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/binary-authorization
Success!
 The configuration is valid.
terraform_validate ./modules/fleet-membership
Success!
 The configuration is valid.
terraform_validate ./modules/hub-legacy
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/services
Success!
 The configuration is valid.
terraform_validate ./modules/workload-identity
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/beta_cluster
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/deploy_service
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/disable_client_cert
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool_update_variant
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/private_zonal_with_networking
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster_iap_bastion
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/sandbox_enabled
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_autopilot_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_autopilot_public
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_networking
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_with_asm
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_identity
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_metadata_config
Success!
 The configuration is valid.
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@abhisek00
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@abhisek00
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Comment by sephethus** [comment]
So what do we do to fix this? I have the latest terraform version 1.2.5 installed by brew. I am unable to get past the error when creating node pools. "Docker container runtimes is not supported in GKE v1.23"

**Comment by Temikus** [comment]
For others looking for what to do, it's most likely the node auto-provisioning that hasn't been updated, this script should help:
https://github.com/GoogleCloudPlatform/k8s-node-tools/blob/HEAD/migrating-to-containerd/find-nodepools-to-migrate.sh

**Pull request merged**
