### PR TITLE
Add support for setting node pool metadata key/value pairs.

### PR DESCRIPTION
**Pull request by czka**

### CODE REVIEW

**Comment by czka** [comment]
Should I have squashed my commits?

**Comment by morgante** [comment]
@czka Do you mind adding some testing for this new parameter? Probably on the node_pool fixture: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/test/integration/node_pool/controls

Rebasing is preferred to squashing or merging, but not strongly required.

Thanks for the contribution!

**Comment by czka** [comment]
@morgante I force-pushed a nice rebased branch for the PR.

I looked into those tests. It's new thing to learn for me and I don't have an easy way to run them myself. I could hack in something I think would be valid, but won't be able to make sure it is. At this moment it's an effort I'd rather avoid, and focus on fixing/extending the module to our needs. This PR (and probably few more in the coming months) is a part of the company I work for evaluating your module as a replacement for their home-grown TF code. Will you not accept my PRs without tests?

FWIW, an example node_config.*.metadata.shutdown-script might be:

```
#!/bin/bash -e

kubectl --kubeconfig=/var/lib/kubelet/kubeconfig drain --force=true --ignore-daemonsets=true --delete-local-data $HOSTNAME
```

**Comment by morgante** [comment]
@czka We're generally trying to make sure new features have good test coverage. I will see if someone else can add the tests for this, but if not I will merge as is.

**Comment by Jberlinsky** [comment]
@czka Thank you for your contribution! Like @morgante mentioned, we'd like to add some test coverage to this pull request. Now that we have [continuous integration](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/48) set up, running the tests should be pretty straightforward.

To move this forward, I'm going to close this pull request, and merge your changes into another branch in the mainline project. I'll add test coverage, and submit a final PR from that branch into `master`.

**Pull request merged**
