### PR TITLE
feat: Add secondary_boot_disks to node_pool configuration.

### PR DESCRIPTION
**Pull request by yorik**
PR adds secondary_boot_disks setting to cluster.tf in the node_config part.

### CODE REVIEW

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @yorik!

Can you please rebase or ideally [allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests).

**Comment by yorik** [comment]
> Thanks for the contribution @yorik!
> 
> Can you please rebase or ideally [allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests).

Sure, rebased. 

Looks like I can't "Allow edits", probably because the repo was cloned into our organization and it blocked somehow.

**Comment by apeabody** [comment]
> > Thanks for the contribution @yorik!
> > Can you please rebase or ideally [allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests).
> 
> Sure, rebased.
> 
> Looks like I can't "Allow edits", probably because the repo was cloned into our organization and it blocked somehow.

Thanks - Yeah, unfortunately that's needed for maintainers to rebase PRs.

**Pull request merged**
