### PR TITLE
feat: add validation checks when using existing KSA

### PR DESCRIPTION
**Pull request by loremaps**
See #1065

This PR adds checks for `cluster_name ` and `location` variables, when using an existing KSA.

The error message is not great:

```
╷
│ Error: Invalid function argument
│
│   on ../../../../../personal/terraform-google-kubernetes-engine/modules/workload-identity/main.tf line 33, in locals:
│   33:   validate_cluster = (var.use_existing_k8s_sa && var.cluster_name == "") ? tobool("Variable 'cluster_name' is required when using existing KSA") : true
│     ├────────────────
│     │ while calling tobool(v)
│
│ Invalid value for "v" parameter: cannot convert "Variable 'cluster_name' is required when using existing KSA" to bool; only the strings "true" or "false" are allowed.
╵
```

But I was bitten by this issue two times already. I believe that this does give some guidance. But if you feel the error is too misleading, please feel free to close this PR 😅 

This was the simplest solution I could find until hashicorp/terraform#25609 or hashicorp/terraform#31122 are addressed. Taken from [here](https://github.com/hashicorp/terraform/issues/25609#issuecomment-1057614400) 

Thank you for your time reviewing!

### CODE REVIEW

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @loremaps 
I think the `tobool` workaround is a bit confusing. Could we update the documentation instead?

**Comment by loremaps** [comment]
Hey @bharathkkb thanks for reviewing.

Indeed it is and please feel free to close this PR. 

The documentation was updated in #1143 AFAIK to help us avoid this misconfiguration. 

But if you miss the docs, please compare the error message shown in #1065 and that of the `tobool` workaround. And then you have to manually remove from state to recover (see https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1065#issuecomment-989003568)

Once again, thanks for your time and feel free to close this, np!

**Comment by bharathkkb** [comment]
Thanks @loremaps

**Pull request closed without merging**
