### PR TITLE
fix: Exposing VPA to GA module

### PR DESCRIPTION
**Pull request by ericyz**
The vertical pod scaling has been availble in the GA Terraform Provider. This change will expose the feature in the existing GA module.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@ericyz
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@ericyz
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part1/terraform
╷
│
 
Warning: 
Argument is deprecated
│
 
│
 
  with module.gke.google_container_cluster.primary,
│
 
  on .terraform/modules/gke/cluster.tf line 81, in resource "google_container_cluster" "primary":
│
 
  81:   enable_binary_authorization = 
var.enable_binary_authorization
│
 
│
 
Deprecated in favor of binary_authorization.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/acm-terraform-blog-part2/terraform
╷
│
 
Warning: 
Argument is deprecated
│
 
│
 
  with module.gke.google_container_cluster.primary,
│
 
  on .terraform/modules/gke/cluster.tf line 81, in resource "google_container_cluster" "primary":
│
 
  81:   enable_binary_authorization = 
var.enable_binary_authorization
│
 
│
 
Deprecated in favor of binary_authorization.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/acm-terraform-blog-part3/terraform
╷
│
 
Warning: 
Argument is deprecated
│
 
│
 
  with module.gke.google_container_cluster.primary,
│
 
  on .terraform/modules/gke/modules/beta-public-cluster/cluster.tf line 113, in resource "google_container_cluster" "primary":
│
 
 113:   enable_binary_authorization = 
var.enable_binary_authorization
│
 
│
 
Deprecated in favor of binary_authorization.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/deploy_service
Success!
 The configuration is valid.
terraform_validate ./examples/disable_client_cert
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../modules/beta-public-cluster/outputs.tf line 184:
│
 
 184: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../modules/beta-public-cluster/outputs.tf:121,1-42. Output names must be
│
 
unique within a module.
╵
terraform_validate ./examples/node_pool_update_variant
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_beta
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../modules/beta-private-cluster-update-variant/outputs.tf line 194:
│
 
 194: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../modules/beta-private-cluster-update-variant/outputs.tf:121,1-42.
│
 
Output names must be unique within a module.
╵
terraform_validate ./examples/node_pool_update_variant_public_beta
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../modules/beta-public-cluster-update-variant/outputs.tf line 184:
│
 
 184: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../modules/beta-public-cluster-update-variant/outputs.tf:121,1-42.
│
 
Output names must be unique within a module.
╵
terraform_validate ./examples/private_zonal_with_networking
Success!
 The configuration is valid.
terraform_validate ./examples/regional_private_node_pool_oauth_scopes
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../modules/beta-private-cluster/outputs.tf line 194:
│
 
 194: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../modules/beta-private-cluster/outputs.tf:121,1-42. Output names must
│
 
be unique within a module.
╵
terraform_validate ./examples/safer_cluster_iap_bastion
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../modules/beta-private-cluster/outputs.tf line 194:
│
 
 194: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../modules/beta-private-cluster/outputs.tf:121,1-42. Output names must
│
 
be unique within a module.
╵
terraform_validate ./examples/shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/simple_autopilot_private
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../modules/beta-autopilot-private-cluster/outputs.tf line 175:
│
 
 175: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../modules/beta-autopilot-private-cluster/outputs.tf:115,1-42. Output
│
 
names must be unique within a module.
╵
terraform_validate ./examples/simple_autopilot_public
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../modules/beta-autopilot-public-cluster/outputs.tf line 165:
│
 
 165: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../modules/beta-autopilot-public-cluster/outputs.tf:115,1-42. Output
│
 
names must be unique within a module.
╵
terraform_validate ./examples/simple_regional
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_beta
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../modules/beta-public-cluster/outputs.tf line 184:
│
 
 184: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../modules/beta-public-cluster/outputs.tf:121,1-42. Output names must be
│
 
unique within a module.
╵
terraform_validate ./examples/simple_regional_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private_beta
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../modules/beta-private-cluster/outputs.tf line 194:
│
 
 194: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../modules/beta-private-cluster/outputs.tf:121,1-42. Output names must
│
 
be unique within a module.
╵
terraform_validate ./examples/simple_regional_with_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_networking
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_acm
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_asm
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_hub
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_hub_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_private
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./examples/upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./examples/workload_identity
Success!
 The configuration is valid.
terraform_validate ./examples/workload_metadata_config
Success!
 The configuration is valid.
terraform_validate ./modules/acm
Success!
 The configuration is valid.
terraform_validate ./modules/asm
Success!
 The configuration is valid.
terraform_validate ./modules/auth
Success!
 The configuration is valid.
terraform_validate ./modules/beta-autopilot-private-cluster
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on outputs.tf line 175:
│
 
 175: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
outputs.tf:115,1-42. Output names must be unique within a module.
╵
terraform_validate ./modules/beta-autopilot-public-cluster
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on outputs.tf line 165:
│
 
 165: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
outputs.tf:115,1-42. Output names must be unique within a module.
╵
terraform_validate ./modules/beta-private-cluster
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on outputs.tf line 194:
│
 
 194: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
outputs.tf:121,1-42. Output names must be unique within a module.
╵
terraform_validate ./modules/beta-private-cluster-update-variant
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on outputs.tf line 194:
│
 
 194: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
outputs.tf:121,1-42. Output names must be unique within a module.
╵
terraform_validate ./modules/beta-public-cluster
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on outputs.tf line 184:
│
 
 184: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
outputs.tf:121,1-42. Output names must be unique within a module.
╵
terraform_validate ./modules/beta-public-cluster-update-variant
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on outputs.tf line 184:
│
 
 184: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
outputs.tf:121,1-42. Output names must be unique within a module.
╵
terraform_validate ./modules/binary-authorization
Success!
 The configuration is valid.
terraform_validate ./modules/fleet-membership
Success!
 The configuration is valid.
terraform_validate ./modules/hub-legacy
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../beta-private-cluster/outputs.tf line 194:
│
 
 194: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../beta-private-cluster/outputs.tf:121,1-42. Output names must be unique
│
 
within a module.
╵
terraform_validate ./modules/safer-cluster-update-variant
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../beta-private-cluster-update-variant/outputs.tf line 194:
│
 
 194: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../beta-private-cluster-update-variant/outputs.tf:121,1-42. Output names
│
 
must be unique within a module.
╵
terraform_validate ./modules/services
Success!
 The configuration is valid.
terraform_validate ./modules/workload-identity
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/beta_cluster
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../../modules/beta-public-cluster/outputs.tf line 184:
│
 
 184: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../../modules/beta-public-cluster/outputs.tf:121,1-42. Output names must
│
 
be unique within a module.
╵
terraform_validate ./test/fixtures/deploy_service
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/disable_client_cert
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../../modules/beta-public-cluster/outputs.tf line 184:
│
 
 184: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../../modules/beta-public-cluster/outputs.tf:121,1-42. Output names must
│
 
be unique within a module.
╵
terraform_validate ./test/fixtures/node_pool_update_variant
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/private_zonal_with_networking
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../../modules/beta-private-cluster/outputs.tf line 194:
│
 
 194: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../../modules/beta-private-cluster/outputs.tf:121,1-42. Output names
│
 
must be unique within a module.
╵
terraform_validate ./test/fixtures/safer_cluster_iap_bastion
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../../modules/beta-private-cluster/outputs.tf line 194:
│
 
 194: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../../modules/beta-private-cluster/outputs.tf:121,1-42. Output names
│
 
must be unique within a module.
╵
terraform_validate ./test/fixtures/sandbox_enabled
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../../modules/beta-public-cluster/outputs.tf line 184:
│
 
 184: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../../modules/beta-public-cluster/outputs.tf:121,1-42. Output names must
│
 
be unique within a module.
╵
terraform_validate ./test/fixtures/simple_autopilot_private
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../../modules/beta-autopilot-private-cluster/outputs.tf line 175:
│
 
 175: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../../modules/beta-autopilot-private-cluster/outputs.tf:115,1-42. Output
│
 
names must be unique within a module.
╵
terraform_validate ./test/fixtures/simple_autopilot_public
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Duplicate output definition
│
 
│
 
  on ../../../modules/beta-autopilot-public-cluster/outputs.tf line 165:
│
 
 165: 
output "vertical_pod_autoscaling_enabled"
 {
│
 
│
 
An output named "vertical_pod_autoscaling_enabled" was already defined at
│
 
../../../modules/beta-autopilot-public-cluster/outputs.tf:115,1-42. Output
│
 
names must be unique within a module.
╵
terraform_validate ./test/fixtures/simple_regional
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_networking
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_with_asm
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_identity
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_metadata_config
Success!
 The configuration is valid.
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@ericyz
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@ericyz
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by ericyz** [comment]
Please review @bharathkkb @Jberlinsky

**Comment by ericyz** [comment]
Hi @bharathkkb @Jberlinsky , could you please review at your convenience?

**Review by bharathkkb — COMMENTED** [review]
Sorry for the delay @ericyz. Just so I understand this correctly based on the PR contents, we are not adding the VPA feature but rather just exposing the output in GA modules. In the future, adding a PR description would be great so it is easier for us to correlate the intention behind the PR with the code changes.

**Comment by ericyz** [comment]
@bharathkkb - thanks for getting back. Yes, agree and I'll add the description in more details in future.

**Comment by comment-bot-dev** [comment]
@ericyz
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@ericyz
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
