### PR TITLE
Parallelize the builds

### PR DESCRIPTION
**Pull request by aaron-lane**
Running all Kitchen instances in serial is taking over 3 hours to complete which is an extreme amount of time to wait for validation of changes.

### CODE REVIEW

**Comment by aaron-lane** [comment]
Looks like the build was reduced to 33 minutes!

**Comment by morgante** [comment]
@aaron-lane Looks like tests are failing though.

**Comment by bharathkkb** [comment]
@aaron-lane is it possible to template int.cloudbuild.yaml and generate it automatically based on whats in test/ci? I thought that was the use of test/ci maybe I am missing something.

**Comment by morgante** [comment]
@bharathkkb We could probably write a script to do that, but it's not a high priority right now.

`test/ci` stores the actual test definitions and config, the Cloud Build config is just calling them.

**Pull request merged**
