### PR TITLE
fix: generate auth.tf from template

### LINKED ISSUE #1229: auth.tf in autopilot clusters isn't generated
### TL;DR

The auth.tf file in the autogenerated autopilot modules is not generated from the template.

### Expected behavior

_No response_

### Observed behavior

_No response_

### Terraform Configuration

```hcl
N/A
```

### Terraform Version

```sh
N/A
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by morgante**
Fixes #1229.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
Only in /tmp/tmp.VtLEsDvYFW/workspace: auth.tf
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by morgante** [comment]
Test failure is a flake (no HCL has changed).

**Comment by bharathkkb** [comment]
@morgante Do we use this in autopilot?

**Comment by morgante** [comment]
@bharathkkb Good call, looks like we don't. I've removed them entirely.

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
