### PR TITLE
feat!: add boot_disk_kms_key variable for node pools to GA modules

### PR DESCRIPTION
**Pull request by r1c0x**
Add support for boot_disk_kms_key for node pools that allows encrypting boot disks with customer-managed encryption keys.
https://cloud.google.com/kubernetes-engine/docs/how-to/using-cmek
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#boot_disk_kms_key

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@r1c0x
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@r1c0x
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by r1c0x** [comment]
@bharathkkb @Jberlinsky Would you mind taking a look? Thanks.

**Review by bharathkkb — CHANGES_REQUESTED** [review]
Thanks for the PR @r1c0x 
Since we are moving this out of beta we should also bump the min supported provider. Looking at the change log this looks like it [was added in 4.31.0.](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4310-aug-1-2022)

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/b9287de679592a2adcae4d98dcfee33a001f328b/versions.tf#L24

**Comment by r1c0x** [comment]
Thanks @bharathkkb for the review. The provider version is sorted.

**Comment by comment-bot-dev** [comment]
@r1c0x
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by r1c0x** [comment]
Remove stale

**Comment by comment-bot-dev** [comment]
@r1c0x
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/cluster.tf /tmp/tmp.k9VUG69GLF/workspace/cluster.tf
579a580,581
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
> 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster/cluster.tf /tmp/tmp.k9VUG69GLF/workspace/modules/beta-private-cluster/cluster.tf
778,779d777
<     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
< 
792a791,792
> 
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster-update-variant/cluster.tf /tmp/tmp.k9VUG69GLF/workspace/modules/beta-private-cluster-update-variant/cluster.tf
870,871d869
<     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
< 
884a883,884
> 
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster/cluster.tf /tmp/tmp.k9VUG69GLF/workspace/modules/beta-public-cluster/cluster.tf
759,760d758
<     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
< 
773a772,773
> 
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster-update-variant/cluster.tf /tmp/tmp.k9VUG69GLF/workspace/modules/beta-public-cluster-update-variant/cluster.tf
851,852d850
<     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
< 
865a864,865
> 
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster/cluster.tf /tmp/tmp.k9VUG69GLF/workspace/modules/private-cluster/cluster.tf
592a593,594
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
> 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster-update-variant/cluster.tf /tmp/tmp.k9VUG69GLF/workspace/modules/private-cluster-update-variant/cluster.tf
684a685,686
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
> 
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
@r1c0x
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/cluster.tf /tmp/tmp.85sRQ8VtHY/workspace/cluster.tf
579a580,581
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
> 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster/cluster.tf /tmp/tmp.85sRQ8VtHY/workspace/modules/beta-private-cluster/cluster.tf
778,779d777
<     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
< 
792a791,792
> 
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster-update-variant/cluster.tf /tmp/tmp.85sRQ8VtHY/workspace/modules/beta-private-cluster-update-variant/cluster.tf
870,871d869
<     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
< 
884a883,884
> 
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster/cluster.tf /tmp/tmp.85sRQ8VtHY/workspace/modules/beta-public-cluster/cluster.tf
759,760d758
<     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
< 
773a772,773
> 
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster-update-variant/cluster.tf /tmp/tmp.85sRQ8VtHY/workspace/modules/beta-public-cluster-update-variant/cluster.tf
851,852d850
<     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
< 
865a864,865
> 
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster/cluster.tf /tmp/tmp.85sRQ8VtHY/workspace/modules/private-cluster/cluster.tf
592a593,594
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
> 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster-update-variant/cluster.tf /tmp/tmp.85sRQ8VtHY/workspace/modules/private-cluster-update-variant/cluster.tf
684a685,686
>     boot_disk_kms_key = lookup(each.value, "boot_disk_kms_key", "")
> 
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
@r1c0x
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@r1c0x
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
