### PR TITLE
chore: sync repo acm location update

### PR DESCRIPTION
**Pull request by themanifold**
As advised by the notice at the top of https://github.com/GoogleCloudPlatform/csp-config-management

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@themanifold
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by themanifold** [comment]
One of the checks failed, but I don't have visibility on why.

**Comment by comment-bot-dev** [comment]
@themanifold
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @themanifold !

**Pull request merged**
