### PR TITLE
Ravindrafix/added snat

### PR DESCRIPTION
**Pull request by ravindrasinghh**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@ravindrasinghh
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster/README.md /tmp/tmp.iKW3AH5SzK/workspace/modules/private-cluster/README.md
154d153
< | disable\_legacy\_metadata\_endpoints | Disable the /0.1/ and /v1beta1/ metadata server endpoints on the node. Changing this value will cause all node pools to be recreated. | `bool` | `true` | no |
155a155
> | disable\_legacy\_metadata\_endpoints | Disable the /0.1/ and /v1beta1/ metadata server endpoints on the node. Changing this value will cause all node pools to be recreated. | `bool` | `true` | no |
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/private-cluster/README.md /tmp/tmp.WjSnidOuXr/generate_docs/workspace/modules/private-cluster/README.md
154d153
< | disable\_legacy\_metadata\_endpoints | Disable the /0.1/ and /v1beta1/ metadata server endpoints on the node. Changing this value will cause all node pools to be recreated. | `bool` | `true` | no |
155a155
> | disable\_legacy\_metadata\_endpoints | Disable the /0.1/ and /v1beta1/ metadata server endpoints on the node. Changing this value will cause all node pools to be recreated. | `bool` | `true` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./modules/private-cluster/cluster.tf:52:  
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/private-cluster/cluster.tf
--- old/modules/private-cluster/cluster.tf
+++ new/modules/private-cluster/cluster.tf
@@ -49,7 +49,7 @@
   }
 
   subnetwork = "projects/${local.network_project_id}/regions/${local.region}/subnetworks/${var.subnetwork}"
-  
+
   default_snat_status {
     disabled = var.disable_default_snat
   }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@ravindrasinghh
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster/README.md /tmp/tmp.ZBvrBdsOsF/workspace/modules/private-cluster/README.md
154d153
< | disable\_legacy\_metadata\_endpoints | Disable the /0.1/ and /v1beta1/ metadata server endpoints on the node. Changing this value will cause all node pools to be recreated. | `bool` | `true` | no |
155a155
> | disable\_legacy\_metadata\_endpoints | Disable the /0.1/ and /v1beta1/ metadata server endpoints on the node. Changing this value will cause all node pools to be recreated. | `bool` | `true` | no |
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/private-cluster/README.md /tmp/tmp.401KGNexOQ/generate_docs/workspace/modules/private-cluster/README.md
154d153
< | disable\_legacy\_metadata\_endpoints | Disable the /0.1/ and /v1beta1/ metadata server endpoints on the node. Changing this value will cause all node pools to be recreated. | `bool` | `true` | no |
155a155
> | disable\_legacy\_metadata\_endpoints | Disable the /0.1/ and /v1beta1/ metadata server endpoints on the node. Changing this value will cause all node pools to be recreated. | `bool` | `true` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@ravindrasinghh
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — CHANGES_REQUESTED** [review]
Thanks for the PR! This change will need to be made in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/dc1de85697d4ee6c7b8f5fd24447fed13ee2eb82/autogen/main/cluster.tf.tmpl#L67-L70 removing the conditional for beta.

**Comment by ravindrasinghh** [comment]
HI @bharathkkb ,
Thanks for reply, Code has been updated as per the suggested.

**Comment by comment-bot-dev** [comment]
@ravindrasinghh
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@ravindrasinghh
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — CHANGES_REQUESTED** [review]
@ravindrasinghh Can you also run `make build` to regenerate.

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/bfb5954552bddccdea8054d90f26ed0de9440545/autogen/main/variables.tf.tmpl#L478-L482
should also be moved out of the conditional

**Comment by comment-bot-dev** [comment]
@ravindrasinghh
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@ravindrasinghh
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by ravindrasinghh** [comment]
@bharathkkb 
Re ran the make build command, as per the instruction.

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
