### PR TITLE
fix: Do not ignore "mesh_id" label on "google_container_cluster" resource

### PR DESCRIPTION
**Pull request by legal90**
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1671
Relates to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1061

According to the documentation, `mesh_id` label is supposed to be set explicitly on the GKE cluster:
- [asm module doc] https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/d82c50c9cd059fd581f7ab5fe943dfada3cce0c3/modules/asm/README.md#L36-L43
- [Google doc for managed ASM] https://cloud.google.com/service-mesh/docs/managed/provision-managed-anthos-service-mesh#configure_your_fleet
- [Google doc for in-cluster ASM] https://cloud.google.com/service-mesh/docs/unified-install/project-cluster-setup#set_up_your_cluster

However, right now this label is ignored by terraform, so it's not possible to set it using IaC. 
This PR fixes that issue and removes `mesh_id` label from the `ignore_changes` list

### CODE REVIEW

**Review by ferrarimarco — APPROVED** [review]

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @legal90!

Thanks for the review @ferrarimarco!

**Pull request merged**
