### PR TITLE
Promote previously beta features to GA modules

### PR DESCRIPTION
**Pull request by marko7460**
This PR fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/644

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate . 
Success!
 The configuration is valid.
terraform_validate ./examples/deploy_service 
Success!
 The configuration is valid.
terraform_validate ./examples/disable_client_cert 
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool 
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant 
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_beta 
Success!
 The configuration is valid.
terraform_validate ./examples/private_zonal_with_networking 
Success!
 The configuration is valid.
terraform_validate ./examples/regional_private_node_pool_oauth_scopes 
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster 
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster_iap_bastion 
Success!
 The configuration is valid.
terraform_validate ./examples/shared_vpc 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_beta 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private_beta 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_kubeconfig 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_networking 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_private 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_acm 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_asm 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_hub 
Error: 
Unsupported block type
  on ../../cluster.tf line 44, in resource "google_container_cluster" "primary":
  44:   dynamic 
"release_channel"
 {
Blocks of type "release_channel" are not expected here.
Error: 
Unsupported argument
  on ../../cluster.tf line 62, in resource "google_container_cluster" "primary":
  62:   
enable_shielded_nodes
 = var.enable_shielded_nodes
An argument named "enable_shielded_nodes" is not expected here.
Error: 
Unsupported block type
  on ../../cluster.tf line 148, in resource "google_container_cluster" "primary":
 148:   dynamic 
"database_encryption"
 {
Blocks of type "database_encryption" are not expected here.
Error: 
Unsupported block type
  on ../../cluster.tf line 157, in resource "google_container_cluster" "primary":
 157:   dynamic 
"workload_identity_config"
 {
Blocks of type "workload_identity_config" are not expected here.
terraform_validate ./examples/stub_domains 
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_private 
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_upstream_nameservers 
Success!
 The configuration is valid.
terraform_validate ./examples/upstream_nameservers 
Success!
 The configuration is valid.
terraform_validate ./examples/workload_identity 
Success!
 The configuration is valid.
terraform_validate ./examples/workload_metadata_config 
Success!
 The configuration is valid.
terraform_validate ./modules/acm 
Success!
 The configuration is valid.
terraform_validate ./modules/asm 
Success!
 The configuration is valid.
terraform_validate ./modules/auth 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/binary-authorization 
Success!
 The configuration is valid.
terraform_validate ./modules/config-sync 
Success!
 The configuration is valid.
terraform_validate ./modules/hub 
Success!
 The configuration is valid.
terraform_validate ./modules/k8s-operator-crd-support 
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/services 
Success!
 The configuration is valid.
terraform_validate ./modules/workload-identity 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/beta_cluster 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/deploy_service 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/disable_client_cert 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool_update_variant 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/private_zonal_with_networking 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster_iap_bastion 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/sandbox_enabled 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_private 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_kubeconfig 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_networking 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_private 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_with_asm 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_private 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_upstream_nameservers 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/upstream_nameservers 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_identity 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_metadata_config 
Success!
 The configuration is valid.
terraform_validate ./test/setup 
Success!
 The configuration is valid.
 ```

**Review by bharathkkb — COMMENTED** [review]
Thanks @marko7460!!
Can we change the source for some of these beta feature tests like [Workload Identity](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/68e8eecaec2d31d19924dec6b4dabc56e2010f0e/examples/workload_identity/main.tf#L35) so that they point at the GA modules. This way we can have good test coverage on some of these features in GA modules.

**Comment by marko7460** [comment]
Yes! I will do that.

**Comment by bharathkkb** [comment]
@marko7460 you may need to rebase for the service identity fix

**Comment by marko7460** [comment]
@bharathkkb I'm abandoning this PR . I'm switching this work to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/709

**Pull request closed without merging**
