### PR TITLE
feat: cloud dns support for safer clusters

### PR DESCRIPTION
**Pull request by feliperfmarques**
Enable Cloud DNS support for safer clusters

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@feliperfmarques
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster/README.md /tmp/tmp.awUxeAIk6d/workspace/modules/safer-cluster/README.md
216,218d215
< | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
< | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
< | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster/main.tf /tmp/tmp.awUxeAIk6d/workspace/modules/safer-cluster/main.tf
140,145d139
<   cluster_dns_provider = var.cluster_dns_provider
< 
<   cluster_dns_scope = var.cluster_dns_scope
< 
<   cluster_dns_domain = var.cluster_dns_domain
< 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster/variables.tf /tmp/tmp.awUxeAIk6d/workspace/modules/safer-cluster/variables.tf
276,293d275
< variable "cluster_dns_provider" {
<   type        = string
<   description = "Which in-cluster DNS provider should be used. PROVIDER_UNSPECIFIED (default) or PLATFORM_DEFAULT or CLOUD_DNS."
<   default     = "PROVIDER_UNSPECIFIED"
< }
< 
< variable "cluster_dns_scope" {
<   type        = string
<   description = "The scope of access to cluster DNS records. DNS_SCOPE_UNSPECIFIED (default) or CLUSTER_SCOPE or VPC_SCOPE. "
<   default     = "DNS_SCOPE_UNSPECIFIED"
< }
< 
< variable "cluster_dns_domain" {
<   type        = string
<   description = "The suffix used for all cluster service records."
<   default     = ""
< }
< 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster-update-variant/README.md /tmp/tmp.awUxeAIk6d/workspace/modules/safer-cluster-update-variant/README.md
216,218d215
< | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
< | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
< | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster-update-variant/main.tf /tmp/tmp.awUxeAIk6d/workspace/modules/safer-cluster-update-variant/main.tf
140,145d139
<   cluster_dns_provider = var.cluster_dns_provider
< 
<   cluster_dns_scope = var.cluster_dns_scope
< 
<   cluster_dns_domain = var.cluster_dns_domain
< 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster-update-variant/variables.tf /tmp/tmp.awUxeAIk6d/workspace/modules/safer-cluster-update-variant/variables.tf
276,293d275
< variable "cluster_dns_provider" {
<   type        = string
<   description = "Which in-cluster DNS provider should be used. PROVIDER_UNSPECIFIED (default) or PLATFORM_DEFAULT or CLOUD_DNS."
<   default     = "PROVIDER_UNSPECIFIED"
< }
< 
< variable "cluster_dns_scope" {
<   type        = string
<   description = "The scope of access to cluster DNS records. DNS_SCOPE_UNSPECIFIED (default) or CLUSTER_SCOPE or VPC_SCOPE. "
<   default     = "DNS_SCOPE_UNSPECIFIED"
< }
< 
< variable "cluster_dns_domain" {
<   type        = string
<   description = "The suffix used for all cluster service records."
<   default     = ""
< }
< 
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/safer-cluster/README.md /tmp/tmp.2fstHyqbop/generate_docs/workspace/modules/safer-cluster/README.md
206a207,209
> | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
> | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
> | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
216,218d218
< | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
< | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
< | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/safer-cluster-update-variant/README.md /tmp/tmp.2fstHyqbop/generate_docs/workspace/modules/safer-cluster-update-variant/README.md
206a207,209
> | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
> | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
> | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
216,218d218
< | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
< | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
< | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@feliperfmarques
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster/README.md /tmp/tmp.6JQsExthnL/workspace/modules/safer-cluster/README.md
216,218d215
< | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
< | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
< | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster/main.tf /tmp/tmp.6JQsExthnL/workspace/modules/safer-cluster/main.tf
140,145d139
<   cluster_dns_provider = var.cluster_dns_provider
< 
<   cluster_dns_scope = var.cluster_dns_scope
< 
<   cluster_dns_domain = var.cluster_dns_domain
< 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster/variables.tf /tmp/tmp.6JQsExthnL/workspace/modules/safer-cluster/variables.tf
276,293d275
< variable "cluster_dns_provider" {
<   type        = string
<   description = "Which in-cluster DNS provider should be used. PROVIDER_UNSPECIFIED (default) or PLATFORM_DEFAULT or CLOUD_DNS."
<   default     = "PROVIDER_UNSPECIFIED"
< }
< 
< variable "cluster_dns_scope" {
<   type        = string
<   description = "The scope of access to cluster DNS records. DNS_SCOPE_UNSPECIFIED (default) or CLUSTER_SCOPE or VPC_SCOPE. "
<   default     = "DNS_SCOPE_UNSPECIFIED"
< }
< 
< variable "cluster_dns_domain" {
<   type        = string
<   description = "The suffix used for all cluster service records."
<   default     = ""
< }
< 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster-update-variant/README.md /tmp/tmp.6JQsExthnL/workspace/modules/safer-cluster-update-variant/README.md
216,218d215
< | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
< | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
< | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster-update-variant/main.tf /tmp/tmp.6JQsExthnL/workspace/modules/safer-cluster-update-variant/main.tf
140,145d139
<   cluster_dns_provider = var.cluster_dns_provider
< 
<   cluster_dns_scope = var.cluster_dns_scope
< 
<   cluster_dns_domain = var.cluster_dns_domain
< 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/safer-cluster-update-variant/variables.tf /tmp/tmp.6JQsExthnL/workspace/modules/safer-cluster-update-variant/variables.tf
276,293d275
< variable "cluster_dns_provider" {
<   type        = string
<   description = "Which in-cluster DNS provider should be used. PROVIDER_UNSPECIFIED (default) or PLATFORM_DEFAULT or CLOUD_DNS."
<   default     = "PROVIDER_UNSPECIFIED"
< }
< 
< variable "cluster_dns_scope" {
<   type        = string
<   description = "The scope of access to cluster DNS records. DNS_SCOPE_UNSPECIFIED (default) or CLUSTER_SCOPE or VPC_SCOPE. "
<   default     = "DNS_SCOPE_UNSPECIFIED"
< }
< 
< variable "cluster_dns_domain" {
<   type        = string
<   description = "The suffix used for all cluster service records."
<   default     = ""
< }
< 
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/safer-cluster/README.md /tmp/tmp.la8zwNzbGg/generate_docs/workspace/modules/safer-cluster/README.md
206a207,209
> | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
> | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
> | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
216,218d218
< | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
< | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
< | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/safer-cluster-update-variant/README.md /tmp/tmp.la8zwNzbGg/generate_docs/workspace/modules/safer-cluster-update-variant/README.md
206a207,209
> | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
> | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
> | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
216,218d218
< | cluster\_dns\_domain | The suffix used for all cluster service records. | `string` | `""` | no |
< | cluster\_dns\_provider | Which in-cluster DNS provider should be used. PROVIDER\_UNSPECIFIED (default) or PLATFORM\_DEFAULT or CLOUD\_DNS. | `string` | `"PROVIDER_UNSPECIFIED"` | no |
< | cluster\_dns\_scope | The scope of access to cluster DNS records. DNS\_SCOPE\_UNSPECIFIED (default) or CLUSTER\_SCOPE or VPC\_SCOPE. | `string` | `"DNS_SCOPE_UNSPECIFIED"` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@feliperfmarques
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@feliperfmarques
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@feliperfmarques
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@feliperfmarques
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by feliperfmarques** [comment]
@bharathkkb could you take a look on this PR, please?

**Pull request merged**
