### PR TITLE
fix: auth module avoid TPG v4.49.0

### LINKED ISSUE #1533: Auth module crash with 4.49 google provider
### TL;DR

When use_private_endpoint is set to true, auth module will fail to plan.

### Expected behavior

use_private_endpoint to work.

### Observed behavior

On a terraform plan:

```
module.target_repo.module.kubernetes-engine_auth.data.google_client_config.provider: Refreshing state...
module.target_repo.module.kubernetes-engine_auth.data.google_container_cluster.gke_cluster: Refreshing state...

Error: Invalid address to set: []string{"addons_config", "0", "config_connector_config"}

  on .terraform/modules/target_repo.kubernetes-engine_auth/modules/auth/main.tf line 26, in data "google_container_cluster" "gke_cluster":
  26: data "google_container_cluster" "gke_cluster" {
```

### Terraform Configuration

```hcl
module "kubernetes-engine_auth" {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/auth"
  version = "24.1.0"

  cluster_name         = var.cluster_name
  location             = var.regionality
  project_id           = local.project_id
  use_private_endpoint = true
}
```

### Terraform Version
https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.49.0

### Additional information

Looks like the GA provider just released a new datasource.

### PR DESCRIPTION
**Pull request by apeabody**
Fixes #1533

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/versions.tf /tmp/tmp.vPB0DG2DHI/workspace/versions.tf
24,25c24
<       # Avoid v4.49.0 for https://github.com/hashicorp/terraform-provider-google/issues/13507
<       version = ">= 4.47.0, != 4.49.0, < 5.0"
---
>       version = ">= 4.47.0, < 5.0"
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
versions.tf
--- old/versions.tf
+++ new/versions.tf
@@ -20,7 +20,7 @@
 
   required_providers {
     google = {
-      source  = "hashicorp/google"
+      source = "hashicorp/google"
       # Avoid v4.49.0 for https://github.com/hashicorp/terraform-provider-google/issues/13507
       version = ">= 4.47.0, != 4.49.0, < 5.0"
     }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/auth/versions.tf
--- old/modules/auth/versions.tf
+++ new/modules/auth/versions.tf
@@ -19,7 +19,7 @@
   required_version = ">= 0.13.0"
   required_providers {
     google = {
-      source  = "hashicorp/google"
+      source = "hashicorp/google"
       # Avoid v4.49.0 for https://github.com/hashicorp/terraform-provider-google/issues/13507
       version = ">= 4.47.0, != 4.49.0, < 5.0"
     }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Review by bharathkkb — APPROVED** [review]
Thanks @apeabody Looks like we need to pin for this example too https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/912da8c97082d08f4fef96e82bbdf6a76dad006b/test/fixtures/safer_cluster_iap_bastion/example.tf#L33

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
