### PR TITLE
fix: use provided k8s version even when a release channel is specified

### PR DESCRIPTION
**Pull request by jamiezieziula**
Related to #1279 & #1356 - this aims to allow users to define **both** a release channel to use as well as a defined version of kubernetes.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@jamiezieziula
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster/cluster.tf /tmp/tmp.fQKkyxSwXp/workspace/modules/beta-private-cluster/cluster.tf
63c63
<   min_master_version = local.master_version
---
>   min_master_version = var.release_channel == null || var.release_channel == "UNSPECIFIED" ? local.master_version : null
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster-update-variant/cluster.tf /tmp/tmp.fQKkyxSwXp/workspace/modules/beta-private-cluster-update-variant/cluster.tf
63c63
<   min_master_version = local.master_version
---
>   min_master_version = var.release_channel == null || var.release_channel == "UNSPECIFIED" ? local.master_version : null
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
@jamiezieziula
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @jamiezieziula Can we append to an existing test to make sure this is WAI. https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/2316e7775ae0322ff72650caca66d6d34a92ec02/examples/simple_regional_beta/main.tf#L53 seenms like a good candidate. https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/ab9c3c57e177b1bd668dd849579a0862dc4bcd2c/test/integration/safer_cluster/controls/gcloud.rb#L39-L43 is an example where we test the expected explicit version.

**Comment by jamiezieziula** [comment]
@bharathkkb done!

**Comment by comment-bot-dev** [comment]
@jamiezieziula
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jamiezieziula
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by bharathkkb** [comment]
Hi @jamiezieziula I am seeing an error where builds are failing with 
```
  module.this.module.gke.google_container_cluster.primary: Still creating... [5m30s elapsed]
       ╷
       │ Error: Error waiting for creating GKE cluster: Failed to create cluster
```
Did setting both `min_master_version` and `release_channel` work in your environment? I did some investigation and it seemed like there was a previous issue https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/383 which we then added this conditional as a fix.

**Comment by comment-bot-dev** [comment]
@jamiezieziula
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by kespineira** [comment]
Hello! Was there any reason that this PR was not continued with?

**Comment by emonisme** [comment]
any update on this PR?

**Pull request closed without merging**
