### PR TITLE
feat(cluster.tf): add support for setting cgroup mode

### LINKED ISSUE #1838: support cgroup mode
### TL;DR

Hi, would it be possible to have [cgroup mode](https://github.com/hashicorp/terraform-provider-google/pull/16103) supported in the next version of this module?

### Terraform Resources

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#cgroup_mode
https://github.com/hashicorp/terraform-provider-google/blob/HEAD/CHANGELOG.md#510-Oct-9-2023

### Additional information

I know this mode was introduced in v5.1 of the provider while the current version of the module (v29) is based on v5.0 on the provider.

Not sure how the development of this module is working, will it be embedded "automatically" in the next version (v30) since it will be based at least on v5.1 of the provider? Or each new feature need to be selected to be in the future version of this module?

### PR DESCRIPTION
**Pull request by chicocvenancio**
Fix #1838

### CODE REVIEW

**Comment by chicocvenancio** [comment]
I do think it would be better to expose `linux_node_config` directly instead of splitting it into `node_pools_linux_node_configs_sysctls` and `node_pools_cgroup_mode` but did not want to make that big of a change without prior discussion.

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @chicocvenancio and I agree exposing `linux_node_config` would be ideal. I think this looks good given current API.

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @chicocvenancio!

From the CI tests:

```
Step #67 - "converge node-pool-local": STDERR: Error: expected node_config.0.linux_node_config.0.cgroup_mode to be one of ["CGROUP_MODE_UNSPECIFIED" "CGROUP_MODE_V1" "CGROUP_MODE_V2"], got 
Step #67 - "converge node-pool-local": 
Step #67 - "converge node-pool-local":   with module.example.module.gke.google_container_node_pool.pools["pool-01"],
Step #67 - "converge node-pool-local":   on ../../../modules/beta-public-cluster/cluster.tf line 565, in resource "google_container_node_pool" "pools":
Step #67 - "converge node-pool-local":  565:   node_config {
Step #67 - "converge node-pool-local": 
Step #67 - "converge node-pool-local": 
Step #67 - "converge node-pool-local": Error: expected node_config.0.linux_node_config.0.cgroup_mode to be one of ["CGROUP_MODE_UNSPECIFIED" "CGROUP_MODE_V1" "CGROUP_MODE_V2"], got 
Step #67 - "converge node-pool-local": 
Step #67 - "converge node-pool-local":   with module.example.module.gke.google_container_node_pool.pools["pool-02"],
Step #67 - "converge node-pool-local":   on ../../../modules/beta-public-cluster/cluster.tf line 565, in resource "google_container_node_pool" "pools":
Step #67 - "converge node-pool-local":  565:   node_config {
Step #67 - "converge node-pool-local": 
Step #67 - "converge node-pool-local": 
Step #67 - "converge node-pool-local": Error: expected node_config.0.linux_node_config.0.cgroup_mode to be one of ["CGROUP_MODE_UNSPECIFIED" "CGROUP_MODE_V1" "CGROUP_MODE_V2"], got 
Step #67 - "converge node-pool-local": 
Step #67 - "converge node-pool-local":   with module.example.module.gke.google_container_node_pool.pools["pool-03"],
Step #67 - "converge node-pool-local":   on ../../../modules/beta-public-cluster/cluster.tf line 565, in resource "google_container_node_pool" "pools":
Step #67 - "converge node-pool-local":  565:   node_config {
```

Can you also please rebase the PR, and we can do a fresh run of the CI tests.

**Pull request closed without merging**
