### PR TITLE
feat: support confidential nodepools

### PR DESCRIPTION
**Pull request by abhikaddy**
This fixes open issue #1386.

### CODE REVIEW

**Comment by abhikaddy** [comment]
@apeabody  Good Day! can I get a review?

**Comment by apeabody** [comment]
> @apeabody Good Day! can I get a review?

Triggered the Integration tests

**Comment by abhikaddy** [comment]
@apeabody  can I get access to build failure logs?

**Comment by abhikaddy** [comment]
Hi Good Day!
Can I get a merge? @apeabody @Jberlinsky @ericyz

**Comment by t-indumathy** [comment]
Can you also backport this change to v30.x pls, as this is a gap that ought to have been addressed from that version?

**Comment by apeabody** [comment]
Thanks for the contribution @abhikaddy!

Can you please rebase your change?  Thanks!

**Comment by t-indumathy** [comment]
@abhikaddy Can you please rebase ?

**Comment by t-indumathy** [comment]
@apeabody Can you please backport this to v30.0.

**Pull request closed without merging**
