### PR TITLE
Add node_locations for node pools

### LINKED ISSUE #290: Allow setting node locations on individual node pools
As added [upstream](https://github.com/GoogleCloudPlatform/magic-modules/pull/2320), we need to update this module to support specifying `node_locations` on individual node pools (that potentially differ from the cluster's overall locations).

This will unblock #263.

### PR DESCRIPTION
**Pull request by bharathkkb**
fixes #290 

Add support for node_locations to set locations for individual node pools.

### CODE REVIEW

**Comment by DanielWozniak** [comment]
Don't mean to rush, but was wondering what is the status on this? When could we expect this to be merged?

**Comment by morgante** [comment]
@DanielWozniak I think we're waiting for tests to pass. @bharathkkb Could you take a look?

**Comment by bharathkkb** [comment]
@morgante I'll try re running the tests. It was failing destroy stage of a different example.

**Comment by DanielWozniak** [comment]
Looks like the checks are passing, could one of the approvers please take a look?

**Comment by DanielWozniak** [comment]
Thanks guys, appreciate you putting this in.

**Pull request merged**
