### PR TITLE
feat!: support for gateway api for safer cluster variants

### PR DESCRIPTION
**Pull request by lauraseidler**
Follow up to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1510

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@lauraseidler
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by ericyz** [comment]
Re-run the checks

**Comment by lauraseidler** [comment]
> Re-run the checks

Can't, unfortunately, I don't think I have the necessary permissions

**Comment by ericyz** [comment]
> > Re-run the checks
> 
> Can't, unfortunately, I don't think I have the necessary permissions

I have re-triggered it for you.

**Comment by lauraseidler** [comment]
Still no luck it seems :(

**Comment by apeabody** [comment]
Thanks for the contribution @lauraseidler! - I suspect the test failure is related to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1525

**Comment by lauraseidler** [comment]
Could be - it's really hard to figure out without having access to the builds. I guess I'll wait for the fix, then rebase and see if it works then.

**Comment by comment-bot-dev** [comment]
@lauraseidler
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by tuunit** [comment]
@lauraseidler sorry that I missed to add this feature to the safer cluster as well in the initial PR

**Comment by lauraseidler** [comment]
@apeabody Thanks for the fix!
@tuunit no worries, I think most people do

**Comment by ericyz** [comment]
Thanks @lauraseidler for the contribution. LGTM overall. Just a minor comment here. Could you please also update the modules/safer-cluster/variables.tf to pin the Google provider version >= 4.47.0 [https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.47.0]

**Comment by lauraseidler** [comment]
@ericyz the google provider version is currently not in there at all - do you want me to add it? I think since the safer cluster variants just use the beta private cluster module with some variables set to defaults, it's not necessary. However, I see that the `versions.tf` files in modules that _do_ specify them haven't been updated - maybe those need to be updated instead (and probably the autogen should handle this)?

**Comment by lauraseidler** [comment]
Yeah I actually think this would break if released as is, as the gateway API support is implemented for the beta clusters, but the provider constraint is not there - I pushed the increase, so probably it's a good idea to merge this before #1512.

**Comment by comment-bot-dev** [comment]
@lauraseidler
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by ericyz** [comment]
> Yeah I actually think this would break if released as is, as the gateway API support is implemented for the beta clusters, but the provider constraint is not there - I pushed the increase, so probably it's a good idea to merge this before #1512.

Thanks @lauraseidler . Yes, it implicitly uses other modules. That's all good

**Comment by ericyz** [comment]
LGTM and will approve once the CI passed

**Comment by comment-bot-dev** [comment]
@lauraseidler
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by ericyz — APPROVED** [review]

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @lauraseidler!

**Pull request merged**
