### PR TITLE
Fix: Change default value of network_policy variable to false

### LINKED ISSUE #804: Disable network_policy by default again
First of all: thanks to everyone who is working actively on this repo to improve and maintain it! Keep up the great work!

I'm suggesting to **disable the network_policy option by default again**, reverting PR #356 (linked to issue #138). 

I understand that the CIS GCP Benchmark recommends this policy to be enabled, but this option causes an overhead that can't be neglected in my opinion. As [documented by Google](https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy#overhead_limitations_and_caveats), this option increases the memory footprint by approximately 128 MB and requires approximately 300 millicores of CPU. Because of this, it is no longer possible to run all `kube-system` pods on a single `e2-small` or `e2-medium` instance. Instead, you need at least 2 `e2-medium` instances, and [Google's documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy#overhead_limitations_and_caveats) even recommends 3 `e2-medium` instances.

This overhead could be acceptable if it would improve the security out-of-the-box, but this option does not contribute anything to the security of your system as long as it's not configured. I'm sure that a lot of users don't know that this option is enabled by default, which means they will probably not configure the `network_policy`, resulting in 300 mCPU and 128 MB of wasted resources (and as previously explained, probably also a wasted VM instance). 

I would finally also like to add that the `network_policy` option is not enabled by default when a Kubernetes cluster is created through Google Cloud Platform console.

Given all these arguments, I feel like the cons outweigh the pros of enabling the `network_policy` by default. I actually feel like there are no real pros for this feature, since users who are planning to use the `network_policy` feature will probably inform themselves on how to enable it within this module. It also makes more sense that users who are not aware of this feature or don't want to use it, don't need to do anything. (In contrast to the current situation where this last category of users is probably experiencing the described overhead without realising it.) 

Thanks for taking this suggestion into consideration! I'm more than happy to create a PR if this gets approved.

### PR DESCRIPTION
**Pull request by JeremyKeustersML6**
This PR fixes #804.

The only thing I'm not sure about is whether or not the `network_policy` checks are necessary in the `stub` integration tests (`stub_domains`, `stub_domains_private`, `stub_domains_upstream_nameservers`).

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by morgante — CHANGES_REQUESTED** [review]
Thanks! This is fine, but FYI we are going to hold off on merging until the next major release.

**Comment by JeremyKeustersML6** [comment]
Thanks! Do you have any more information in the meantime on why the CI/CD pipeline is failing? Can't see the cloud build details.

**Review by bharathkkb — COMMENTED** [review]
Hi @JeremyKeustersML6 
We have an upcoming breaking release coming up that we can roll this into. Could you add this to the [upgrade guide ](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/upgrading_to_v14.0.md )showing how users can continue to use netpol with 14.0? A diff like [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/upgrading_to_v10.0.md#default-machine-type) should work.

**Comment by JeremyKeustersML6** [comment]
Sure @bharathkkb ! Will push something tomorrow.

**Comment by JeremyKeustersML6** [comment]
I added some documentation @bharathkkb . Let me know if it's okay!

**Comment by morgante** [comment]
@JeremyKeustersML6 Please resolve the linter errors ^^^

**Review by morgante — APPROVED** [review]

**Pull request merged**
