### PR TITLE
Fix: Can't create zonal beta-private cluster is region not set.

### PR DESCRIPTION
**Pull request by swbsf**
Hello,

Creating a zonal cluster will fail with a
```
Error: Invalid template interpolation value

  on .terraform/modules/gke_private/modules/beta-private-cluster/cluster.tf line 52, in resource "google_container_cluster" "primary":
  52:   subnetwork = "projects/${local.network_project_id}/regions/${var.region}/subnetworks/${var.subnetwork}"
    |----------------
    | var.region is null

The expression result is null. Cannot include a null value in a string
template.
```
The bug seems here [https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/bf4d0da796f3df0e5d924ab04c701df0a239e341/modules/beta-private-cluster/cluster.tf#L52](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/bf4d0da796f3df0e5d924ab04c701df0a239e341/modules/beta-private-cluster/cluster.tf#L52)
Which should reference local.region instead of var.region if I'm correct?

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster/cluster.tf /tmp/tmp.IHuBj9vIbP/workspace/modules/beta-private-cluster/cluster.tf
52c52
<   subnetwork = "projects/${local.network_project_id}/regions/${local.region}/subnetworks/${var.subnetwork}"
---
>   subnetwork = "projects/${local.network_project_id}/regions/${var.region}/subnetworks/${var.subnetwork}"
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Review by morgante — CHANGES_REQUESTED** [review]
Changes need to be made in `autogen/`.

**Comment by swbsf** [comment]
> Changes need to be made in `autogen/`.

Ok done, anything else?

**Comment by morgante** [comment]
@swbsf You need to run `make build`.

**Review by morgante — APPROVED** [review]

**Pull request merged**
