### PR TITLE
Add KALM config

### PR DESCRIPTION
**Pull request by c0ffeec0der**
Add KALM config

### CODE REVIEW

**Comment by c0ffeec0der** [comment]
Okay, beta provider updated in /autogen/version.tf.tmpl

**Comment by bharathkkb** [comment]
@c0ffeec0der you will need to update the examples which use the beta-modules as well. If you do `make docker_test_lint` that should show you which modules are failing validation due to this.

**Comment by c0ffeec0der** [comment]
I ran make docker_test_lint and it found a lot of errors (attached). But i think most is not related to the change, rather to windows character formatting. So I did some guesswork here and think the modules in examples folder get the beta version from test/setup/versions.tf . I have updated the file. Is the test on your end still failing? If you could supply the result of make docker_test_lint on your end, I'll make the changes in the code

[test_lint_error.txt](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/files/4666014/test_lint_error.txt)

**Comment by bharathkkb** [comment]
Sure, here are the logs: https://gist.github.com/bharathkkb/f1298ef2629c1ce0f25f30fea3de0c71
Basically any example like `./examples/node_pool ` you see that has the error `No provider "google-beta" plugins meet the constraint` is failing because we have the required beta provider to be at least `3.21.0` but those examples are using an older version.

**Comment by c0ffeec0der** [comment]
Ah okay, so I have updated the failing version in /examples

But the ones in /test/fixtures doesn't seem to specify provider version. It looks like it use the same one in /examples?

I see the second trigger of the cloud build successful. Is that the lint check? If there is still error, let me know how to fix the one in /test/fixtures, because I couldn't find the provider version explicitly mentioned in that one. Thanks

**Comment by bharathkkb** [comment]
I apologize for the back and forth, we are working to surface these logs to make contributing easier 😃  And yes, the ones in fixtures don't need them as we have set in the examples.

LGTM overall. However we need to make sure that the issue mentioned here https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/428 does not happen. I think this was fixed in the provider but I am happy to give this a whirl and confirm. 

@morgante I think int tests are failing due to the cloudbuild service account unable to copy the acm yaml from GCS. Could you PTAL?

**Comment by c0ffeec0der** [comment]
No worries, always happy to help :)

**Pull request merged**
