### PR TITLE
Expose service account key file variable

### PR DESCRIPTION
**Pull request by alexw19**
Expose service account key file variable due to default account not having permissions to retrieve cluster credentials to run kubectl commands

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@alexw19
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./modules/asm/main.tf:64:  service_account_key_file = var.service_account_key_file	
./modules/asm/main.tf:65:  
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/asm/main.tf
--- old/modules/asm/main.tf
+++ new/modules/asm/main.tf
@@ -61,8 +61,8 @@
   cluster_name             = var.cluster_name
   cluster_location         = var.cluster_location
   internal_ip              = var.internal_ip
-  service_account_key_file = var.service_account_key_file	
-  
+  service_account_key_file = var.service_account_key_file
+
   kubectl_create_command  = "${path.module}/scripts/create_cpr.sh ${local.revision_name} ${local.channel} ${var.enable_cni} ${var.enable_vpc_sc}"
   kubectl_destroy_command = "${path.module}/scripts/destroy_cpr.sh ${local.revision_name}"
 
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@alexw19
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/asm/README.md /tmp/tmp.myLttZvR1l/workspace/modules/asm/README.md
65a66
> | service\_account\_key\_file | Path to service account key file to auth as for running `gcloud container clusters get-credentials`. | `string` | `""` | no |
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/asm/README.md /tmp/tmp.ldxCBeGGJJ/generate_docs/workspace/modules/asm/README.md
65a66
> | service\_account\_key\_file | Path to service account key file to auth as for running `gcloud container clusters get-credentials`. | `string` | `""` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./modules/asm/main.tf:65:  
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/asm/main.tf
--- old/modules/asm/main.tf
+++ new/modules/asm/main.tf
@@ -62,7 +62,7 @@
   cluster_location         = var.cluster_location
   internal_ip              = var.internal_ip
   service_account_key_file = var.service_account_key_file
-  
+
   kubectl_create_command  = "${path.module}/scripts/create_cpr.sh ${local.revision_name} ${local.channel} ${var.enable_cni} ${var.enable_vpc_sc}"
   kubectl_destroy_command = "${path.module}/scripts/destroy_cpr.sh ${local.revision_name}"
 
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@alexw19
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/asm/README.md /tmp/tmp.YXCKZLyt5H/workspace/modules/asm/README.md
65a66
> | service\_account\_key\_file | Path to service account key file to auth as for running `gcloud container clusters get-credentials`. | `string` | `""` | no |
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/asm/README.md /tmp/tmp.JfiacoLYEp/generate_docs/workspace/modules/asm/README.md
65a66
> | service\_account\_key\_file | Path to service account key file to auth as for running `gcloud container clusters get-credentials`. | `string` | `""` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./modules/asm/main.tf:64:  service_account_key_file = var.service_account_key_file	
./modules/asm/main.tf:65:  
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/asm/main.tf
--- old/modules/asm/main.tf
+++ new/modules/asm/main.tf
@@ -61,8 +61,8 @@
   cluster_name             = var.cluster_name
   cluster_location         = var.cluster_location
   internal_ip              = var.internal_ip
-  service_account_key_file = var.service_account_key_file	
-  
+  service_account_key_file = var.service_account_key_file
+
   kubectl_create_command  = "${path.module}/scripts/create_cpr.sh ${local.revision_name} ${local.channel} ${var.enable_cni} ${var.enable_vpc_sc}"
   kubectl_destroy_command = "${path.module}/scripts/destroy_cpr.sh ${local.revision_name}"
 
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Review by bharathkkb — CHANGES_REQUESTED** [review]
Thanks for the PR @alexw19 
Could you fix the comments in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1372#issuecomment-1226191730
Also if you are running in a CI system that supports running other commands, activating the SA out of band will also work.

**Pull request closed without merging**
