### PR TITLE
feat!: Set the provided SA when creating autopilot clusters

### LINKED ISSUE #1488: beta-autopilot-private-cluster uses default service account
### TL;DR

Using the `beta-autopilot-private-cluster` uses a the default service account for the cluster created in GCP.

```bash
gcloud container clusters describe --region northamerica-northeast2 cluster-main-test-29420926 | grep serviceAccount
    serviceAccount: default
  serviceAccount: default
    serviceAccount: default
```

Looking in [cluster.tf](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/v24.0.0/modules/beta-autopilot-private-cluster/cluster.tf) I don't even see any reference to the service_account variable.

### Expected behavior

The cluster should use the service account created by the module.

### Observed behavior

Cluster uses default service account which is against GKE [hardening guidelines](https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#use_least_privilege_sa). 

### Terraform Configuration

```hcl
resource "random_id" "cluster" {
  byte_length = 4
}

// Subnet for Cluster.
resource "google_compute_subnetwork" "cluster-subnet" {
  project       = var.project_id
  name          = "cluster-${var.name}-subnet-${var.environment_realm}-${random_id.cluster.hex}"
  ip_cidr_range = "10.3.0.0/16"
  region        = var.region
  network       = var.network
  private_ip_google_access = true
  secondary_ip_range {
    range_name    = "cluster-${var.name}-subnet-${var.environment_realm}-range-pods"
    ip_cidr_range = "192.168.10.0/24"
  }
  secondary_ip_range {
    range_name    = "cluster-${var.name}-subnet-${var.environment_realm}-range-services"
    ip_cidr_range = "192.168.11.0/24"
  }
  depends_on = [
    var.network
  ]
}

module "main-cluster" {
  source                     = "terraform-google-modules/kubernetes-engine/google//modules/beta-autopilot-private-cluster"
  project_id                 = var.project_id
  name                       = "cluster-${var.name}-${var.environment_realm}-${random_id.cluster.hex}"
  region                     = var.region
  zones                      = ["${var.region}-a", "${var.region}-b"]
  network                    = var.network
  subnetwork                 = google_compute_subnetwork.cluster-subnet.name
  ip_range_pods              = "cluster-${var.name}-subnet-${var.environment_realm}-range-pods"
  ip_range_services          = "cluster-${var.name}-subnet-${var.environment_realm}-range-services"
  horizontal_pod_autoscaling = true
  enable_private_endpoint    = false
  enable_private_nodes       = true
  enable_vertical_pod_autoscaling = true
  release_channel = "RAPID"
  
  master_ipv4_cidr_block     = "10.0.0.0/28"
  depends_on = [
    google_compute_subnetwork.cluster-subnet
  ]
}
```

### Terraform Version

```sh
+ provider registry.terraform.io/hashicorp/google v4.36.0
+ provider registry.terraform.io/hashicorp/google-beta v4.44.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ferrarimarco**
Fixes #1488 

Hi folks!

In this PR, I'm trying to address the above issue, although I think the [necessary server-side fix](https://github.com/hashicorp/terraform-provider-google/issues/9505#issuecomment-1340074019) is still being rolled out.

Hopefully I got the autogen bits right :)

### CODE REVIEW

**Comment by ferrarimarco** [comment]
If I read the log correctly, the failures reported in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1495/checks?check_run_id=9992487427 don't seem too related to this PR, but rather to a checksum mismatch when downloading providers/plugins.

**Comment by comment-bot-dev** [comment]
@ferrarimarco
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-autopilot-public-cluster/cluster.tf /tmp/tmp.bk2hDUABCh/workspace/modules/beta-autopilot-public-cluster/cluster.tf
73a74,83
>   cluster_autoscaling {
>     enabled = var.create_service_account
>     dynamic "auto_provisioning_defaults" {
>       for_each = var.create_service_account ? [1] : []
> 
>       content {
>         service_account = local.service_account
>       }
>     }
>   }
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
@ferrarimarco
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by ferrarimarco** [comment]
Ah, so now the build may be failing for that yet missing server-side fix.

**Comment by comment-bot-dev** [comment]
@ferrarimarco
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/beta-autopilot-public-cluster/cluster.tf
--- old/modules/beta-autopilot-public-cluster/cluster.tf
+++ new/modules/beta-autopilot-public-cluster/cluster.tf
@@ -78,7 +78,7 @@
 
       content {
         service_account = local.service_account
-        oauth_scopes = local.node_pools_oauth_scopes["https://www.googleapis.com/auth/cloud-platform"]
+        oauth_scopes    = local.node_pools_oauth_scopes["https://www.googleapis.com/auth/cloud-platform"]
       }
     }
   }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/beta-autopilot-private-cluster/cluster.tf
--- old/modules/beta-autopilot-private-cluster/cluster.tf
+++ new/modules/beta-autopilot-private-cluster/cluster.tf
@@ -78,7 +78,7 @@
 
       content {
         service_account = local.service_account
-        oauth_scopes = local.node_pools_oauth_scopes["https://www.googleapis.com/auth/cloud-platform"]
+        oauth_scopes    = local.node_pools_oauth_scopes["https://www.googleapis.com/auth/cloud-platform"]
       }
     }
   }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@ferrarimarco
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by ferrarimarco** [comment]
It appears to be the case. This is an extract from the Terraform `INFO` output running in my environment when testing this PR:

```
2022-12-09T13:53:19.420Z [ERROR] provider.terraform-provider-google-beta_v4.44.1_x5: Response contains error diagnostic: diagnostic_attribute=AttributeName("cluster_autoscaling").ElementKeyInt(0).AttributeName("enabled") @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/diag/diagnostics.go:56 diagnostic_detail=""cluster_autoscaling.0.enabled": conflicts with enable_autopilot" diagnostic_summary="Conflicting configuration arguments" @module=sdk.proto diagnostic_severity=ERROR tf_proto_version=5.2 tf_provider_addr=provider tf_req_id=REDACTED tf_resource_type=google_container_cluster tf_rpc=ValidateResourceTypeConfig timestamp=2022-12-09T13:53:19.420Z
2022-12-09T13:53:19.420Z [ERROR] vertex "module.gke.google_container_cluster.primary" error: Conflicting configuration arguments
2022-12-09T13:53:19.420Z [ERROR] vertex "module.gke.google_container_cluster.primary (expand)" error: Conflicting configuration arguments
```

**Comment by ferrarimarco** [comment]
Ah, I was wrongly setting `cluster_autoscaling.enabled`. Fixed.

**Comment by ferrarimarco** [comment]
Ok, now I _think_ I'm getting the server-side error:

```
│ Error: googleapi: Error 400: Overriding Autopilot autoscaling settings is not allowed.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.DebugInfo",
│     "detail": "[ORIGINAL ERROR] cloud-kubernetes::3: Overriding Autopilot autoscaling settings is not allowed. [google.rpc.error_details_ext] { code: 3 message: \"Overriding Autopilot autoscaling settings is not allowed.\" }"
│   }
│ ]
│ , badRequest
│
│   with module.gke.google_container_cluster.primary,
│   on terraform-google-kubernetes-engine/modules/beta-autopilot-private-cluster/cluster.tf line 22, in resource "google_container_cluster" "primary":
│   22: resource "google_container_cluster" "primary" {
```

**Comment by comment-bot-dev** [comment]
@ferrarimarco
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by CaliWee** [comment]
> Fixes #1488
> 
> Hi folks!
> 
> In this PR, I'm trying to address the above issue, although I think the [necessary server-side fix](https://github.com/hashicorp/terraform-provider-google/issues/9505#issuecomment-1340074019) is still being rolled out.
> 
> Hopefully I got the autogen bits right :)

Hi @ferrarimarco! Thank you for working on this. is there a GitHub issue or PR I can watch to track the server side fix?

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @ferrarimarco. 
I pushed a few changes as we are switching to a new test framework. Looks like this will be a breaking change as the conflict on the field was removed in 4.44+.

**Comment by comment-bot-dev** [comment]
@ferrarimarco
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./build/int.cloudbuild.yaml:409:  args: ['/bin/bash', '-c', 'cft test run TestSimpleAutopilotPrivateNonDefaultSA --stage init --verbose'] 
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ```

**Comment by comment-bot-dev** [comment]
@ferrarimarco
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@ferrarimarco
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@ferrarimarco
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@ferrarimarco
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
