### PR TITLE
feat: add support for gpu_driver_installation_config on nodepool

### PR DESCRIPTION
**Pull request by umeshkumhar**
- Updated guest_accelerator to add gpu driver installation

### CODE REVIEW

**Comment by ericyz** [comment]
Please review the logs below
   gpu_driver_version   = lookup(each.value, "gpu_driver_version", "")
+            gpu_driver_version = lookup(each.value, "gpu_driver_version", "")

**Comment by umeshkumhar** [comment]
@ericyz @bharathkkb Updated the fix.

**Comment by ericyz** [comment]
--- old/cluster.tf
+++ new/cluster.tf
@@ -528,11 +528,11 @@
         type               = lookup(each.value, "accelerator_type", "")
         count              = lookup(each.value, "accelerator_count", 0)
         gpu_partition_size = lookup(each.value, "gpu_partition_size", null)
-        
+
         dynamic "gpu_driver_installation_config" {
           for_each = lookup(each.value, "gpu_driver_version", "") != "" ? [1] : []
           content {
-            gpu_driver_version   = lookup(each.value, "gpu_driver_version", "")
+            gpu_driver_version = lookup(each.value, "gpu_driver_version", "")
           }
         }
       }
@@ -727,7 +727,7 @@
         dynamic "gpu_driver_installation_config" {
           for_each = lookup(each.value, "gpu_driver_version", "") != "" ? [1] : []
           content {
-            gpu_driver_version   = lookup(each.value, "gpu_driver_version", "")
+            gpu_driver_version = lookup(each.value, "gpu_driver_version", "")
           }
         }
       }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/beta-private-cluster-update-variant/cluster.tf
--- old/modules/beta-private-cluster-update-variant/cluster.tf
+++ new/modules/beta-private-cluster-update-variant/cluster.tf
@@ -739,7 +739,7 @@
         dynamic "gpu_driver_installation_config" {
           for_each = lookup(each.value, "gpu_driver_version", "") != "" ? [1] : []
           content {
-            gpu_driver_version   = lookup(each.value, "gpu_driver_version", "")
+            gpu_driver_version = lookup(each.value, "gpu_driver_version", "")
           }
         }
       }
@@ -974,7 +974,7 @@
         dynamic "gpu_driver_installation_config" {
           for_each = lookup(each.value, "gpu_driver_version", "") != "" ? [1] : []
           content {
-            gpu_driver_version   = lookup(each.value, "gpu_driver_version", "")
+            gpu_driver_version = lookup(each.value, "gpu_driver_version", "")
           }
         }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
       }
modules/beta-public-cluster/cluster.tf
--- old/modules/beta-public-cluster/cluster.tf
+++ new/modules/beta-public-cluster/cluster.tf
@@ -626,7 +626,7 @@
         dynamic "gpu_driver_installation_config" {
           for_each = lookup(each.value, "gpu_driver_version", "") != "" ? [1] : []
           content {
-            gpu_driver_version   = lookup(each.value, "gpu_driver_version", "")
+            gpu_driver_version = lookup(each.value, "gpu_driver_version", "")
           }
         }
       }
@@ -860,7 +860,7 @@
         dynamic "gpu_driver_installation_config" {
           for_each = lookup(each.value, "gpu_driver_version", "") != "" ? [1] : []
           content {
-            gpu_driver_version   = lookup(each.value, "gpu_driver_version", "")
+            gpu_driver_version = lookup(each.value, "gpu_driver_version", "")
           }
         }
       }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/private-cluster/cluster.tf
--- old/modules/private-cluster/cluster.tf
+++ new/modules/private-cluster/cluster.tf
@@ -551,7 +551,7 @@
         dynamic "gpu_driver_installation_config" {
           for_each = lookup(each.value, "gpu_driver_version", "") != "" ? [1] : []
           content {
-            gpu_driver_version   = lookup(each.value, "gpu_driver_version", "")
+            gpu_driver_version = lookup(each.value, "gpu_driver_version", "")
           }
         }
       }
@@ -746,7 +746,7 @@
         dynamic "gpu_driver_installation_config" {
           for_each = lookup(each.value, "gpu_driver_version", "") != "" ? [1] : []
           content {
-            gpu_driver_version   = lookup(each.value, "gpu_driver_version", "")
+            gpu_driver_version = lookup(each.value, "gpu_driver_version", "")
           }
         }
       }
Error: terraform fmt failed with exit code 3

**Comment by umeshkumhar** [comment]
@ericyz I hope this should fix lints now, can we rerun the testcases again!

**Comment by ericyz** [comment]
Notes for myself. feature added in [v4.75.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.75.0)

**Review by ericyz — APPROVED** [review]
LGTM

**Pull request merged**
