### PR TITLE
feat: adds local_nvme_ssd_block_config to beta-public-cluster module

### PR DESCRIPTION
**Pull request by matilote**
Adds local nvme ssd block configuration as per https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster.html#local_nvme_ssd_block_config.

Allows usage of NVME interface alongside SCSI.
Consider reusing this block within other modules too.

### CODE REVIEW

**Comment by NissesSenap** [comment]
@matilote all the config is generated from https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/autogen/main, take a look there and perform your updates.

**Comment by matilote** [comment]
> @matilote all the config is generated from https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/autogen/main, take a look there and perform your updates.

Added change to the autogen templates instead.

**Comment by kri5** [comment]
Anything blocking this MR?

Would be much appreciated to see those changes land 🙏

**Comment by VladStarr** [comment]
Up

This option will be very useful.
Local NVMe SSD Block API also automatically created RAID arrays for Local SSDs up to 9TiB.

**Comment by NissesSenap** [comment]
@matilote you also need to run the script to update the files that get generated. 
Look in the makefile

**Comment by bsgrigorov** [comment]
this feature will be very useful can we reopen this?

**Comment by sbocinec** [comment]
@matilote by chance could you rebase from the base branch (`master`) and try to push the changes to satisfy the CI? 

It would be awesome if this feature can finally land in the module as right now we need to maintain a fork to use the feature, causing unnecessary maintenance effort.

**Comment by florianMalbranque** [comment]
Same as @sbocinec, @gtsorbo would you kindly take a look ?

**Pull request closed without merging**
