### PR TITLE
Update README to prevent KSA misconfiguration

### PR DESCRIPTION
**Pull request by MoskitoHero**
Update the documentation of the workload identity module to address issue #1065

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/workload-identity/README.md /tmp/tmp.uEHMjAi4qt/workspace/modules/workload-identity/README.md
103c103
< | k8s\_sa\_name | Name for the Kubernetes service account; overrides `var.name`. `cluster_name` and `location` must be set when this input is specified. | `string` | `null` | no |
---
> | k8s\_sa\_name | Name for the Kubernetes service account; overrides `var.name`. | `string` | `null` | no |
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/workload-identity/README.md /tmp/tmp.LnDydu4SsM/generate_docs/workspace/modules/workload-identity/README.md
103c103
< | k8s\_sa\_name | Name for the Kubernetes service account; overrides `var.name`. `cluster_name` and `location` must be set when this input is specified. | `string` | `null` | no |
---
> | k8s\_sa\_name | Name for the Kubernetes service account; overrides `var.name`. | `string` | `null` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by morgante** [comment]
Please sign the CLA.

**Comment by MoskitoHero** [comment]
Sorry, I had trouble signing the CLA due to my numerous email addresses associated to my Github account. Thanks for accepting this PR.

**Review by morgante — APPROVED** [review]

**Comment by morgante** [comment]
> Sorry, I had trouble signing the CLA due to my numerous email addresses associated to my Github account. Thanks for accepting this PR.

Thank you for contributing!

**Pull request merged**
