### PR TITLE
feat: add location_policy and fix permadiff

### PR DESCRIPTION
**Pull request by bogaertg**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@bogaertg
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@bogaertg
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Our test  beta-cluster-local seem to be failing with 
`Error: error creating NodePool: googleapi: Error 400: Location policy cannot be set for nodepools in clusters that does not support the feature`. I suspect this is due to the limitation that `Location policy is supported only in 1.24.1+ clusters.` per https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#nested_autoscaling

Can we default to null instead if no explicit value is provided?

**Comment by comment-bot-dev** [comment]
@bogaertg
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster-update-variant/cluster.tf /tmp/tmp.4t3uxMMunz/workspace/modules/beta-private-cluster-update-variant/cluster.tf
554c554
<       location_policy = lookup(autoscaling.value, "location_policy", null)
---
>       location_policy = lookup(autoscaling.value, "location_policy", (lookup(autoscaling.value, "spot", false) || lookup(autoscaling.value, "preemptible", false) ? "ANY" : "BALANCED"))
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
@bogaertg
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by bogaertg** [comment]
> Our test beta-cluster-local seem to be failing with `Error: error creating NodePool: googleapi: Error 400: Location policy cannot be set for nodepools in clusters that does not support the feature`. I suspect this is due to the limitation that `Location policy is supported only in 1.24.1+ clusters.` per https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#nested_autoscaling
> 
> Can we default to null instead if no explicit value is provided?

done

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
