### PR TITLE
feat: Add option image_type in cluster_autoscaling block

### LINKED ISSUE #1904: No Option for specifying image_type in auto_provisioning_defaults
### TL;DR

This issue resurrects #1191, which was closed for some reason without the corresponding PR merged.

The 'auto_provisioning_defaults' block supports [image_type](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#image_type)

But the option is not available currently in the module still.

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#image_type
```

### Detailed design

```markdown
Here is how it could look like:


  cluster_autoscaling {
    enabled = var.cluster_autoscaling.enabled
    dynamic "auto_provisioning_defaults" {
      for_each = var.cluster_autoscaling.enabled ? [1] : []

      content {
        service_account  = local.service_account
        oauth_scopes     = local.node_pools_oauth_scopes["all"]
        min_cpu_platform = lookup(var.node_pools[0], "min_cpu_platform", "")
        image_type       = lookup(var.cluster_autoscaling, "image_type", "")
      }
    }
  }
```
```


### Additional information

_No response_

### PR DESCRIPTION
**Pull request by endrec**
Fixes #1904

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @endrec!

Can you please add `image_type` to the `cluster_autoscaling` variable so it is included in the generated documentation: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/autogen/main/variables.tf.tmpl#L244

**Comment by apeabody** [comment]
Thanks @endrec! - Can you please (also) make your change to the template: `autogen/main/variables.tf.tmpl` and then `make build`.

**Comment by endrec** [comment]
@apeabody Done. :)

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @endrec!

**Pull request merged**
