### PR TITLE
feat!: cost_management_config is out of beta now

### PR DESCRIPTION
**Pull request by zmaupin**
move the config outside the logic of beta only

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@zmaupin
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @zmaupin 
Looks like this was moved to GA in 4.42. Could you bump the min provider versions in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/autogen/main/versions.tf.tmpl
and also update the upgrade guide https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/upgrading_to_v24.0.md#minimum-google-provider-versions to include this in the latest breaking release https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1447

**Comment by zmaupin** [comment]
@bharathkkb Thanks for looking! I have updated the two files you asked me to change.

**Comment by comment-bot-dev** [comment]
@zmaupin
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-autopilot-private-cluster/versions.tf /tmp/tmp.p1oH3v5xNk/workspace/modules/beta-autopilot-private-cluster/versions.tf
24c24
<       version = ">= 4.36.0, < 5.0"
---
>       version = ">= 4.42.0, < 5.0"
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-autopilot-public-cluster/versions.tf /tmp/tmp.p1oH3v5xNk/workspace/modules/beta-autopilot-public-cluster/versions.tf
24c24
<       version = ">= 4.36.0, < 5.0"
---
>       version = ">= 4.42.0, < 5.0"
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster/versions.tf /tmp/tmp.p1oH3v5xNk/workspace/modules/beta-private-cluster/versions.tf
24c24
<       version = ">= 4.36.0, < 5.0"
---
>       version = ">= 4.42.0, < 5.0"
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-private-cluster-update-variant/versions.tf /tmp/tmp.p1oH3v5xNk/workspace/modules/beta-private-cluster-update-variant/versions.tf
24c24
<       version = ">= 4.36.0, < 5.0"
---
>       version = ">= 4.42.0, < 5.0"
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster/versions.tf /tmp/tmp.p1oH3v5xNk/workspace/modules/beta-public-cluster/versions.tf
24c24
<       version = ">= 4.36.0, < 5.0"
---
>       version = ">= 4.42.0, < 5.0"
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-public-cluster-update-variant/versions.tf /tmp/tmp.p1oH3v5xNk/workspace/modules/beta-public-cluster-update-variant/versions.tf
24c24
<       version = ">= 4.36.0, < 5.0"
---
>       version = ">= 4.42.0, < 5.0"
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
