### PR TITLE
feat: allow setting network tags on autopilot clusters

### PR DESCRIPTION
**Pull request by gtsorbo**
* dynamically configure `node_pool_auto_config` block with `network_tags` nested block
* Addressing https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1496

### CODE REVIEW

**Review by ericyz — APPROVED** [review]
LGTM

**Comment by ericyz** [comment]
@apeabody  @bharathkkb - would you like to pair review and merge when ready. Thanks

**Review by apeabody — APPROVED** [review]
LGTM

**Pull request merged**
