### PR TITLE
docs: add location_policy entry for node_pools

### PR DESCRIPTION
**Pull request by bogaertg**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@bogaertg
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/README.md /tmp/tmp.UmoRcYXCdm/workspace/README.md
281d280
< | location_policy | [Location policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#location_policy) specifies the algorithm used when scaling-up the node pool. Location policy is supported only in 1.24.1+ clusters. | " " | Optional |
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Review by bharathkkb — CHANGES_REQUESTED** [review]
Thanks for the PR
Could make changes to the autogen as mentioned in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1482#issuecomment-1330320468?

**Comment by comment-bot-dev** [comment]
@bogaertg
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/README.md /tmp/tmp.ofLntJc6pz/workspace/README.md
281d280
< | location_policy | [Location policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#location_policy) specifies the algorithm used when scaling-up the node pool. Location policy is supported only in 1.24.1+ clusters. | " " | Optional |
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by bogaertg** [comment]
done 😉

**Comment by comment-bot-dev** [comment]
@bogaertg
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
