### PR TITLE
feat: add gcp_filestore_csi_driver_config to addons config

### PR DESCRIPTION
**Pull request by moskitone**
[#1030](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1030)
Signed-off-by: Volodymyr Moseichuk <moskitone@gmail.com>

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by morgante — APPROVED** [review]
Thanks, we will include this in our next breaking release.

**Comment by morgante** [comment]
@moskitone Please rebase when you get a chance.

**Comment by bharathkkb** [comment]
@moskitone @DavidSpek We can include this in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1146 could you rebase?

**Comment by DavidSpek** [comment]
@bharathkkb I'll rebase it right now.

**Comment by DavidSpek** [comment]
@bharathkkb I've just rebased on the latest master in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1161.

**Comment by bharathkkb** [comment]
superseded by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1166

**Pull request closed without merging**
