### PR TITLE
feat: bump `enable_intranode_visibility` to GA

### PR DESCRIPTION
**Pull request by DrFaust92**

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @DrFaust92!

Please see the lint findings:
```
Working in ./modules/beta-autopilot-private-cluster ...
1 issue(s) found:

Warning: [Fixable] variable "enable_intranode_visibility" is declared but not used (terraform_unused_declarations)

  on variables.tf line 460:
 460: variable "enable_intranode_visibility" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.7.0/docs/rules/terraform_unused_declarations.md

tflint failed ./modules/beta-autopilot-private-cluster 
Working in ./modules/beta-autopilot-public-cluster ...
1 issue(s) found:

Warning: [Fixable] variable "enable_intranode_visibility" is declared but not used (terraform_unused_declarations)

  on variables.tf line 430:
 430: variable "enable_intranode_visibility" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.7.0/docs/rules/terraform_unused_declarations.md
```

**Comment by DrFaust92** [comment]
[apeabody](https://github.com/apeabody) trying again, lint passes in CI and locally

**Comment by DrFaust92** [comment]
[apeabody](https://github.com/apeabody) any idea why tests failed? 😢

**Comment by apeabody** [comment]
> [apeabody](https://github.com/apeabody) any idea why tests failed? 😢

Might be a flake, re-running the tests.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @DrFaust92!

**Comment by apeabody** [comment]
validated [enable_intranode_visibility](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster.html#enable_intranode_visibility) GA in v5.25.0

**Pull request merged**
