### PR TITLE
fix: Create new node pool when shielded_instance_config changes

### LINKED ISSUE #923: Enabling secure boot on an existing nodepool is failing
Hello, we tried to enable secure boot on an existing node pool, but its failing.

**NP Config**: added enable_secure_boot:true
```
      {
        name = "node-pool"
        machine_type = "n1-standard-8"
        local_ssd_count = 0
        disk_size_gb = 100
        disk_type = "pd-standard"
        image_type = "COS_CONTAINERD"
        auto_repair = true
        auto_upgrade = false
        preemptible = false
        initial_node_count = 1
        min_count = 1
        max_count = 10
        default_max_pods_per_node = 32
        max_surge = 1
        max_unavailable = 0
        version = "1.18.16-gke.502"
        enable_secure_boot = true
      }
```

**PLAN RELATED TO CHANGE:**
```
taint             = [] -> (known after apply)
~ shielded_instance_config {
    enable_integrity_monitoring = true
    ~ enable_secure_boot          = false -> true # forces replacement
}
--
```

**ERROR:**
```
Error: error creating NodePool: googleapi: Error 409: Already exists: projects/PROJECT/locations/us-central1/clusters/CLUSTER/nodePools/NP., alreadyExists
```

**TRIED:**

To update file cluster.tf and add in **"beta-private-cluster-update-variant/cluster.tf"**, under **force_node_pool_recreation_resources**, enable_secure_boot, but this did not help.

Please let me know how we should proceed in here?

Thanks

### PR DESCRIPTION
**Pull request by abursavich**
Fixes #923

This adds the `enable_secure_boot` and `enable_integrity_monitoring` properties from the `shielded_instance_config` to the list that triggers the creation of a new node pool.

Example:
```
...

      ~ node_config {
          ~ shielded_instance_config {
              ~ enable_secure_boot          = false -> true # forces replacement
                # (1 unchanged attribute hidden)
            }
        }

...

│ Error: resource - projects/xxx/locations/us-west1/clusters/xxx/nodePools/xxx-00de - already exists
│ 
│   with module.gke.google_container_node_pool.pools["xxx"],
│   on .terraform/modules/gke/modules/beta-private-cluster-update-variant/cluster.tf line 448, in resource "google_container_node_pool" "pools":
│  448: resource "google_container_node_pool" "pools" {
│ 
```

See: ForceNew at https://github.com/hashicorp/terraform-provider-google/blob/v4.19.0/google/node_config.go#L208-L233

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@abursavich
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by abursavich** [comment]
I can't view any details of the `kubernetes-engine-int-trigger` failure?

**Comment by comment-bot-dev** [comment]
@abursavich
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @abursavich

**Pull request merged**
