### PR TITLE
fix: remove datapath provider from Autopilot modules

### LINKED ISSUE #1446: Terraform re-apply causes cluster deletion and recreation due to `datapath_provider` parameter
### TL;DR

Even when the default value for the `datapath_provider` variable is `DATAPATH_PROVIDER_UNSPECIFIED`, the `beta-autopilot-public-cluster` module creates a GKE cluster with Dataplane V2 enabled (`ADVANCED_DATAPATH`). 

This causes the next Terraform plan/apply to think that an outside change was made to the GKE cluster and forces a destroy + recreate.

### Expected behavior

When no change is made to the Terraform config, nothing changes in the Terraform plan.

### Observed behavior

The Terraform plan output is saying that it will replace the cluster resource (delete + recreate) due to the `datapath_provider` variable

### Terraform Configuration

```hcl
locals {
  network_name           = "gke-heisenberg-public-network"
  subnet_name            = "gke-heisenberg-public-subnet"
  master_auth_subnetwork = "gke-heisenberg-public-master-subnet"
  pods_range_name        = "ip-range-pods-gke-heisenberg-public"
  svc_range_name         = "ip-range-svc-gke-heisenberg-public"
  subnet_names           = [for subnet_self_link in module.gcp-network.subnets_self_links : split("/", subnet_self_link)[length(split("/", subnet_self_link)) - 1]]
}


module "gcp-network" {
  source       = "terraform-google-modules/network/google"
  project_id   = var.project_id
  network_name = local.network_name

  subnets = [
    {
      subnet_name   = local.subnet_name
      subnet_ip     = "10.0.0.0/17"
      subnet_region = var.region
    },
    {
      subnet_name   = local.master_auth_subnetwork
      subnet_ip     = "10.60.0.0/17"
      subnet_region = var.region
    },
  ]

  secondary_ranges = {
    (local.subnet_name) = [
      {
        range_name    = local.pods_range_name
        ip_cidr_range = "192.168.0.0/18"
      },
      {
        range_name    = local.svc_range_name
        ip_cidr_range = "192.168.64.0/18"
      },
    ]
  }
}


module "gke" {
  source                          = "terraform-google-modules/kubernetes-engine/google//modules/beta-autopilot-public-cluster"
  project_id                      = var.project_id
  name                            = "gke-heisenberg-cluster"
  regional                        = true
  region                          = var.region
  network                         = module.gcp-network.network_name
  subnetwork                      = local.subnet_names[index(module.gcp-network.subnets_names, local.subnet_name)]
  ip_range_pods                   = local.pods_range_name
  ip_range_services               = local.svc_range_name
  release_channel                 = "RAPID"
  enable_vertical_pod_autoscaling = true
}
```

### Terraform Version

```sh
1.3.3
```

### Additional information

Region is us-east1.

### PR DESCRIPTION
**Pull request by mastersingh24**
You cannot set datapath for Autopilot clusters.

Fixes #1446

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@mastersingh24
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-autopilot-private-cluster/cluster.tf /tmp/tmp.yRyYp2mYE6/workspace/modules/beta-autopilot-private-cluster/cluster.tf
121a122,123
>   datapath_provider = var.datapath_provider
> 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-autopilot-public-cluster/cluster.tf /tmp/tmp.yRyYp2mYE6/workspace/modules/beta-autopilot-public-cluster/cluster.tf
121a122,123
>   datapath_provider = var.datapath_provider
> 
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
@mastersingh24
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-autopilot-private-cluster/cluster.tf /tmp/tmp.DKaE0TX07f/workspace/modules/beta-autopilot-private-cluster/cluster.tf
121a122,123
>   datapath_provider = var.datapath_provider
> 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/beta-autopilot-public-cluster/cluster.tf /tmp/tmp.DKaE0TX07f/workspace/modules/beta-autopilot-public-cluster/cluster.tf
121a122,123
>   datapath_provider = var.datapath_provider
> 
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
@mastersingh24
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by mastersingh24** [comment]
No idea why this is failing test 27.  Don't see how this change would have any affect there.

**Comment by bharathkkb** [comment]
@mastersingh24 it may have been a flake. I will retry

**Review by bharathkkb — APPROVED** [review]

**Comment by comment-bot-dev** [comment]
@mastersingh24
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
