### PR TITLE
fix: switch ASM enable api, iam flags to native resources

### LINKED ISSUE #905: ASM Module: Replace script components with native resources
Based on https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/895#discussion_r635658897

### PR DESCRIPTION
**Pull request by bharathkkb**
fixes #905 

`enable_gcp_components` seems to [modify](https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/1cf61b679cd369f42a0e735f8e201de1a6a6433b/scripts/asm-installer/install_asm#L189-L191) update the cluster, so leaving it as is.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/examples/simple_zonal_with_asm/README.md /tmp/tmp.ZWbDTMeiaI/workspace/examples/simple_zonal_with_asm/README.md
16d15
< | service\_account | The GCP Service Account email address used to deploy ASM. | `string` | `""` | no |
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/examples/simple_zonal_with_asm/README.md /tmp/tmp.VUbnOlhiSk/generate_docs/workspace/examples/simple_zonal_with_asm/README.md
16d15
< | service\_account | The GCP Service Account email address used to deploy ASM. | `string` | `""` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Attempting to download /workspace/test/bundle.hcl bundle.
/tmp/bundler /workspace
Fetching Terraform 0.13.6 core package...
Local plugin directory ".plugins" found; scanning for provider binaries.
No ".plugins" directory found, skipping local provider discovery.
Creating terraform_0.13.6-bundle2021060104_linux_amd64.zip ...
All done!
Archive:  terraform_0.13.6-bundle2021060104_linux_amd64.zip
/workspace
Running terraform fmt
modules/asm/main.tf
--- old/modules/asm/main.tf
+++ new/modules/asm/main.tf
@@ -46,7 +46,7 @@
   // if enable_gcp_iam_roles is set, grant IAM roles to first non null principal in the order below
   asm_iam_member = var.enable_gcp_iam_roles ? coalesce(var.impersonate_service_account, var.service_account, var.iam_member) : ""
   # compute any additonal resources that ASM provisioner should depend on
-  additional_depends_on = concat(var.enable_gcp_apis ? [module.asm-services[0].project_id] : [], local.asm_iam_member != "" ? [for k,v in google_project_iam_member.asm_iam: v.etag] : [])
+  additional_depends_on = concat(var.enable_gcp_apis ? [module.asm-services[0].project_id] : [], local.asm_iam_member != "" ? [for k, v in google_project_iam_member.asm_iam : v.etag] : [])
 }
 
 resource "google_project_iam_member" "asm_iam" {
@@ -59,7 +59,7 @@
 module "asm-services" {
   source     = "terraform-google-modules/project-factory/google//modules/project_services"
   version    = "~> 10.0"
-  count     = var.enable_gcp_apis ? 1 : 0
+  count      = var.enable_gcp_apis ? 1 : 0
   project_id = var.project_id
 
   # https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/1cf61b679cd369f42a0e735f8e201de1a6a6433b/scripts/asm-installer/install_asm#L2005
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Review by morgante — APPROVED** [review]

**Comment by cloud-pharaoh** [comment]
I am 100% for using native TF resources rather than bash scripts hidden under TF modules. However, in this case, this module is a wrapper around install_asm.sh. I am concerned that now the burden of maintenance is higher than before where a subset of functionality (albeit minimal with APIs and IAM roles) is in TF and the rest in the script. 
I personally think that keeping it as simply a wrapper and letting the script decide if/when to create/destroy/recreate resources with the logic implemented there rather than selecting a flag that would make the module behave inconsistently because some of the functionality is extracted.

**Comment by morgante** [comment]
My view is that we should only use bash scripts where we _need_ to. Ideally we would eventually throw away the underlying script entirely. This is the approach we have successfully taken with project-factory and I'd like to take it here.

Obviously this _does_ increase the maintenance burden but in general I would rather do that than continue to use a massive bash script which re-implements logic that Terraform should be doing.

**Pull request merged**
