### PR TITLE
feat: Add enable_cilium_clusterwide_network_policy support

### PR DESCRIPTION
**Pull request by SavvasM1**
Leverage the [existing configuration field](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#enable_cilium_clusterwide_network_policy) on the google container cluster module to optionally declare usage of cilium clusterwide network policy CRDs

* Non-Beta
* Defaults to false
* Located at the base of the module

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @SavvasM1!

From the lint test:

```
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/README.md /tmp/tmp.dH7WdF6rzI/workspace/README.md
164d163
< | enable\_cilium\_clusterwide\_network\_policy | Enable Cilium Cluster Wide Network Policies on the cluster | `bool` | `false` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster/README.md /tmp/tmp.dH7WdF6rzI/workspace/modules/private-cluster/README.md
171d170
< | enable\_cilium\_clusterwide\_network\_policy | Enable Cilium Cluster Wide Network Policies on the cluster | `bool` | `false` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster/variables.tf /tmp/tmp.dH7WdF6rzI/workspace/modules/private-cluster/variables.tf
541,546d540
< variable "enable_cilium_clusterwide_network_policy" {
<   type        = bool
<   description = "Enable Cilium Cluster Wide Network Policies on the cluster"
<   default     = false
< }
< 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster-update-variant/README.md /tmp/tmp.dH7WdF6rzI/workspace/modules/private-cluster-update-variant/README.md
193d192
< | enable\_cilium\_clusterwide\_network\_policy | Enable Cilium Cluster Wide Network Policies on the cluster | `bool` | `false` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster-update-variant/variables.tf /tmp/tmp.dH7WdF6rzI/workspace/modules/private-cluster-update-variant/variables.tf
541,546d540
< variable "enable_cilium_clusterwide_network_policy" {
<   type        = bool
<   description = "Enable Cilium Cluster Wide Network Policies on the cluster"
<   default     = false
< }
< 
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/variables.tf /tmp/tmp.dH7WdF6rzI/workspace/variables.tf
726,731d725
< variable "enable_cilium_clusterwide_network_policy" {
<   type        = bool
<   description = "Enable Cilium Cluster Wide Network Policies on the cluster"
<   default     = false
< }
< 
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
```

**Comment by SavvasM1** [comment]
> Thanks for the contribution @SavvasM1!
> 
> From the lint test:
> 
> ```
> Checking submodule's files generation
> diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/README.md /tmp/tmp.dH7WdF6rzI/workspace/README.md
> 164d163
> < | enable\_cilium\_clusterwide\_network\_policy | Enable Cilium Cluster Wide Network Policies on the cluster | `bool` | `false` | no |
> diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster/README.md /tmp/tmp.dH7WdF6rzI/workspace/modules/private-cluster/README.md
> 171d170
> < | enable\_cilium\_clusterwide\_network\_policy | Enable Cilium Cluster Wide Network Policies on the cluster | `bool` | `false` | no |
> diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster/variables.tf /tmp/tmp.dH7WdF6rzI/workspace/modules/private-cluster/variables.tf
> 541,546d540
> < variable "enable_cilium_clusterwide_network_policy" {
> <   type        = bool
> <   description = "Enable Cilium Cluster Wide Network Policies on the cluster"
> <   default     = false
> < }
> < 
> diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster-update-variant/README.md /tmp/tmp.dH7WdF6rzI/workspace/modules/private-cluster-update-variant/README.md
> 193d192
> < | enable\_cilium\_clusterwide\_network\_policy | Enable Cilium Cluster Wide Network Policies on the cluster | `bool` | `false` | no |
> diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/private-cluster-update-variant/variables.tf /tmp/tmp.dH7WdF6rzI/workspace/modules/private-cluster-update-variant/variables.tf
> 541,546d540
> < variable "enable_cilium_clusterwide_network_policy" {
> <   type        = bool
> <   description = "Enable Cilium Cluster Wide Network Policies on the cluster"
> <   default     = false
> < }
> < 
> diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/variables.tf /tmp/tmp.dH7WdF6rzI/workspace/variables.tf
> 726,731d725
> < variable "enable_cilium_clusterwide_network_policy" {
> <   type        = bool
> <   description = "Enable Cilium Cluster Wide Network Policies on the cluster"
> <   default     = false
> < }
> < 
> Error: submodule's files generation has not been run, please run the
> 'make build' command and commit changes
> ```

Heya @apeabody , thanks :)

It should be OK now!

**Comment by SavvasM1** [comment]
Hey @apeabody :). I've run `make build` once more -- should be good for another gcbrun.

**Comment by apeabody** [comment]
confirmed `enable_cilium_clusterwide_network_policy` is present in v5.25.0 and defaults to false.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @SavvasM1!

**Comment by SavvasM1** [comment]
> Thanks for the contribution @SavvasM1!

Thanks for you help Andrew.

**Pull request merged**
