### PR TITLE
fix: use dynamic block for accelerators, updates for CI

### PR DESCRIPTION
**Pull request by bharathkkb**
- Switch to using a dynamic block for accelerators config due to https://github.com/hashicorp/terraform-provider-google/issues/12817. We have been using this field as https://www.terraform.io/language/attr-as-blocks#arbitrary-expressions-with-argument-syntax previously

Misc CI fixes:
- Remove Isitio/Cloudrun from examples. Part of https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1395
- Jail one test https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1431 due to an upstream issue
- Switch to using an inline command without linebreak for shutdown script as the API was complaining ` Error: error creating NodePool: googleapi: Error 400: Input "#!/usr/bin/env bash\nset ....ignore-daemonsets=true --delete-local-data \"$HOSTNAME\"\n" contains a linebreak., badRequest`
- Remove `remove_default_node_pool = true` due to  https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1227

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@bharathkkb
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part1/terraform
╷
│
 
Warning: 
Argument is deprecated
│
 
│
 
  with module.gke.google_container_cluster.primary,
│
 
  on .terraform/modules/gke/cluster.tf line 81, in resource "google_container_cluster" "primary":
│
 
  81:   enable_binary_authorization = 
var.enable_binary_authorization
│
 
│
 
Deprecated in favor of binary_authorization.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/acm-terraform-blog-part2/terraform
╷
│
 
Warning: 
Argument is deprecated
│
 
│
 
  with module.gke.google_container_cluster.primary,
│
 
  on .terraform/modules/gke/cluster.tf line 81, in resource "google_container_cluster" "primary":
│
 
  81:   enable_binary_authorization = 
var.enable_binary_authorization
│
 
│
 
Deprecated in favor of binary_authorization.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/acm-terraform-blog-part3/terraform
╷
│
 
Warning: 
Argument is deprecated
│
 
│
 
  with module.gke.google_container_cluster.primary,
│
 
  on .terraform/modules/gke/modules/beta-public-cluster/cluster.tf line 113, in resource "google_container_cluster" "primary":
│
 
 113:   enable_binary_authorization = 
var.enable_binary_authorization
│
 
│
 
Deprecated in favor of binary_authorization.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/deploy_service
Success!
 The configuration is valid.
terraform_validate ./examples/disable_client_cert
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_beta
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_public_beta
Success!
 The configuration is valid.
terraform_validate ./examples/private_zonal_with_networking
Success!
 The configuration is valid.
terraform_validate ./examples/regional_private_node_pool_oauth_scopes
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster_iap_bastion
Success!
 The configuration is valid.
terraform_validate ./examples/shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/simple_autopilot_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_autopilot_public
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_beta
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private_beta
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_networking
Success!
 The configuration is valid.
terraform_validate ./examples/simple_windows_node_pool
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_acm
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_asm
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_hub
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_hub_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_private
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./examples/upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./examples/workload_identity
Success!
 The configuration is valid.
terraform_validate ./examples/workload_metadata_config
Success!
 The configuration is valid.
terraform_validate ./modules/acm
Success!
 The configuration is valid.
terraform_validate ./modules/asm
Success!
 The configuration is valid.
terraform_validate ./modules/auth
Success!
 The configuration is valid.
terraform_validate ./modules/beta-autopilot-private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-autopilot-public-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/binary-authorization
Success!
 The configuration is valid.
terraform_validate ./modules/fleet-membership
Success!
 The configuration is valid.
terraform_validate ./modules/hub-legacy
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/services
Success!
 The configuration is valid.
terraform_validate ./modules/workload-identity
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/beta_cluster
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on main.tf line 60, in module "this":
│
 
  60:   
istio
 = true
│
 
│
 
An argument named "istio" is not expected here.
╵
terraform_validate ./test/fixtures/deploy_service
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/disable_client_cert
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool_update_variant
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/private_zonal_with_networking
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster_iap_bastion
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/sandbox_enabled
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_autopilot_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_autopilot_public
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_networking
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_windows_node_pool
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_with_asm
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_identity
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_metadata_config
Success!
 The configuration is valid.
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@bharathkkb
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@bharathkkb
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@bharathkkb
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@bharathkkb
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@bharathkkb
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@bharathkkb
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by apeabody — APPROVED** [review]
LGTM!

**Pull request merged**
