### PR TITLE
fix!: Revert create least privilege default service account (#1757)

### PR DESCRIPTION
**Pull request by apeabody**
This reverts commit 350faa747659202de58bef64de67c94845b223ff.

### CODE REVIEW

**Comment by gorge511** [comment]
Hi @apeabody, why this is reverted to old solution and not to the new generally available role `roles/container.nodeServiceAgent`? Is there any reasoning I'm not aware of?

**Comment by apeabody** [comment]
> roles/container.nodeServiceAgent

Hi @gorge511 - I believe at the time of the revert that `roles/container.nodeServiceAgent` wasn't yet generally available. Would be happy to review a PR to switch it to now. We can include in the upcoming release.

**Comment by apeabody** [comment]
> > roles/container.nodeServiceAgent
> 
> Hi @gorge511 - I believe at the time of the revert that `roles/container.nodeServiceAgent` wasn't yet generally available. Would be happy to review a PR to switch it to now. We can include in the upcoming release.

I haven't had a chance to dig into the details, but looks like use of an *Agent* role isn't recommended for this propose: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1757#issuecomment-1889614996

**Comment by gorge511** [comment]
> I haven't had a chance to dig into the details, but looks like use of an _Agent_ role isn't recommended for this propose: [#1757 (comment)](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1757#issuecomment-1889614996)

Thanks for the quick response. Yes, it seems that the Agent role is not the right one, even if it looks really good for this use case 🙂 
I guess we should continue with the discussion in #1757, there are more people in the discussion.

**Pull request merged**
