### PR TITLE
fix: autopilot also supports managed prometheus

### PR DESCRIPTION
**Pull request by ykzts**
Follow-up #1307

#1307 is missing Autopilot support. This Pull Request will allow Managed Prometheus to be used with Autopilot as well.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@ykzts
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part1/terraform
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part2/terraform
Success!
 The configuration is valid.
terraform_validate ./examples/acm-terraform-blog-part3/terraform
Success!
 The configuration is valid.
terraform_validate ./examples/deploy_service
Success!
 The configuration is valid.
terraform_validate ./examples/disable_client_cert
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_beta
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_public_beta
Success!
 The configuration is valid.
terraform_validate ./examples/private_zonal_with_networking
Success!
 The configuration is valid.
terraform_validate ./examples/regional_private_node_pool_oauth_scopes
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster_iap_bastion
Success!
 The configuration is valid.
terraform_validate ./examples/shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/simple_autopilot_private
╷
│
 
Error: 
Reference to undeclared input variable
│
 
│
 
  on ../../modules/beta-autopilot-private-cluster/cluster.tf line 59, in resource "google_container_cluster" "primary":
│
 
  59:     for_each = 
var.monitoring_enable_managed_prometheus
 ? [1] : []
│
 
│
 
An input variable with the name "monitoring_enable_managed_prometheus" has
│
 
not been declared. This variable can be declared with a variable
│
 
"monitoring_enable_managed_prometheus" {} block.
╵
terraform_validate ./examples/simple_autopilot_public
╷
│
 
Error: 
Reference to undeclared input variable
│
 
│
 
  on ../../modules/beta-autopilot-public-cluster/cluster.tf line 59, in resource "google_container_cluster" "primary":
│
 
  59:     for_each = 
var.monitoring_enable_managed_prometheus
 ? [1] : []
│
 
│
 
An input variable with the name "monitoring_enable_managed_prometheus" has
│
 
not been declared. This variable can be declared with a variable
│
 
"monitoring_enable_managed_prometheus" {} block.
╵
terraform_validate ./examples/simple_regional
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_beta
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private_beta
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_networking
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_private
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_acm
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_asm
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_hub
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_hub_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_private
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./examples/upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./examples/workload_identity
Success!
 The configuration is valid.
terraform_validate ./examples/workload_metadata_config
Success!
 The configuration is valid.
terraform_validate ./modules/acm
Success!
 The configuration is valid.
terraform_validate ./modules/asm
Success!
 The configuration is valid.
terraform_validate ./modules/auth
Success!
 The configuration is valid.
terraform_validate ./modules/beta-autopilot-private-cluster
╷
│
 
Error: 
Reference to undeclared input variable
│
 
│
 
  on cluster.tf line 59, in resource "google_container_cluster" "primary":
│
 
  59:     for_each = 
var.monitoring_enable_managed_prometheus
 ? [1] : []
│
 
│
 
An input variable with the name "monitoring_enable_managed_prometheus" has
│
 
not been declared. This variable can be declared with a variable
│
 
"monitoring_enable_managed_prometheus" {} block.
╵
terraform_validate ./modules/beta-autopilot-public-cluster
╷
│
 
Error: 
Reference to undeclared input variable
│
 
│
 
  on cluster.tf line 59, in resource "google_container_cluster" "primary":
│
 
  59:     for_each = 
var.monitoring_enable_managed_prometheus
 ? [1] : []
│
 
│
 
An input variable with the name "monitoring_enable_managed_prometheus" has
│
 
not been declared. This variable can be declared with a variable
│
 
"monitoring_enable_managed_prometheus" {} block.
╵
terraform_validate ./modules/beta-private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/binary-authorization
Success!
 The configuration is valid.
terraform_validate ./modules/fleet-membership
Success!
 The configuration is valid.
terraform_validate ./modules/hub-legacy
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster-update-variant
Success!
 The configuration is valid.
terraform_validate ./modules/services
Success!
 The configuration is valid.
terraform_validate ./modules/workload-identity
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/beta_cluster
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/deploy_service
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/disable_client_cert
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool_update_variant
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/private_zonal_with_networking
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster_iap_bastion
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/sandbox_enabled
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_autopilot_private
╷
│
 
Error: 
Reference to undeclared input variable
│
 
│
 
  on ../../../modules/beta-autopilot-private-cluster/cluster.tf line 59, in resource "google_container_cluster" "primary":
│
 
  59:     for_each = 
var.monitoring_enable_managed_prometheus
 ? [1] : []
│
 
│
 
An input variable with the name "monitoring_enable_managed_prometheus" has
│
 
not been declared. This variable can be declared with a variable
│
 
"monitoring_enable_managed_prometheus" {} block.
╵
terraform_validate ./test/fixtures/simple_autopilot_public
╷
│
 
Error: 
Reference to undeclared input variable
│
 
│
 
  on ../../../modules/beta-autopilot-public-cluster/cluster.tf line 59, in resource "google_container_cluster" "primary":
│
 
  59:     for_each = 
var.monitoring_enable_managed_prometheus
 ? [1] : []
│
 
│
 
An input variable with the name "monitoring_enable_managed_prometheus" has
│
 
not been declared. This variable can be declared with a variable
│
 
"monitoring_enable_managed_prometheus" {} block.
╵
terraform_validate ./test/fixtures/simple_regional
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_kubeconfig
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_networking
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_with_asm
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_private
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/upstream_nameservers
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_identity
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_metadata_config
Success!
 The configuration is valid.
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@ykzts
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @ykzts

**Comment by dkamenov-fitted** [comment]
@ykzts, how are you able to get a managed prometheus instance on an Auto Pilot GKE instance?

`Error: googleapi: Error 400: Managed Prometheus is not supported for Autopilot clusters., badRequest`

This was the error I got back when trying to enable the managed Prometheus instance on such a GKE instance.

**Pull request merged**
