### PR TITLE
feat: Make confidential_nodes GA

### PR DESCRIPTION
**Pull request by DrFaust92**

### CODE REVIEW

**Comment by t-indumathy** [comment]
@apeabody May I know the details of failed checks. Don't have access to the build logs.

**Comment by apeabody** [comment]
> @apeabody May I know the details of failed checks. Don't have access to the build logs.

Hi @t-indumathy - It's unclear if this is related to the change, so I'll trigger another run:

```
TestSimpleZonalWithASM 2024-01-19T01:13:56Z command.go:185: module.example.module.gke.google_container_cluster.primary: Creating...
TestSimpleZonalWithASM 2024-01-19T01:14:06Z command.go:185: module.example.module.gke.google_container_cluster.primary: Still creating... [10s elapsed]
TestSimpleZonalWithASM 2024-01-19T01:14:16Z command.go:185: module.example.module.gke.google_container_cluster.primary: Still creating... [20s elapsed]
TestSimpleZonalWithASM 2024-01-19T01:14:26Z command.go:185: module.example.module.gke.google_container_cluster.primary: Still creating... [30s elapsed]
TestSimpleZonalWithASM 2024-01-19T01:14:31Z command.go:185: 
TestSimpleZonalWithASM 2024-01-19T01:14:31Z command.go:185: Error: Error waiting for creating GKE cluster: Failed to create cluster
TestSimpleZonalWithASM 2024-01-19T01:14:31Z command.go:185: 
TestSimpleZonalWithASM 2024-01-19T01:14:31Z command.go:185:   with module.example.module.gke.google_container_cluster.primary,
TestSimpleZonalWithASM 2024-01-19T01:14:31Z command.go:185:   on ../../../cluster.tf line 22, in resource "google_container_cluster" "primary":
TestSimpleZonalWithASM 2024-01-19T01:14:31Z command.go:185:   22: resource "google_container_cluster" "primary" {
```

**Comment by t-indumathy** [comment]
@DrFaust92 Can you please sync your fork with upstream to reflect the new changes.

**Comment by t-indumathy** [comment]
@apeabody Kindly review.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @DrFaust92!

**Pull request merged**
