### PR TITLE
Set security relevant settings on default node pool to comply with Sentinel

### PR DESCRIPTION
**Pull request by MajorBreakfast**
This PR adds some security relevant settings to the default node pool that exists temporarily during cluster creation to satisfy Terraform Enterprise Sentinel policies defined by CSO at my project.

### CODE REVIEW

**Comment by MajorBreakfast** [comment]
@morgante Thank you for the quick feedback!

I've removed the sandbox from the PR to make the tests pass. Sentinel policy enforcement currently only happens for the integrity monitoring, so it's not necessary at this point.

**Comment by MajorBreakfast** [comment]
Change of strategy: Now setting the machine type and image as well based on the value of node pool 0. This should fix it and make it so that even the gvisor can be activated

**Comment by MajorBreakfast** [comment]
Green tests ✌️

**Review by morgante — APPROVED** [review]

**Pull request merged**
