### PR TITLE
feat!: Add option to pass `resource_labels` to NP

### LINKED ISSUE #1507: Add the option to pass `resource_labels` to individual node pools
### TL;DR

[Resource labels](https://cloud.google.com/kubernetes-engine/docs/how-to/creating-managing-labels#label_propagation) can be applied on the cluster level, or on the node pool level by passing `node_config.resource_labels`.

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#resource_labels
```

### Detailed design

```markdown
Sometimes a user would want to configure resource labels on the node pool level (for cost allocation, etc).
This is currently possible to do with the Terraform Google provider, though not with the modules provided in this repository.

This can be done in the same way that `node_pools_labels` are passed down to node pool resources, but will of course require an additional variable to do so.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eyalzek**
For configuring resource labels on a per node pool basis.

Fixes #1507

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@eyalzek
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @eyalzek 
Let's also bump the min provider versions to 4.45.0 https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/autogen/main/versions.tf.tmpl

**Comment by comment-bot-dev** [comment]
@eyalzek
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Comment by comment-bot-dev** [comment]
@eyalzek
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
