### PR TITLE
[ASM module] Document ASM module data source workaround

### PR DESCRIPTION
**Pull request by Monkeyanator**
Documents workaround for https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1181

### CODE REVIEW

**Review by morgante — COMMENTED** [review]
Honestly I think we should just fix the module. It would be faster/simpler than this.

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by Monkeyanator** [comment]
> Documents workaround for #1181

Opened https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1189, if that approach looks good will close this.

**Comment by bharathkkb** [comment]
@morgante I am thinking it could be worth documenting this (without the workaround code) incase the user is using plain resources or a different module? The error surfaced is not very actionable.

**Comment by morgante** [comment]
> @morgante I am thinking it could be worth documenting this (without the workaround code) incase the user is using plain resources or a different module? The error surfaced is not very actionable.

Good point, but I think we should document it just by saying you must make the name dependent on the GKE cluster resource. I don't think we should use the `locals` hack as it's messy/unnecessary.

**Comment by Monkeyanator** [comment]
Closing in favor of https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1189

**Pull request closed without merging**
