### PR TITLE
[wait-for-cluster.sh] Update the script in all submodules.

### PR DESCRIPTION
**Pull request by omazin**
Follows up #284

### CODE REVIEW

**Comment by paulpalamarchuk** [comment]
@omazin please update sh-script in autogen directory (`autogen/scripts/wait-for-cluster.sh`)

**Comment by omazin** [comment]
@paulpalamarchuk updated

**Comment by omazin** [comment]
Updated, without the fix it would throw the following error when `terraform create / destroy`:
```
module.gke.null_resource.wait_for_cluster (local-exec): ERROR: (gcloud.container.clusters.list) ResponseError: code=403, message=Required "container.clusters.list" permission(s) for "projects/your-project-id".
```

**Comment by aaron-lane** [comment]
Merging since the test timeout will be addressed with #292 and this solves a regression in the generation diff.

**Pull request merged**
