### PR TITLE
feat: add optional private_endpoint_subnetwork variable in private submodules

### LINKED ISSUE #1987: Expose `private_endpoint_subnetwork` on `beta-private-cluster*` modules
### TL;DR

When setting up a private cluster with private endpoint, Google now creates an extra VPC subnet for the API server endpoint. We'd like to create a subnet on our own and use this for the endpoint by passing it in [`private_endpoint_subnetwork`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#private_endpoint_subnetwork).

### Terraform Resources

```markdown
This is the field I'm talking about:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#private_endpoint_subnetwork
```

### Detailed design

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by pib**
Fixes #1987

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @pib!

Can you please rebase.

**Comment by apeabody** [comment]
Thanks @pib! - From the PR title is the intention to only add for beta submodules?  Currently it appears this is being added for all private clusters?  To add for just beta you can enclose the new code section in `{% if beta_cluster %}` `{% endif %}`.

**Comment by pib** [comment]
> Thanks @pib! - From the PR title is the intention to only add for beta submodules? Currently it appears this is being added for all private clusters? To add for just beta you can enclose the new code section in `{% if beta_cluster %}` `{% endif %}`.

Ah, based on issue #1987 I had assumed that field was only available in the beta provider, but I see it is available in the non-beta provider as well, so really it should just be "in private submodules".

**Comment by pib** [comment]
@apeabody should I also amend the commit so it has the correct message? I'm not sure if release-please will use the PR title or the actual commit message.

**Comment by apeabody** [comment]
> @apeabody should I also amend the commit so it has the correct message? I'm not sure if release-please will use the PR title or the actual commit message.

Thanks! We always squash merge, so it will use the title of the PR (not the commits).

**Comment by pib** [comment]
Whoops, sorry, that "Close with comment" button is really close to the "Comment" button :|

**Comment by apeabody** [comment]
> Whoops, sorry, that "Close with comment" button is really close to the "Comment" button :|

Agreed, I've done that by accident more than once!

**Review by apeabody — APPROVED** [review]

**Pull request merged**
