### PR TITLE
feat: Add nodepool taints to keepers for update-variant

### PR DESCRIPTION
**Pull request by jinoobaek-qz**
Add node_pool_taints to force new.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate . 
Success!
 The configuration is valid.
terraform_validate ./examples/deploy_service 
Success!
 The configuration is valid.
terraform_validate ./examples/disable_client_cert 
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool 
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant 
Success!
 The configuration is valid.
terraform_validate ./examples/node_pool_update_variant_beta 
Error verifying checksum for provider "google"
The checksum for provider distribution from the Terraform Registry
did not match the source. This may mean that the distributed files
were changed after this version was released to the Registry.
Error: 
unable to verify checksum
terraform_validate ./examples/private_zonal_with_networking 
Success!
 The configuration is valid.
terraform_validate ./examples/regional_private_node_pool_oauth_scopes 
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster 
Success!
 The configuration is valid.
terraform_validate ./examples/safer_cluster_iap_bastion 
Success!
 The configuration is valid.
terraform_validate ./examples/shared_vpc 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_beta 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_private_beta 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_kubeconfig 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_regional_with_networking 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_private 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_acm 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_asm 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_zonal_with_hub 
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains 
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_private 
Success!
 The configuration is valid.
terraform_validate ./examples/stub_domains_upstream_nameservers 
Success!
 The configuration is valid.
terraform_validate ./examples/upstream_nameservers 
Success!
 The configuration is valid.
terraform_validate ./examples/workload_identity 
Success!
 The configuration is valid.
terraform_validate ./examples/workload_metadata_config 
Success!
 The configuration is valid.
terraform_validate ./modules/acm 
Success!
 The configuration is valid.
terraform_validate ./modules/asm 
Error installing provider "null": read tcp 192.168.10.2:36620->151.101.1.183:443: read: connection reset by peer.
Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.
This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.
If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64
Error: 
read tcp 192.168.10.2:36620->151.101.1.183:443: read: connection reset by peer
terraform_validate ./modules/auth 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-private-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/beta-public-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/binary-authorization 
Success!
 The configuration is valid.
terraform_validate ./modules/config-sync 
Success!
 The configuration is valid.
terraform_validate ./modules/hub 
Success!
 The configuration is valid.
terraform_validate ./modules/k8s-operator-crd-support 
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/private-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster 
Success!
 The configuration is valid.
terraform_validate ./modules/safer-cluster-update-variant 
Success!
 The configuration is valid.
terraform_validate ./modules/services 
Success!
 The configuration is valid.
terraform_validate ./modules/workload-identity 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/beta_cluster 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/deploy_service 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/disable_client_cert 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/node_pool_update_variant 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/private_zonal_with_networking 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/safer_cluster_iap_bastion 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/sandbox_enabled 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_private 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_kubeconfig 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_regional_with_networking 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_private 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_zonal_with_asm 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_private 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/stub_domains_upstream_nameservers 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/upstream_nameservers 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_identity 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/workload_metadata_config 
Success!
 The configuration is valid.
terraform_validate ./test/setup 
Success!
 The configuration is valid.
 ```

**Review by bharathkkb — CHANGES_REQUESTED** [review]
Thanks for the PR!
We need to propagate this change to all the other modules by running `make build`. [More details here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/CONTRIBUTING.md#templating).

**Comment by bharathkkb** [comment]
I changed the logic from the initial PR based on the schema in `node_config`.

**Review by morgante — APPROVED** [review]

**Comment by jmymy** [comment]
FYI this forces recreation of all node pools since the random_id has a change
```
+/- resource "random_id" "name" {
      ~ b64_std     = "pool-01-XXX=" -> (known after apply)
      ~ b64_url     = "pool-01-XXX" -> (known after apply)
      ~ dec         = "pool-01-XXXX" -> (known after apply)
      ~ hex         = "pool-01-XXXX" -> (known after apply)
      ~ id          = "Thg" -> (known after apply)
      ~ keepers     = { # forces replacement
          + "taints"            = ""
            # (12 unchanged elements hidden)
        }
        # (2 unchanged attributes hidden)
    }

+/- resource "google_container_node_pool" "pools" {
      ~ id                  = "<REMOVED/pool-01-XXX" -> (known after apply)
      ~ instance_group_urls = [ ] -> (known after apply)
      ~ max_pods_per_node   = 110 -> (known after apply)
      ~ name                = "pool-01-XXX" -> (known after apply) # forces replacement
```

**Pull request merged**
