### PR TITLE
ASM module rewrite improvements

### LINKED ISSUE #1164: ASM Module improvements
### TL;DR

Before we release the new ASM module, a number of things need to be addressed:

- [ ] We need a full upgrade guide for how to upgrade an existing cluster.
- [ ] The [hub feature and membership](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1140/files#diff-9e87345497361239a98497e4d5a297913b563e0c196762018a48209b7689254cR17-R33) should be moved into the module. These can be controlled via a variable.

### Expected behavior

_No response_

### Observed behavior

_No response_

### Terraform Configuration

```hcl
N/A
```

### Terraform Version

```sh
N/A
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Monkeyanator**
Fixes #1164. Adds the `enable_fleet_registration` and `enable_mesh_feature` variables, documents a best-effort upgrade path from the previous module

### CODE REVIEW

**Review by morgante — APPROVED** [review]

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Can we remove this https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/examples/simple_zonal_with_asm/hub.tf and use the new flags instead?

**Comment by Monkeyanator** [comment]
> Can we remove this https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/examples/simple_zonal_with_asm/hub.tf and use the new flags instead?

Done, thanks

**Comment by bharathkkb** [comment]
@Monkeyanator Looks like some ASM tests may need an update

**Review by morgante — APPROVED** [review]

**Pull request merged**
